// Todo el contenido del sitio vive aquí, en español (es) e inglés (en).
// Para actualizar datos (notas Fraser, fechas, programas) edita solo este archivo.

export const FRASER = {
  report: { es: "Informe Fraser 2025 (año escolar 2024-25)", en: "Fraser Institute 2025 Report Card (2024-25 school year)" },
  url: "https://www.fraserinstitute.org/sites/default/files/2025-11/ontario-secondary-school-rankings-2025_0.pdf",
  site: "https://www.compareschoolrankings.org/",
};

export const UI = {
  es: {
    htmlLang: "es",
    title: "Guía de Secundarias en Mississauga | Highschool Navigator",
    metaDesc: "Guía informativa de secundarias católicas y públicas en Mississauga (DPCDSB y Peel): escuelas, programas regionales, AP, IB, fechas de solicitud y nota Fraser, con filtros y comparador.",
    skip: "Saltar al contenido",
    eyebrow: "Mississauga · Ingreso a Grade 9, septiembre 2027",
    h1: "Guía de Secundarias en Mississauga",
    lead: "Qué escuelas y programas existen en Mississauga Este, qué ofrece cada uno y cómo se entra. Una guía para conversar en familia con la misma información.",
    factBoards: "Sistemas:",
    factBoardsV: "DPCDSB (católico) y Peel (público)",
    factSchools: "Escuelas destacadas:",
    factSchoolsV: "4 secundarias católicas de Mississauga Este",
    notice: "<b>Esta guía describe la oferta; no recomienda ninguna escuela.</b> Incluye la nota pública del Fraser Institute como referencia de cómo se percibe cada escuela en resultados académicos. No mide programas, ambiente ni ajuste a cada estudiante.",
    nav: { capas: "Cómo leer el mapa", explorar: "Explorar y filtrar", escuelas: "4 escuelas", comparar: "Comparar", regionales: "Programas regionales", peel: "Peel", grados: "Desde qué grado", siglas: "Siglas", fechas: "Fechas", preguntas: "Preguntas" },
    navLabel: "Secciones",
    langLabel: "Idioma",
    themeLabel: "Cambiar tema",

    capasH: "Cómo leer el mapa",
    capasP: "Las opciones no son equivalentes. Hay cuatro niveles distintos y algunos se pueden combinar.",
    layers: [
      { tag: "Nivel 1", h: "Escuela", p: "El edificio donde estudias. Toda escuela ofrece la secundaria regular completa, más algunos extras propios." },
      { tag: "Nivel 2", h: "Programa regional", p: "Un programa especial que vive en ciertas escuelas y recibe estudiantes de toda la zona. Casi siempre se solicita, y el transporte puede ser por cuenta de la familia." },
      { tag: "Nivel 3", h: "Especialización", p: "Una ruta dentro de una escuela, como SHSM o Co-op. Se cursa sobre todo en Grades 11 y 12." },
      { tag: "Nivel 4", h: "Pathway", p: "Hacia dónde conduce todo: universidad, college, apprenticeship o trabajo. Depende de las combinaciones que se elijan." },
    ],

    exploreH: "Explorar y filtrar",
    exploreP: "Filtra escuelas y programas por sistema, tipo, grado de inicio y forma de ingreso. Los filtros afectan las secciones de escuelas y programas de más abajo.",
    searchLabel: "Buscar",
    searchPh: "Ej. IB, panadería, arte, francés…",
    fSystem: "Sistema", fStart: "Empieza en", fEntry: "Cómo se entra",
    all: "Todos",
    optSystem: { dpcdsb: "DPCDSB (católico)", peel: "Peel (público)" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automática (boundary)", apply: "Requiere solicitud o transferencia" },
    reset: "Limpiar filtros",
    resultCount: (n) => `${n} resultado${n === 1 ? "" : "s"}`,
    noResults: "No hay resultados con esos filtros. Prueba a limpiarlos.",

    escuelasH: "Las 4 escuelas de Mississauga Este",
    escuelasP: "Las cuatro pertenecen al Dufferin-Peel Catholic District School Board (DPCDSB). Cada una tiene un carácter distinto. La nota Fraser es solo académica y no ordena esta lista.",
    lblFocus: "Enfoque:",
    fraserLabel: "Nota Fraser",
    fraserOf: "/ 10",
    fraserRank: (r) => `Puesto ${r} en Ontario`,
    fraserPrev: (p) => `Año anterior: ${p}`,
    fraserFoot: "Fuente: ",
    fraserWhatH: "Qué mide (y qué no) la nota Fraser",
    fraserWhat: "Se calcula con resultados de exámenes provinciales: matemáticas de Grade 9 (Academic y Applied), Ontario Secondary School Literacy Test (OSSLT), porcentaje de pruebas por debajo del estándar y de pruebas no rendidas, y brechas entre géneros. No mide artes, deportes, programas técnicos, ambiente, apoyo ni idiomas. El contexto socioeconómico y el tamaño de la muestra influyen, y las notas cambian de un año a otro. Úsala como una referencia más, no como veredicto.",
    compare: "Comparar",
    comparing: "En la comparación",

    compararH: "Comparador de escuelas",
    compararP: "Marca las escuelas de arriba con «Comparar» (o usa los botones) para verlas lado a lado.",
    compRows: { fraser: "Nota Fraser (2024-25)", rank: "Puesto en Ontario", prev: "Nota año anterior", focus: "Enfoque", entry: "Cómo se entra", shsm: "Especializaciones (SHSM)", distinct: "Distintivo", langs: "Idiomas", addr: "Ubicación" },
    compEmpty: "Selecciona al menos dos escuelas para compararlas.",
    compCol: "Escuela",

    regionalesH: "Programas regionales del DPCDSB",
    regionalesP: "Están un poco más lejos, pero son opciones reales para una familia de Mississauga. La escuela sede es donde se cursa el programa.",
    peelH: "El otro sistema: Peel District School Board",
    peelP: "Los Regional Learning Choices Programs (RLCP) de Peel están abiertos a estudiantes que viven en Peel, incluidos los que hoy estudian en el sistema católico. Conviene conocerlos antes de descartar nada.",
    host: "Sede: ",
    peelHowH: "Cómo funciona",
    peelHow: "Entrada en Grade 9 por solicitud en línea. Hay una tarifa de solicitud y una tarifa anual por programa. Peel planea dar transporte en Grades 6 a 10, sujeto a financiamiento del Ministerio.",
    peelRuleH: "Regla importante",
    peelRule: "Primero se ofrecen cupos a quienes viven en Peel y cumplen los criterios. Los programas suelen estar en varias escuelas, y el boundary depende de la dirección de casa.",
    startsAt: { "9": "Desde Gr 9", "10": "Desde Gr 10", "11": "Desde Gr 11" },

    gradosH: "¿Desde qué grado empieza cada cosa?",
    gradosP: "Varias opciones no aparecen hasta Grade 10 u 11. Por eso conviene ver el recorrido completo antes de decidir por Grade 9.",
    tlOption: "Opción",
    tlConfirmed: "Confirmado",
    tlSoft: "Preparación o rango típico, por confirmar con cada escuela",
    timeline: [
      { label: "Secundaria regular", sub: "Cualquier escuela", from: 1, to: 5, txt: "Cursos regulares", soft: false },
      { label: "AP", sub: "Por materia", segs: [[1, 3, "Preparación", true], [3, 5, "Cursos y exámenes AP", false]] },
      { label: "IB", sub: "Diploma de dos años", segs: [[1, 3, "Secuencia previa", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Programas regionales", from: 1, to: 5, txt: "Desde Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grades 10 a 12", soft: false },
      { label: "SHSM", sub: "Especialización", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Experiencia laboral con crédito", from: 3, to: 5, txt: "Senior grades", soft: false },
      { label: "OYAP y Dual Credit", sub: "Oficios y college", from: 3, to: 5, txt: "Normalmente 11–12", soft: true },
    ],

    siglasH: "Siglas en una línea",
    glossary: [
      ["AP", "Cursos de nivel universitario, materia por materia.", "Modular y flexible."],
      ["IB", "Diploma completo y estructurado de dos años.", "Todo el paquete, no materias sueltas."],
      ["SHSM", "Specialist High Skills Major: una especialización de sector (ICT, Hospitality, Transportation, Arts y otros) con cursos, certificaciones y Co-op.", "Se cursa en Gr 11–12."],
      ["Co-op", "Estudiar y trabajar en una empresa real, y recibir créditos por ello.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: empezar un aprendizaje de oficio mientras se termina la secundaria.", ""],
      ["Dual Credit", "Cursos de college que cuentan también para el diploma de secundaria.", ""],
      ["Feeder", "La secundaria que corresponde por defecto a una escuela primaria.", ""],
      ["Boundary", "El área de residencia que decide a qué escuela se asiste sin solicitar nada.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: prueba provincial de lectoescritura, base de parte de la nota Fraser.", ""],
    ],

    fechasH: "Fechas para el calendario",
    fechasP: "Estas son las fechas que ya se conocen. Confírmalas siempre en el sitio de cada board o escuela.",
    dates: [
      { when: "Oct–nov 2026", b: "Charlas y open houses del DPCDSB", p: "para Grade 8. Cada escuela publica su propia fecha en su sitio." },
      { when: "3–24 nov 2026", b: "Solicitudes RLCP de Peel", p: "para el año escolar 2027-28. Peel suele tener noches informativas justo antes." },
      { when: "Por confirmar", b: "Solicitudes de programas regionales DPCDSB", p: "(AP, IB, Arts, Sports, STEAM, Bakery). Se confirma en cada charla." },
    ],

    preguntasH: "Preguntas para llevar a las charlas",
    preguntasP: "Para escuchar con criterio y no solo la presentación de cada escuela.",
    questions: [
      "¿Qué tiene esta escuela que no tenga la de al lado?",
      "¿Qué programas requieren solicitud y hasta cuándo?",
      "¿Qué se puede tomar desde Grade 9 y qué solo en Grades 11–12?",
      "¿Qué notas o requisitos piden, y hay audición o portafolio?",
      "¿Hay transporte, o lo cubre la familia? ¿Qué costos extra hay?",
      "¿Qué certificaciones se obtienen y qué Co-op existe?",
      "¿Con qué universidades, colleges o industria trabajan?",
      "¿Se pueden combinar programas, por ejemplo IB con Co-op?",
    ],

    pendingH: "Lo que falta por confirmar",
    pendingP: "Datos que no se pudieron verificar y que conviene revisar en cada charla o sitio de la escuela.",
    pending: [
      "Distancia exacta desde casa y direcciones de Cabot y St. Francis Xavier",
      "Segunda sede de AP del DPCDSB y la lista completa de SHSM de cada escuela",
      "Costos, transporte y fechas de solicitud de los programas regionales del DPCDSB",
      "Requisitos académicos y audiciones de Arts, Sports y STEAM",
      "La nota Fraser se actualiza cada otoño: revisa el informe más reciente",
    ],
    sourcesH: "Fuentes consultadas",
    disclaimer: "Sitio informativo independiente, sin afiliación con el DPCDSB, Peel ni el Fraser Institute. La información puede cambiar: verifica siempre en las fuentes oficiales.",
    backTop: "Volver arriba",
  },

  en: {
    htmlLang: "en",
    title: "Mississauga High School Guide | Highschool Navigator",
    metaDesc: "Informational guide to Catholic and public high schools in Mississauga (DPCDSB and Peel): schools, regional programs, AP, IB, application dates and Fraser scores, with filters and a comparison tool.",
    skip: "Skip to content",
    eyebrow: "Mississauga · Grade 9 entry, September 2027",
    h1: "Mississauga High School Guide",
    lead: "Which schools and programs exist in east Mississauga, what each one offers and how to get in. A guide so the family can talk with the same information.",
    factBoards: "Boards:",
    factBoardsV: "DPCDSB (Catholic) and Peel (public)",
    factSchools: "Featured schools:",
    factSchoolsV: "4 Catholic high schools in east Mississauga",
    notice: "<b>This guide describes what is offered; it does not recommend any school.</b> It includes the Fraser Institute's public score as a reference for how each school is perceived on academic results. It does not measure programs, atmosphere or fit for each student.",
    nav: { capas: "How to read the map", explorar: "Explore & filter", escuelas: "4 schools", comparar: "Compare", regionales: "Regional programs", peel: "Peel", grados: "Which grade", siglas: "Glossary", fechas: "Dates", preguntas: "Questions" },
    navLabel: "Sections",
    langLabel: "Language",
    themeLabel: "Toggle theme",

    capasH: "How to read the map",
    capasP: "The options are not equivalent. There are four different levels and some can be combined.",
    layers: [
      { tag: "Level 1", h: "School", p: "The building where you study. Every school offers the full regular high school program, plus some extras of its own." },
      { tag: "Level 2", h: "Regional program", p: "A special program housed in certain schools that takes students from the whole area. It almost always requires an application, and transportation may be the family's responsibility." },
      { tag: "Level 3", h: "Specialization", p: "A pathway inside a school, such as SHSM or Co-op. Mostly taken in Grades 11 and 12." },
      { tag: "Level 4", h: "Pathway", p: "Where it all leads: university, college, apprenticeship or work. It depends on the combinations chosen." },
    ],

    exploreH: "Explore & filter",
    exploreP: "Filter schools and programs by board, type, starting grade and how you get in. Filters apply to the schools and programs sections below.",
    searchLabel: "Search",
    searchPh: "E.g. IB, bakery, arts, French…",
    fSystem: "Board", fStart: "Starts in", fEntry: "How to get in",
    all: "All",
    optSystem: { dpcdsb: "DPCDSB (Catholic)", peel: "Peel (public)" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automatic (boundary)", apply: "Application or transfer required" },
    reset: "Clear filters",
    resultCount: (n) => `${n} result${n === 1 ? "" : "s"}`,
    noResults: "No results for those filters. Try clearing them.",

    escuelasH: "The 4 schools in east Mississauga",
    escuelasP: "All four belong to the Dufferin-Peel Catholic District School Board (DPCDSB). Each has a different character. The Fraser score is academic only and does not order this list.",
    lblFocus: "Focus:",
    fraserLabel: "Fraser score",
    fraserOf: "/ 10",
    fraserRank: (r) => `Rank ${r} in Ontario`,
    fraserPrev: (p) => `Previous year: ${p}`,
    fraserFoot: "Source: ",
    fraserWhatH: "What the Fraser score measures (and what it does not)",
    fraserWhat: "It is calculated from provincial test results: Grade 9 math (Academic and Applied), the Ontario Secondary School Literacy Test (OSSLT), the share of tests below standard and of tests not written, and gender gaps. It does not measure arts, sports, technical programs, atmosphere, support or languages. Socioeconomic context and sample size matter, and scores change from year to year. Use it as one reference, not a verdict.",
    compare: "Compare",
    comparing: "In comparison",

    compararH: "School comparison",
    compararP: "Tick “Compare” on the schools above (or use the buttons) to see them side by side.",
    compRows: { fraser: "Fraser score (2024-25)", rank: "Rank in Ontario", prev: "Previous year score", focus: "Focus", entry: "How to get in", shsm: "Specializations (SHSM)", distinct: "What stands out", langs: "Languages", addr: "Location" },
    compEmpty: "Select at least two schools to compare them.",
    compCol: "School",

    regionalesH: "DPCDSB regional programs",
    regionalesP: "They are a bit farther away, but they are real options for a Mississauga family. The host school is where the program is taken.",
    peelH: "The other system: Peel District School Board",
    peelP: "Peel's Regional Learning Choices Programs (RLCP) are open to students who live in Peel, including those currently in the Catholic system. Worth knowing before ruling anything out.",
    host: "Host: ",
    peelHowH: "How it works",
    peelHow: "Grade 9 entry by online application. There is an application fee and an annual per-program fee. Peel plans to provide transportation in Grades 6 to 10, subject to Ministry funding.",
    peelRuleH: "Important rule",
    peelRule: "Places are first offered to those who live in Peel and meet the criteria. Programs are often in several schools, and the boundary depends on your home address.",
    startsAt: { "9": "From Gr 9", "10": "From Gr 10", "11": "From Gr 11" },

    gradosH: "From which grade does each thing start?",
    gradosP: "Several options do not appear until Grade 10 or 11. That is why it helps to see the whole path before deciding on Grade 9.",
    tlOption: "Option",
    tlConfirmed: "Confirmed",
    tlSoft: "Preparation or typical range, to be confirmed with each school",
    timeline: [
      { label: "Regular high school", sub: "Any school", from: 1, to: 5, txt: "Regular courses", soft: false },
      { label: "AP", sub: "Subject by subject", segs: [[1, 3, "Preparation", true], [3, 5, "AP courses and exams", false]] },
      { label: "IB", sub: "Two-year diploma", segs: [[1, 3, "Prior sequence", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Regional programs", from: 1, to: 5, txt: "From Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grades 10 to 12", soft: false },
      { label: "SHSM", sub: "Specialization", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Work experience for credit", from: 3, to: 5, txt: "Senior grades", soft: false },
      { label: "OYAP & Dual Credit", sub: "Trades and college", from: 3, to: 5, txt: "Usually 11–12", soft: true },
    ],

    siglasH: "Acronyms in one line",
    glossary: [
      ["AP", "University-level courses, subject by subject.", "Modular and flexible."],
      ["IB", "A complete, structured two-year diploma.", "The whole package, not single subjects."],
      ["SHSM", "Specialist High Skills Major: a sector specialization (ICT, Hospitality, Transportation, Arts and others) with courses, certifications and Co-op.", "Taken in Gr 11–12."],
      ["Co-op", "Study and work at a real company, and earn credits for it.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: start a trade apprenticeship while finishing high school.", ""],
      ["Dual Credit", "College courses that also count toward the high school diploma.", ""],
      ["Feeder", "The high school that is the default for a given elementary school.", ""],
      ["Boundary", "The residence area that decides which school you attend without applying.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: the provincial literacy test, part of the basis of the Fraser score.", ""],
    ],

    fechasH: "Dates for your calendar",
    fechasP: "These are the dates already known. Always confirm them on each board's or school's website.",
    dates: [
      { when: "Oct–Nov 2026", b: "DPCDSB talks and open houses", p: "for Grade 8. Each school publishes its own date on its website." },
      { when: "Nov 3–24, 2026", b: "Peel RLCP applications", p: "for the 2027-28 school year. Peel usually holds information nights right before." },
      { when: "To be confirmed", b: "DPCDSB regional program applications", p: "(AP, IB, Arts, Sports, STEAM, Bakery). Confirmed at each talk." },
    ],

    preguntasH: "Questions to bring to the info sessions",
    preguntasP: "To listen critically and not just to each school's presentation.",
    questions: [
      "What does this school have that the one next door doesn't?",
      "Which programs require an application, and by when?",
      "What can be taken from Grade 9 and what only in Grades 11–12?",
      "What grades or requirements are needed, and is there an audition or portfolio?",
      "Is there transportation, or does the family cover it? What extra costs are there?",
      "What certifications can be earned and what Co-op exists?",
      "Which universities, colleges or industries do they work with?",
      "Can programs be combined, for example IB with Co-op?",
    ],

    pendingH: "What is still to be confirmed",
    pendingP: "Data that could not be verified and that is worth checking at each info session or school website.",
    pending: [
      "Exact distance from home and addresses of Cabot and St. Francis Xavier",
      "DPCDSB's second AP host and each school's complete list of SHSMs",
      "Costs, transportation and application dates for DPCDSB regional programs",
      "Academic requirements and auditions for Arts, Sports and STEAM",
      "Fraser scores are updated every autumn",
    ],
    sourcesH: "Sources consulted",
    disclaimer: "Independent informational site, not affiliated with DPCDSB, Peel or the Fraser Institute. Information may change: always verify with official sources.",
    backTop: "Back to top",
  },
};

export const SOURCES = [
  ["DPCDSB, Regional & Local Programs", "https://www.dpcdsb.org/programs-services/regional-local-programs"],
  ["DPCDSB, International Baccalaureate", "https://www.dpcdsb.org/programs-services/secondary/international-baccalaureate"],
  ["DPCDSB, Regional Advanced Placement", "https://www.dpcdsb.org/programs-services/secondary/advanced-placement"],
  ["DPCDSB, Canada Bakery School 2026-27", "https://www.dpcdsb.org/dpcdsb/news/post/dpcdsb-now-accepting-applications-for-canada-bakery-school-regional-program-2026-27"],
  ["Peel, Secondary Regional Learning Choices Programs", "https://www.peelschools.org/secondary-regional-learning-choice-programs"],
  ["Peel, SciTech", "https://www.peelschools.org/scitech"],
  ["Fraser Institute, Report Card on Ontario's Secondary Schools 2025", FRASER.url],
];

// entry: "auto" | "apply". start: "9" | "10" | "11". system: "dpcdsb" | "peel".
export const SCHOOLS = [
  {
    id: "goetz", mono: "FMG", cls: "", name: "Father Michael Goetz", addr: "330 Central Pkwy W",
    system: "dpcdsb", start: "9", entry: "auto",
    fraser: { score: 4.0, rank: 654, prev: 5.2 },
    chips: [{ t: { es: "Entrada automática si vives en su boundary", en: "Automatic entry if you live in its boundary" }, k: "auto" }],
    focus: { es: "secundaria completa con tecnología y un programa técnico de panadería. No es una escuela «de bakery».", en: "full high school with technology and a technical bakery program. It is not a “bakery school” overall." },
    kv: {
      distinct: { es: "Regional Bakery School: cuatro cursos de panadería en Grades 10 a 12, con Co-op u OYAP. Primer año 2026-27.", en: "Regional Bakery School: four bakery courses in Grades 10 to 12, with Co-op or OYAP. First year 2026-27." },
      shsm: { es: "SHSM en Information & Communications Technology (ICT) y en Arts & Culture", en: "SHSM in Information & Communications Technology (ICT) and in Arts & Culture" },
      langs: { es: "También Computer Science y Co-op", en: "Also Computer Science and Co-op" },
      entry: { es: "Regular: automática si vives en su boundary. Bakery: requiere solicitud.", en: "Regular: automatic if you live in its boundary. Bakery: application required." },
    },
    tags: "bakery panadería technology tecnología ict computer science co-op arts",
  },
  {
    id: "pocock", mono: "PP", cls: "pocock", name: "Philip Pocock", addr: "4555 Tomken Rd",
    system: "dpcdsb", start: "9", entry: "apply",
    fraser: { score: 5.9, rank: 401, prev: 7.0 },
    chips: [{ t: { es: "Transferencia (fuera de boundary)", en: "Transfer (outside boundary)" }, k: "apply" }],
    focus: { es: "combinación visible de idiomas, artes, hospitality y áreas técnicas.", en: "a visible mix of languages, arts, hospitality and technical areas." },
    kv: {
      distinct: { es: "SHSM de Transportation, ligado a áreas técnicas", en: "Transportation SHSM, tied to technical fields" },
      shsm: { es: "SHSM en Arts & Culture, Hospitality & Tourism y Transportation", en: "SHSM in Arts & Culture, Hospitality & Tourism and Transportation" },
      langs: { es: "French Immersion y Extended French", en: "French Immersion and Extended French" },
      entry: { es: "Se pide transferencia a través de la escuela. Los programas de francés pueden tener su propio proceso.", en: "Transfer requested through the school. French programs may have their own process." },
    },
    tags: "french francés immersion hospitality tourism transportation arts idiomas",
  },
  {
    id: "cabot", mono: "JC", cls: "cabot", name: "John Cabot", addr: "Mississauga East",
    system: "dpcdsb", start: "9", entry: "apply",
    fraser: { score: 4.4, rank: 620, prev: 5.8 },
    chips: [{ t: { es: "Transferencia (fuera de boundary)", en: "Transfer (outside boundary)" }, k: "apply" }],
    focus: { es: "negocios, tecnología y medios digitales, con ruta clara al emprendimiento.", en: "business, technology and digital media, with a clear path to entrepreneurship." },
    kv: {
      distinct: { es: "Mezcla tecnología con creatividad y negocios. Incluye animación, cine y fotografía, no solo programación.", en: "Mixes technology with creativity and business. Includes animation, film and photography, not just programming." },
      shsm: { es: "SHSM en ICT", en: "SHSM in ICT" },
      langs: { es: "Business, ICT, Media, producción digital y Co-op", en: "Business, ICT, Media, digital production and Co-op" },
      entry: { es: "Se pide transferencia a través de la escuela", en: "Transfer requested through the school" },
    },
    tags: "business negocios ict media digital animation film photography co-op",
  },
  {
    id: "sfx", mono: "SFX", cls: "sfx", name: "St. Francis Xavier", addr: "Mississauga East",
    system: "dpcdsb", start: "9", entry: "apply",
    fraser: { score: 8.0, rank: 86, prev: 8.0 },
    chips: [
      { t: { es: "Transferencia (fuera de boundary)", en: "Transfer (outside boundary)" }, k: "apply" },
      { t: { es: "Sede de IB", en: "IB host" }, k: "warm" },
    ],
    focus: { es: "ruta académica alternativa con International Baccalaureate y una oferta amplia.", en: "an alternative academic pathway with the International Baccalaureate and a broad offering." },
    kv: {
      distinct: { es: "IB Diploma Programme: programa integrado y estructurado, distinto de la secundaria regular", en: "IB Diploma Programme: an integrated, structured program, different from regular high school" },
      shsm: { es: "Varios SHSM", en: "Several SHSMs" },
      langs: { es: "—", en: "—" },
      entry: { es: "Regular: transferencia. IB: solicitud, según el boundary regional de IB.", en: "Regular: transfer. IB: application, according to the regional IB boundary." },
    },
    tags: "ib international baccalaureate diploma shsm",
  },
];

// Programas regionales DPCDSB y Peel.
export const PROGRAMS = [
  { id: "ap", system: "dpcdsb", start: "9", entry: "apply", name: "Advanced Placement (AP)", host: "St. Joseph CSS",
    p: { es: "Cursos de nivel universitario dentro de la secundaria. No es «una escuela más difícil». Se elige materia por materia y los exámenes AP pueden dar crédito universitario.", en: "University-level courses inside high school. It is not “a harder school”. You choose subject by subject and AP exams can earn university credit." },
    chips: [{ t: { es: "Preparación desde Gr 9", en: "Preparation from Gr 9" }, k: "" }, { t: { es: "Solicitud", en: "Application" }, k: "apply" }] },
  { id: "ib", system: "dpcdsb", start: "11", entry: "apply", name: "International Baccalaureate (IB)", host: "Notre Dame, St. Francis Xavier, St. Paul",
    p: { es: "Diploma preuniversitario de dos años. El estudiante elige una materia de cada uno de seis grupos. Es un paquete integrado, no modular como AP.", en: "Two-year pre-university diploma. The student chooses one subject from each of six groups. It is an integrated package, not modular like AP." },
    chips: [{ t: { es: "Diploma en Gr 11–12", en: "Diploma in Gr 11–12" }, k: "" }, { t: { es: "Solicitud", en: "Application" }, k: "apply" }] },
  { id: "steam", system: "dpcdsb", start: "9", entry: "apply", name: "Regional STEAM", host: "St. Joan of Arc CSS",
    p: { es: "Ciencia, tecnología, ingeniería, artes y matemáticas. Aprendizaje por proyectos, design thinking y resolución de problemas. El board lo lista también como STEM.", en: "Science, technology, engineering, arts and math. Project-based learning, design thinking and problem solving. The board also lists it as STEM." },
    chips: [{ t: { es: "Desde Gr 9", en: "From Gr 9" }, k: "" }, { t: { es: "Solicitud", en: "Application" }, k: "apply" }] },
  { id: "arts", system: "dpcdsb", start: "9", entry: "apply", name: "Regional Arts", host: "Iona CSS",
    p: { es: "Danza, teatro, música instrumental y vocal, medios y artes visuales. Puede pedir audición o portafolio.", en: "Dance, drama, instrumental and vocal music, media and visual arts. May require an audition or portfolio." },
    chips: [{ t: { es: "Desde Gr 9", en: "From Gr 9" }, k: "" }, { t: { es: "Solicitud o audición", en: "Application or audition" }, k: "apply" }] },
  { id: "sports", system: "dpcdsb", start: "9", entry: "apply", name: "Regional Sports", host: "St. Martin CSS",
    p: { es: "Deporte, condición física, liderazgo y educación física. No es solo para atletas de élite. Puede conectar con un SHSM de Sports.", en: "Sport, fitness, leadership and physical education. Not only for elite athletes. Can connect to a Sports SHSM." },
    chips: [{ t: { es: "Desde Gr 9", en: "From Gr 9" }, k: "" }, { t: { es: "Solicitud", en: "Application" }, k: "apply" }] },
  { id: "bakery", system: "dpcdsb", start: "10", entry: "apply", name: "Bakery School", host: "Father Michael Goetz CSS",
    p: { es: "Ruta técnica dentro de una secundaria general. Cuatro cursos de panadería y experiencia real con Co-op u OYAP.", en: "A technical pathway inside a general high school. Four bakery courses and real experience through Co-op or OYAP." },
    chips: [{ t: { es: "Gr 10–12", en: "Gr 10–12" }, k: "" }, { t: { es: "Solicitud", en: "Application" }, k: "apply" }] },

  { id: "p-ib", system: "peel", start: "11", entry: "apply", name: "IB",
    p: { es: "Diploma preuniversitario. Segunda puerta de entrada en Grade 11.", en: "Pre-university diploma. Second entry point in Grade 11." } },
  { id: "p-arts", system: "peel", start: "9", entry: "apply", name: "Arts",
    p: { es: "Programa artístico integrado. Segunda puerta de entrada en Grade 10.", en: "Integrated arts program. Second entry point in Grade 10." } },
  { id: "p-scitech", system: "peel", start: "9", entry: "apply", name: "SciTech",
    p: { es: "Matemáticas, ciencia y tecnología con aprendizaje práctico.", en: "Math, science and technology with hands-on learning." } },
  { id: "p-ap", system: "peel", start: "9", entry: "apply", name: "Advanced Placement (AP)",
    p: { es: "Cursos de nivel universitario en la secundaria.", en: "University-level courses in high school." } },
  { id: "p-ibt", system: "peel", start: "9", entry: "apply", name: "International Business & Technology (IBT)",
    p: { es: "Negocios y tecnología con mirada global y proyectos.", en: "Business and technology with a global outlook and projects." } },
  { id: "p-tet", system: "peel", start: "9", entry: "apply", name: "Transportation, Engineering & Technology",
    p: { es: "Ruta técnica hacia ingeniería y transporte.", en: "Technical pathway toward engineering and transportation." } },
  { id: "p-strings", system: "peel", start: "9", entry: "apply", name: "Strings",
    p: { es: "Programa de música de cuerdas.", en: "String music program." } },
  { id: "p-trades", system: "peel", start: "11", entry: "apply", name: "Regional Skilled Trades",
    p: { es: "Oficios especializados. Segunda puerta de entrada en Grade 11.", en: "Skilled trades. Second entry point in Grade 11." } },
];
