// All site content lives here, in Spanish (es), English (en) and Canadian French (fr).
// To update data (Fraser scores, dates, programs, schools) edit only this file.

import { EXTRAS } from "./school-extras.js";

const x = (es, en, fr) => ({ es, en, fr });

export const LANGS = ["es", "en", "fr"];

/* Signature line shown discreetly at the bottom of every page. */
const MADE_WITH = {
  en: "Made with love by a loving parent",
  es: "Hecho con amor por papá y mamá, que los adoran",
  fr: "Fait avec amour par un parent aimant",
};
export const madeWith = (lang) => `${MADE_WITH[lang] || MADE_WITH.en} ❤ <b>SBR · CBR</b>`;

export const FRASER = {
  report: x(
    "Informe Fraser 2025 (año escolar 2024-25)",
    "Fraser Institute 2025 Report Card (2024-25 school year)",
    "Bulletin 2025 de l'Institut Fraser (année scolaire 2024-2025)"
  ),
  url: "https://www.fraserinstitute.org/sites/default/files/2025-11/ontario-secondary-school-rankings-2025_0.pdf",
};

/* ------------------------------------------------------------------ */
/* Program types used as filter tags and chips                         */
/* ------------------------------------------------------------------ */
export const TAGS = {
  ib: x("IB", "IB", "BI"),
  ap: x("AP", "AP", "AP"),
  arts: x("Artes", "Arts", "Arts"),
  stem: x("STEM / SciTech", "STEM / SciTech", "STIM / SciTech"),
  sports: x("Deportes", "Sports", "Sports"),
  fi: x("French Immersion", "French Immersion", "Immersion française"),
  ef: x("Extended French", "Extended French", "Français prolongé"),
  bakery: x("Panadería", "Bakery", "Boulangerie"),
  trades: x("Oficios (Skilled Trades)", "Skilled Trades", "Métiers spécialisés"),
  ibt: x("IBT (negocios y tecnología)", "IBT (business & tech)", "IBT (affaires et technologie)"),
  strings: x("Cuerdas", "Strings", "Cordes"),
  alt: x("Programa alternativo", "Alternative program", "Programme alternatif"),
  shsm: x("SHSM", "SHSM", "MHS (SHSM)"),
};

export const BOARDS = {
  dpcdsb: x("DPCDSB (católico)", "DPCDSB (Catholic)", "DPCDSB (catholique)"),
  peel: x("Peel (público)", "Peel (public)", "Peel (public)"),
  fr: x("Católica en francés", "French-language Catholic", "Catholique de langue française"),
};

/* ------------------------------------------------------------------ */
/* UI strings                                                          */
/* ------------------------------------------------------------------ */
export const UI = {
  es: {
    htmlLang: "es",
    ogLocale: "es_CO",
    title: "Guía de secundarias en Mississauga | Highschool Navigator",
    metaDesc: "Directorio completo de secundarias católicas, públicas y de habla francesa en Mississauga (DPCDSB y Peel): IB, AP, artes, STEM, francés, oficios, fechas para aplicar y nota Fraser, con filtros y comparador.",
    skip: "Saltar al contenido",
    eyebrow: "Mississauga · Para entrar a Grade 9 en septiembre de 2027",
    h1: "Guía de secundarias en Mississauga",
    h1a: "Guía de secundarias",
    h1b: "en Mississauga",
    vibesLabel: "Explora según lo que te interesa:",
    statSchools: "escuelas", statBoards: "sistemas", statPrograms: "programas",
    tone: { label: "Tono", teen: "Teen", family: "Familia" },
    bnav: { escuelas: "Escuelas", regionales: "Programas", quiz: "Descúbrete", fechas: "Fechas" },
    privacy: "Privacidad",
    sticker: "6-7 😏",
    lead: "Todas las secundarias públicas, católicas y de habla francesa de Mississauga, con sus programas especiales (IB, AP, artes, STEM, francés y más), cómo se entra y cuándo hay que aplicar. Una guía para que toda la familia hable con la misma información.",
    factBoards: "Sistemas escolares:",
    factBoardsV: "DPCDSB (católico), Peel (público) y una escuela en francés",
    factSchools: "Escuelas:",
    factSchoolsN: (n) => `${n} secundarias de Mississauga`,
    notice: "<b>Esta guía muestra lo que ofrece cada escuela; no recomienda ninguna.</b> Incluye la nota pública del Fraser Institute como referencia de cómo se ve cada escuela en resultados académicos. No mide los programas, el ambiente ni si la escuela es adecuada para cada estudiante.",
    scope: "Alcance: secundarias públicas y católicas de Mississauga, más una escuela en francés. No incluye escuelas privadas ni independientes (por ejemplo Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). Los programas de cada escuela son los regionales confirmados en fuentes oficiales. Otras opciones, como los SHSM (especializaciones) y el Co-op (prácticas laborales con crédito), pueden variar: confírmalas con la escuela.",
    crs: {
      extraH: "También en esta escuela", shsmL: "SHSM", otherL: "Otros programas", siteL: "Sitio de la escuela", calL: "Calendario de cursos oficial",
      h: "Cursos que ofrece",
      intro: (y) => `Cursos del calendario oficial de la escuela (${y}). Que un curso aparezca no garantiza que se dicte todos los años: confírmalo con la escuela. Los nombres se muestran como los publica la escuela (en inglés).`,
      show: "Ver los cursos", hide: "Ocultar los cursos", loading: "Cargando…", course: "Curso",
      peelNote: "Las escuelas de Peel publican sus cursos en su propia guía de selección; aún no están incluidos aquí.",
      finderH: "Buscador de cursos",
      finderP: "Escribe una materia o un código (por ejemplo Computer Science, Photography, ICS4U) para ver qué escuelas del DPCDSB la ofrecen y en qué grados.",
      finderPh: "Ej.: Computer Science, Photography, MHF4U…", finderNone: "No encontramos cursos con ese texto.", finderMin: "Escribe al menos 3 letras.",
      finderCount: (n) => `${n} curso${n === 1 ? "" : "s"}`,
      finderSrc: (y) => `Fuente: calendarios de cursos oficiales de 15 escuelas del DPCDSB (${y}). Peel todavía no está incluido.`,
      offeredIn: "Se ofrece en",
    },
    map: {
      nav: "Mapa", h: "Mapa de las escuelas",
      legendH: "Colores", legendToggle: "Toca para mostrar u ocultar", tilesFail: "Tu navegador bloqueó el mapa de calles (¿bloqueador de anuncios o escudo de privacidad?). Los puntos y la lista siguen funcionando; prueba pausar el bloqueador para este sitio.", legendNum: "El número de cada punto coincide con la lista", legendHome: "Mi casa",
      p: "Encuentra las escuelas cerca de ti. Toca una escuela de la lista o un punto del mapa para ver su tarjeta y abrir su perfil. Puedes marcar tu casa en el mapa para ver la distancia en línea recta.",
      aria: "Mapa interactivo de las secundarias de Mississauga",
      search: "Buscar una escuela…", listAria: "Lista de escuelas",
      count: (n) => `${n} escuela${n === 1 ? "" : "s"}`,
      gateH: "Mapa de calles interactivo",
      gateP: "Para mostrarlo, tu navegador pedirá las imágenes del mapa a los servidores de OpenStreetMap, que verán tu dirección IP. No se envía nada más. La lista de escuelas funciona igual sin el mapa.",
      load: "Cargar el mapa", remember: "Recordar mi elección en este dispositivo",
      home: "Marcar mi casa", homePick: "Toca el mapa para marcar tu casa", homeClear: "Quitar mi casa", locate: "Usar mi ubicación",
      homeNote: "La ubicación se queda en tu dispositivo y no se guarda.", geoErr: "No pudimos obtener tu ubicación.",
      dist: (km) => `≈ ${km} km en línea recta`, sortedByDist: "Ordenadas por distancia a tu casa",
      directions: "Cómo llegar", view: "Ver perfil", fit: "Ver todas", mine: "En mi lista",
      attrib: "© colaboradores de OpenStreetMap", none: "No hay escuelas con esos filtros.", myHome: "Mi casa",
    },
    list: {
      btn: "Mi lista", h: "Mi lista", local: "Se guarda solo en este dispositivo, sin cuenta.",
      add: "Guardar en mi lista", saved: "Guardado en mi lista",
      empty: "Toca ☆ en las escuelas y los programas para armar tu lista. Aquí verás tu plan con sus fechas.",
      schools: "Escuelas", programs: "Programas", planH: "Tu plan",
      noSessions: "Todavía no hay charlas con fecha para lo que guardaste.",
      icsAll: "Agregar todas las fechas al calendario", pdf: "Descargar mi lista (PDF)", copy: "Copiar como texto", copied: "Copiado", clear: "Vaciar la lista",
      applyPeel: "Peel (RLCP): aplicaciones del 3 al 24 de noviembre de 2026; primeras ofertas el 2 de febrero de 2027.",
      applyDp: "DPCDSB: las fechas de inscripción de los programas regionales se confirman en la charla de cada escuela.",
    },
    game: {
      h: "Descanso 🎮", p: "¿Ya viste muchas escuelas? Tómate un respiro y ayuda al 67 a saltar la tarea.",
      aria: "Juego: el 67 salta obstáculos escolares y recoge íconos de programas",
      start: "Empezar", restart: "Reiniciar", again: "Jugar otra vez", ready: "Toca o pulsa espacio para empezar", over: "Game over",
      score: "Puntos", best: "Récord",
      hint: "Salta con la barra espaciadora, la flecha ↑ o tocando la pantalla. Recoge los íconos de programas para sumar puntos.",
      reduced: "Detectamos «reducir movimiento»: el juego va más lento.", sixtySeven: "¡67! 😏", paused: "Juego en pausa",
    },
    sess: {
      nav: "Charlas",
      h: "Calendario de charlas informativas",
      p: "Fechas y horarios de las charlas de otoño de 2026, escuela por escuela y programa por programa. Agrégalas a tu calendario y confirma siempre en el sitio de la escuela.",
      area: "Zona", board: "Sistema", all: "Todas", allBoards: "Todos",
      miss: "Mississauga", bramp: "Brampton", caledon: "Caledon y Bolton", virtual: "Virtual",
      tbc: "Fecha por confirmar", tba: "Hora por confirmar",
      kindSchool: "Charla de la escuela", kindProgram: "Charla del programa", kindGeneral: "Charla general",
      presented: "También se presentan:",
      register: "Inscribirme", join: "Unirme a la sesión",
      linkTbc: "El enlace de conexión lo publica el board o la escuela; revisa la fuente oficial o la página del programa.", info: "Más información", flyer: "Folleto", website: "Sitio de la escuela",
      cal: "Agregar al calendario", calNote: "Horas de Toronto (Este). La duración es aproximada.",
      none: "No hay charlas con esos filtros.",
      count: (n) => `${n} charla${n === 1 ? "" : "s"}`,
      source: "Fuentes: PDF oficial de charlas 2026 del DPCDSB y la página de RLCP de Peel. Los horarios pueden cambiar.",
      forSchool: "Charla informativa", forProgram: "Charlas de este programa",
      pd: { who: "Para quién es", reqs: "Requisitos", how: "Cómo se aplica", keyDates: "Fechas clave", sessions: "Charlas informativas", hosts: "Dónde se ofrece", links: "Información oficial", viewSchool: "Ver perfil de la escuela", details: "Ver detalles", tapHint: "Toca la tarjeta para ver más. Puedes seleccionar y copiar cualquier texto." },
    },
    detail: { close: "Cerrar", profile: "Ver perfil", fraserH: "Nota Fraser", fraserAcademic: "Es una medida solo académica.", reportLink: "Informe Fraser", programsH: "Programas y especializaciones", hostedH: "Programas que se ofrecen aquí", detailsH: "Sobre esta escuela", officialLink: "Sitio oficial del board", copy: "Copiar enlace", copied: "Enlace copiado", addCompare: "Agregar al comparador", inCompare: "En el comparador ✓", frenchNote: "Escuela de lengua francesa: para entrar hay que cumplir los requisitos de titular de derechos (sección 23)." },
    quiz: { h: "¿No sabes por dónde empezar?", p: "Responde un cuestionario anónimo de 3 minutos y recibe ideas de escuelas y programas para explorar, con un PDF de resultado. Es una orientación, no una asesoría profesional.", btn: "Hacer el cuestionario" },
    nav: { capas: "Cómo funciona el sistema", explorar: "Explorar y filtrar", escuelas: "Directorio", comparar: "Comparar", regionales: "Programas DPCDSB", peel: "Programas Peel", grados: "Desde qué grado", siglas: "Siglas", fechas: "Fechas", preguntas: "Preguntas" },
    navLabel: "Secciones",
    langLabel: "Idioma",
    themeLabel: "Cambiar tema",

    capasH: "Cómo funciona el sistema",
    capasP: "No todas las opciones son del mismo tipo. Hay cuatro niveles y algunos se pueden combinar.",
    layers: [
      { tag: "Nivel 1", h: "Escuela", p: "Donde vas a estudiar. Todas las escuelas ofrecen la secundaria regular completa, y cada una suma sus propios extras." },
      { tag: "Nivel 2", h: "Programa regional", p: "Un programa especial que funciona en algunas escuelas y recibe estudiantes de toda la zona. Casi siempre hay que aplicar, y el transporte puede correr por cuenta de la familia." },
      { tag: "Nivel 3", h: "Especialización", p: "Un camino dentro de la escuela, como un SHSM (especialización por sector) o el Co-op (prácticas laborales). Se hace sobre todo en Grade 11 y 12." },
      { tag: "Nivel 4", h: "Pathway", p: "A dónde te lleva todo esto: universidad, college, aprender un oficio (apprenticeship) o trabajo. Depende de las combinaciones que elijas." },
    ],

    exploreH: "Explorar y filtrar",
    exploreP: "Los filtros de sistema, tipo de programa y búsqueda afectan al directorio y a los programas. «Empieza en» y «Cómo se entra» solo afectan a las listas de programas.",
    searchLabel: "Buscar",
    searchPh: "Ej.: IB, panadería, arte, Port Credit…",
    fSystem: "Sistema", fTag: "Tipo de programa", fStart: "Empieza en (programas)", fEntry: "Cómo se entra (programas)", fSort: "Ordenar escuelas",
    all: "Todos",
    optSystem: { dpcdsb: "DPCDSB (católico)", peel: "Peel (público)", fr: "Francófona católica" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automática (según tu boundary)", apply: "Hay que aplicar o pedir traslado" },
    optSort: { name: "Nombre (A–Z)", fraser: "Nota Fraser (mayor a menor)" },
    reset: "Limpiar filtros",
    resultCount: (s, p) => `${s} escuela${s === 1 ? "" : "s"} · ${p} programa${p === 1 ? "" : "s"}`,
    noResults: "No hay resultados con esos filtros. Prueba quitándolos.",

    escuelasH: "Directorio de secundarias de Mississauga",
    escuelasP: "Todas las escuelas, con sus programas regionales y su nota Fraser. La nota es solo académica y la lista no se ordena por ella, a menos que tú lo pidas.",
    lblFocus: "Enfoque:",
    fraserLabel: "Nota Fraser",
    fraserOf: "/ 10",
    fraserRank: (r) => `Puesto ${r} en Ontario`,
    fraserPrev: (p) => `Año anterior: ${p}`,
    fraserNone: "Sin nota Fraser en el informe 2025",
    noPrograms: "No tiene un programa regional propio. Ofrece la secundaria regular; pregunta en la escuela por SHSM y Co-op.",
    moreInfo: "Más detalles",
    fraserFoot: "Fuente: ",
    fraserWhatH: "Qué mide (y qué no) la nota Fraser",
    fraserWhat: "Se calcula con resultados de pruebas provinciales: matemáticas de Grade 9 (Academic y Applied), la prueba de lectoescritura OSSLT, el porcentaje de pruebas por debajo del estándar y de pruebas que no se presentaron, y las diferencias entre géneros. No mide arte, deportes, programas técnicos, ambiente, apoyo ni idiomas. El contexto socioeconómico y el tamaño de la muestra influyen, y la nota cambia de un año a otro. Úsala como una referencia más, no como un veredicto.",
    compare: "Comparar",
    compareMax: "Máximo 4 escuelas",

    compararH: "Comparador de escuelas",
    compararP: "Elige hasta 4 escuelas, de cualquier sistema, para verlas lado a lado.",
    compAdd: "Agregar escuela…",
    compRemove: "Quitar",
    compRows: { board: "Sistema", fraser: "Nota Fraser (2024-25)", rank: "Puesto en Ontario", prev: "Nota del año anterior", addr: "Ubicación", programs: "Programas regionales", focus: "Enfoque", distinct: "Lo que la distingue", shsm: "Especializaciones (SHSM)", langs: "Idiomas y otros", entry: "Cómo se entra" },
    compEmpty: "Selecciona al menos dos escuelas para compararlas.",
    compCol: "Escuela",
    none: "—",

    regionalesH: "Programas regionales del DPCDSB",
    regionalesP: "Programas que reciben estudiantes de toda la zona. La escuela sede es donde se cursa el programa; las sedes en Mississauga aparecen marcadas.",
    peelH: "Programas regionales de Peel (RLCP)",
    peelP: "Los Regional Learning Choices Programs (RLCP) de Peel están abiertos a estudiantes que viven en Peel, incluso a quienes hoy están en el sistema católico. Se aplica según tu boundary (la zona que te corresponde por tu dirección). Vale la pena conocerlos antes de descartar nada.",
    host: "Sedes: ",
    inMiss: "Mississauga",
    secondEntry: "Segunda oportunidad de entrada: ",
    peelHowH: "Cómo funciona",
    peelHow: "Se entra en Grade 9 aplicando en línea. Hay una tarifa por aplicar y otra anual por programa. Se revisan las notas de Grade 7 y, en algunos programas, también una audición, una evaluación o una respuesta escrita. Después hay un sorteo entre quienes cumplen los criterios.",
    peelRuleH: "Reglas importantes",
    peelRule: "Tienes que aplicar al programa que te corresponde según tu boundary (tu dirección). Los estudiantes con visa de estudiante internacional no pueden aplicar; quienes tienen permiso de trabajo o de estudio, sí.",
    startsAt: { "9": "Desde Gr 9", "10": "Desde Gr 10", "11": "Desde Gr 11" },
    applyChip: "Aplicar",

    gradosH: "¿Desde qué grado empieza cada cosa?",
    gradosP: "Varias opciones no aparecen hasta Grade 10 u 11. Por eso conviene ver todo el recorrido antes de decidir para Grade 9.",
    tlOption: "Opción",
    tlConfirmed: "Confirmado",
    tlSoft: "Preparación o rango habitual; confírmalo con cada escuela",
    timeline: [
      { label: "Secundaria regular", sub: "Cualquier escuela", from: 1, to: 5, txt: "Cursos regulares", soft: false },
      { label: "AP", sub: "Por materia", segs: [[1, 3, "Preparación", true], [3, 5, "Cursos y exámenes AP", false]] },
      { label: "IB", sub: "Diploma de dos años", segs: [[1, 3, "Secuencia previa (MYP o Pre-IB)", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Programas regionales", from: 1, to: 5, txt: "Desde Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grade 10 a 12", soft: false },
      { label: "SHSM", sub: "Especialización", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Experiencia laboral con crédito", from: 3, to: 5, txt: "Últimos años", soft: false },
      { label: "OYAP y Dual Credit", sub: "Oficios y college", from: 3, to: 5, txt: "Normalmente 11–12", soft: true },
    ],

    siglasH: "Glosario en una línea",
    glossary: [
      ["AP", "Cursos de nivel universitario, materia por materia.", "Modular y flexible."],
      ["IB", "Diploma completo y estructurado de dos años.", "Todo el paquete, no materias sueltas."],
      ["MYP / Pre-IB", "Caminos previos al Diploma IB en Peel: MYP (en Glenforest) y Pre-IB (en Erindale).", ""],
      ["SHSM", "Specialist High Skills Major: una especialización por sector (tecnología, negocios, hospitalidad, transporte, artes y otros) con cursos, certificaciones y prácticas laborales (Co-op).", "Se cursa en Gr 11–12."],
      ["Co-op", "Estudiar y trabajar en una empresa de verdad, y recibir créditos por ello.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: empezar el aprendizaje de un oficio mientras terminas la secundaria.", ""],
      ["Dual Credit", "Cursos de college que también cuentan para el diploma de secundaria.", ""],
      ["RLCP", "Regional Learning Choices Programs: los programas regionales de Peel.", ""],
      ["Feeder", "La secundaria que le corresponde, por defecto, a los estudiantes de una escuela primaria.", ""],
      ["Boundary", "La zona según tu dirección, que decide a qué escuela vas sin tener que aplicar.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: prueba provincial de lectura y escritura. Es parte de la base de la nota Fraser.", ""],
    ],

    fechasH: "Fechas para tu calendario",
    fechasP: "Estas son las fechas que ya se conocen. Confírmalas siempre en el sitio del board o de cada escuela.",
    dates: [
      { when: "8 oct – 26 nov 2026", b: "Charlas del DPCDSB", p: "escuela por escuela (mira el calendario más abajo)." },
      { when: "6 oct 2026", b: "Noche virtual de Peel", p: "para familias de estudiantes afrodescendientes (de 6:00 a 7:00 p. m.), sobre los RLCP, Explore High Skills y Skilled Trades." },
      { when: "21 oct – 5 nov 2026", b: "Charlas de los programas RLCP de Peel", p: "una por programa: IB 21 oct; AP, SciTech y Strings 22 oct; Arts 27 oct; IBT 28 oct; Skilled Trades 29 oct; Transportation 5 nov." },
      { when: "3–24 nov 2026", b: "Aplicaciones a los RLCP de Peel", p: "para el año escolar 2027-28. Primeras ofertas: 2 de febrero de 2027." },
      { when: "5 dic 2026 – 28 ene 2027", b: "Evaluaciones y audiciones de Peel", p: "AP y Strings 5 dic; IB 12 dic; Arts y Skilled Trades 27–28 ene (la hora la define cada escuela)." },
      { when: "8 ene 2027", b: "Bakery School (Goetz)", p: "fecha límite de la primera ronda de aplicaciones para entrar en septiembre de 2027." },
      { when: "Por confirmar", b: "Aplicaciones a los programas regionales del DPCDSB", p: "(AP, IB, artes, deportes, STEM, panadería). Se confirman en cada charla; según el board, la aplicación a STEAM en St. Joan of Arc abre en octubre." },
    ],

    preguntasH: "Preguntas para llevar a las charlas",
    preguntasP: "Para escuchar con ojo crítico, y no solo la presentación de cada escuela.",
    questions: [
      "¿Qué tiene esta escuela que no tenga la de al lado?",
      "¿Qué programas piden aplicar, y hasta cuándo?",
      "¿Qué se puede empezar en Grade 9 y qué solo en Grade 11–12?",
      "¿Qué notas o requisitos piden? ¿Hay audición o portafolio?",
      "¿Hay transporte o lo cubre la familia? ¿Qué costos adicionales hay?",
      "¿Qué certificaciones se pueden obtener y qué opciones de Co-op hay?",
      "¿Con qué universidades, colleges o empresas trabajan?",
      "¿Se pueden combinar programas, por ejemplo IB con Co-op?",
    ],

    pendingH: "Lo que falta por confirmar",
    pendingP: "Datos que no pudimos verificar y que conviene revisar en las charlas o en el sitio de cada escuela.",
    pending: [
      "Direcciones exactas de varias escuelas y la distancia desde tu casa",
      "Lista completa de SHSM por escuela (el DPCDSB publica una matriz 2026-27 con 57 programas)",
      "Costos, transporte y fechas de aplicación de los programas regionales del DPCDSB",
      "Requisitos académicos y audiciones de Arts, Sports y STEM",
      "Las escuelas de Peel sin RLCP también ofrecen Co-op, SHSM y Explore High Skills; confírmalo en el sitio de cada una",
      "La nota Fraser se actualiza cada otoño: revisa siempre el informe más reciente",
    ],
    sourcesH: "Fuentes consultadas",
    disclaimer: "Sitio informativo independiente, sin relación con el DPCDSB, Peel ni el Fraser Institute. La información puede cambiar: verifícala siempre en las fuentes oficiales.",
    backTop: "Volver arriba",
  },

  en: {
    htmlLang: "en",
    ogLocale: "en_CA",
    title: "Mississauga High School Guide | Highschool Navigator",
    metaDesc: "Complete directory of Catholic, public and French-language high schools in Mississauga (DPCDSB and Peel): IB, AP, Arts, STEM, French, trades, application dates and Fraser scores, with filters and a comparison tool.",
    skip: "Skip to content",
    eyebrow: "Mississauga · Grade 9 entry, September 2027",
    h1: "Mississauga High School Guide",
    h1a: "Mississauga",
    h1b: "High School Guide",
    vibesLabel: "Explore by interest:",
    statSchools: "schools", statBoards: "boards", statPrograms: "programs",
    tone: { label: "Tone", teen: "Teen", family: "Family" },
    bnav: { escuelas: "Schools", regionales: "Programs", quiz: "Find your fit", fechas: "Dates" },
    privacy: "Privacy",
    sticker: "6-7 😏",
    lead: "Every public, Catholic and French-language high school in Mississauga, with its special programs (IB, AP, Arts, STEM, French and more), how to get in and when to apply. A guide so the family can talk with the same information.",
    factBoards: "Boards:",
    factBoardsV: "DPCDSB (Catholic), Peel (public) and a French-language school",
    factSchools: "Schools:",
    factSchoolsN: (n) => `${n} high schools in Mississauga`,
    notice: "<b>This guide describes what is offered; it does not recommend any school.</b> It includes the Fraser Institute's public score as a reference for how each school is perceived on academic results. It does not measure programs, atmosphere or fit for each student.",
    scope: "Scope: public and Catholic high schools in Mississauga, plus one French-language school. Private and independent schools are excluded (for example Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). The programs listed per school are the regional programs confirmed in official sources; SHSM, Co-op and others may vary, so confirm them with the school.",
    crs: {
      extraH: "Also at this school", shsmL: "SHSM", otherL: "Other programs", siteL: "School website", calL: "Official course calendar",
      h: "Courses offered",
      intro: (y) => `Courses in the school's official course calendar (${y}). A listed course is not a guarantee that it runs every year: confirm with the school. Names are shown as the school publishes them.`,
      show: "Show the courses", hide: "Hide the courses", loading: "Loading…", course: "Course",
      peelNote: "Peel schools publish their courses in their own course selection guides; they are not included here yet.",
      finderH: "Course finder",
      finderP: "Type a subject or a course code (for example Computer Science, Photography, ICS4U) to see which DPCDSB schools offer it and in which grades.",
      finderPh: "E.g. Computer Science, Photography, MHF4U…", finderNone: "No courses match that text.", finderMin: "Type at least 3 letters.",
      finderCount: (n) => `${n} course${n === 1 ? "" : "s"}`,
      finderSrc: (y) => `Source: official course calendars of 15 DPCDSB schools (${y}). Peel is not included yet.`,
      offeredIn: "Offered at",
    },
    map: {
      nav: "Map", h: "School map",
      legendH: "Colors", legendToggle: "Tap to show or hide", tilesFail: "Your browser blocked the street map (ad blocker or privacy shield?). The pins and the list still work; try pausing the blocker for this site.", legendNum: "The number on each pin matches the list", legendHome: "My home",
      p: "Find schools near you. Tap a school in the list or a point on the map to see its card and open its profile. You can mark your home on the map to see the straight-line distance.",
      aria: "Interactive map of Mississauga high schools",
      search: "Search for a school…", listAria: "List of schools",
      count: (n) => `${n} school${n === 1 ? "" : "s"}`,
      gateH: "Interactive street map",
      gateP: "To show it, your browser will request the map images from OpenStreetMap's servers, which will see your IP address. Nothing else is sent. The school list works the same without the map.",
      load: "Load the map", remember: "Remember my choice on this device",
      home: "Mark my home", homePick: "Tap the map to mark your home", homeClear: "Remove my home", locate: "Use my location",
      homeNote: "Your location stays on your device and is not saved.", geoErr: "We could not get your location.",
      dist: (km) => `≈ ${km} km straight line`, sortedByDist: "Sorted by distance from your home",
      directions: "Directions", view: "View profile", fit: "Show all", mine: "In my list",
      attrib: "© OpenStreetMap contributors", none: "No schools match these filters.", myHome: "My home",
    },
    list: {
      btn: "My list", h: "My list", local: "Saved only on this device, no account.",
      add: "Save to my list", saved: "Saved to my list",
      empty: "Tap ☆ on schools and programs to build your list. You will see your plan with its dates here.",
      schools: "Schools", programs: "Programs", planH: "Your plan",
      noSessions: "No dated sessions yet for what you saved.",
      icsAll: "Add all dates to calendar", pdf: "Download my list (PDF)", copy: "Copy as text", copied: "Copied", clear: "Clear list",
      applyPeel: "Peel (RLCP): applications Nov 3–24, 2026; first offers Feb 2, 2027.",
      applyDp: "DPCDSB: registration dates for regional programs are confirmed at each school's session.",
    },
    game: {
      h: "Take a break 🎮", p: "Seen a lot of schools? Take a breather and help the 67 jump over homework.",
      aria: "Game: the 67 jumps over school obstacles and collects program icons",
      start: "Start", restart: "Restart", again: "Play again", ready: "Tap or press space to start", over: "Game over",
      score: "Score", best: "Best",
      hint: "Jump with the space bar, the ↑ key or by tapping the screen. Collect program icons for extra points.",
      reduced: "We detected “reduce motion”: the game runs slower.", sixtySeven: "67! 😏", paused: "Game paused",
    },
    sess: {
      nav: "Sessions",
      h: "Information session calendar",
      p: "Dates and times of the fall 2026 information sessions, school by school and program by program. Add them to your calendar and always confirm on the school's website.",
      area: "Area", board: "Board", all: "All", allBoards: "All",
      miss: "Mississauga", bramp: "Brampton", caledon: "Caledon & Bolton", virtual: "Virtual",
      tbc: "Date to be confirmed", tba: "Time to be confirmed",
      kindSchool: "School session", kindProgram: "Program session", kindGeneral: "General session",
      presented: "Also presented:",
      register: "Register", join: "Join the session",
      linkTbc: "The connection link is published by the board or the school; check the official source or the program page.", info: "More info", flyer: "Flyer", website: "School website",
      cal: "Add to calendar", calNote: "Eastern time (Toronto). Duration is approximate.",
      none: "No sessions match these filters.",
      count: (n) => `${n} session${n === 1 ? "" : "s"}`,
      source: "Sources: DPCDSB's official 2026 sessions PDF and Peel's RLCP page. Times may change.",
      forSchool: "Information session", forProgram: "Sessions for this program",
      pd: { who: "Who it is for", reqs: "Requirements", how: "How to apply", keyDates: "Key dates", sessions: "Information sessions", hosts: "Where it is offered", links: "Official information", viewSchool: "View school profile", details: "View details", tapHint: "Tap the card for more. You can select and copy any text." },
    },
    detail: { close: "Close", profile: "View profile", fraserH: "Fraser score", fraserAcademic: "An academic-only measure.", reportLink: "Fraser report", programsH: "Programs and specializations", hostedH: "Programs taken here", detailsH: "About this school", officialLink: "Official board website", copy: "Copy link", copied: "Link copied", addCompare: "Add to comparison", inCompare: "In comparison ✓", frenchNote: "French-language school: entry requires rights-holder eligibility (section 23)." },
    quiz: { h: "Not sure where to start?", p: "Take an anonymous 3-minute questionnaire and get ideas for schools and programs to explore, with a PDF result. It is guidance, not counselling.", btn: "Take the questionnaire" },
    nav: { capas: "How to read the map", explorar: "Explore & filter", escuelas: "Directory", comparar: "Compare", regionales: "DPCDSB programs", peel: "Peel programs", grados: "Which grade", siglas: "Glossary", fechas: "Dates", preguntas: "Questions" },
    navLabel: "Sections",
    langLabel: "Language",
    themeLabel: "Toggle theme",

    capasH: "How to read the map",
    capasP: "The options are not equivalent. There are four different levels and some can be combined.",
    layers: [
      { tag: "Level 1", h: "School", p: "The building where you study. Every school offers the full regular high school program, plus some extras of its own." },
      { tag: "Level 2", h: "Regional program", p: "A special program housed in certain schools that takes students from the whole area. It almost always requires an application, and transportation may be the family's responsibility." },
      { tag: "Level 3", h: "Specialization", p: "A pathway inside a school, such as SHSM or Co-op. Mostly taken in Grades 11 and 12." },
      { tag: "Level 4", h: "Pathway", p: "Where it all leads: university, college, apprenticeship or work. It depends on the combinations chosen." },
    ],

    exploreH: "Explore & filter",
    exploreP: "The board, program type and search filters affect the directory and the programs. “Starts in” and “How to get in” only affect the program lists.",
    searchLabel: "Search",
    searchPh: "E.g. IB, bakery, arts, Port Credit…",
    fSystem: "Board", fTag: "Program type", fStart: "Starts in (programs)", fEntry: "How to get in (programs)", fSort: "Sort schools",
    all: "All",
    optSystem: { dpcdsb: "DPCDSB (Catholic)", peel: "Peel (public)", fr: "French-language Catholic" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automatic (boundary)", apply: "Application or transfer required" },
    optSort: { name: "Name (A–Z)", fraser: "Fraser score (high to low)" },
    reset: "Clear filters",
    resultCount: (s, p) => `${s} school${s === 1 ? "" : "s"} · ${p} program${p === 1 ? "" : "s"}`,
    noResults: "No results for those filters. Try clearing them.",

    escuelasH: "Directory of Mississauga high schools",
    escuelasP: "Every school, with its regional programs and Fraser score. The score is academic only and does not order the list unless you choose to sort by it.",
    lblFocus: "Focus:",
    fraserLabel: "Fraser score",
    fraserOf: "/ 10",
    fraserRank: (r) => `Rank ${r} in Ontario`,
    fraserPrev: (p) => `Previous year: ${p}`,
    fraserNone: "No Fraser score in the 2025 report",
    noPrograms: "No regional program of its own. Offers the regular high school; confirm SHSM and Co-op with the school.",
    moreInfo: "More details",
    fraserFoot: "Source: ",
    fraserWhatH: "What the Fraser score measures (and what it does not)",
    fraserWhat: "It is calculated from provincial test results: Grade 9 math (Academic and Applied), the Ontario Secondary School Literacy Test (OSSLT), the share of tests below standard and of tests not written, and gender gaps. It does not measure arts, sports, technical programs, atmosphere, support or languages. Socioeconomic context and sample size matter, and scores change from year to year. Use it as one reference, not a verdict.",
    compare: "Compare",
    compareMax: "Maximum 4 schools",

    compararH: "School comparison",
    compararP: "Pick up to 4 schools from any board to see them side by side.",
    compAdd: "Add a school…",
    compRemove: "Remove",
    compRows: { board: "Board", fraser: "Fraser score (2024-25)", rank: "Rank in Ontario", prev: "Previous year score", addr: "Location", programs: "Regional programs", focus: "Focus", distinct: "What stands out", shsm: "Specializations (SHSM)", langs: "Languages and other", entry: "How to get in" },
    compEmpty: "Select at least two schools to compare them.",
    compCol: "School",
    none: "—",

    regionalesH: "DPCDSB regional programs",
    regionalesP: "Programs that take students from the whole area. The host school is where the program is taken; Mississauga hosts are marked.",
    peelH: "Peel regional programs (RLCP)",
    peelP: "Peel's Regional Learning Choices Programs (RLCP) are open to students who live in Peel, including those currently in the Catholic system. You apply according to your home boundary, and it is worth knowing them before ruling anything out.",
    host: "Hosts: ",
    inMiss: "Mississauga",
    secondEntry: "Second entry: ",
    peelHowH: "How it works",
    peelHow: "Grade 9 entry by online application. There is an application fee and an annual per-program fee. Grade 7 marks are reviewed and, for some programs, an audition, assessment or written response. Then a random selection is held among applicants who meet the criteria.",
    peelRuleH: "Important rules",
    peelRule: "You must apply to the program that matches your boundary by home address. Students on an international student visa are not eligible (those with work or study permits may apply).",
    startsAt: { "9": "From Gr 9", "10": "From Gr 10", "11": "From Gr 11" },
    applyChip: "Application",

    gradosH: "From which grade does each thing start?",
    gradosP: "Several options do not appear until Grade 10 or 11. That is why it helps to see the whole path before deciding on Grade 9.",
    tlOption: "Option",
    tlConfirmed: "Confirmed",
    tlSoft: "Preparation or typical range, to be confirmed with each school",
    timeline: [
      { label: "Regular high school", sub: "Any school", from: 1, to: 5, txt: "Regular courses", soft: false },
      { label: "AP", sub: "Subject by subject", segs: [[1, 3, "Preparation", true], [3, 5, "AP courses and exams", false]] },
      { label: "IB", sub: "Two-year diploma", segs: [[1, 3, "Prior sequence (MYP or Pre-IB)", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Regional programs", from: 1, to: 5, txt: "From Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grades 10 to 12", soft: false },
      { label: "SHSM", sub: "Specialization", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Work experience for credit", from: 3, to: 5, txt: "Senior grades", soft: false },
      { label: "OYAP & Dual Credit", sub: "Trades and college", from: 3, to: 5, txt: "Usually 11–12", soft: true },
    ],

    siglasH: "Acronyms in one line",
    glossary: [
      ["AP", "University-level courses, subject by subject.", "Modular and flexible."],
      ["IB", "A complete, structured two-year diploma.", "The whole package, not single subjects."],
      ["MYP / Pre-IB", "Sequences leading to the IB Diploma in Peel: MYP (Glenforest) and Pre-IB (Erindale).", ""],
      ["SHSM", "Specialist High Skills Major: a sector specialization (ICT, Business, Hospitality, Transportation, Arts and others) with courses, certifications and Co-op.", "Taken in Gr 11–12."],
      ["Co-op", "Study and work at a real company, and earn credits for it.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: start a trade apprenticeship while finishing high school.", ""],
      ["Dual Credit", "College courses that also count toward the high school diploma.", ""],
      ["RLCP", "Regional Learning Choices Programs: Peel's regional programs.", ""],
      ["Feeder", "The high school that is the default for a given elementary school.", ""],
      ["Boundary", "The residence area that decides which school you attend without applying.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: the provincial literacy test, part of the basis of the Fraser score.", ""],
    ],

    fechasH: "Dates for your calendar",
    fechasP: "These are the dates already known. Always confirm them on each board's or school's website.",
    dates: [
      { when: "Oct 8 – Nov 26, 2026", b: "DPCDSB information sessions", p: "school by school (see the calendar below)." },
      { when: "Oct 6, 2026", b: "Peel virtual information night", p: "for families of African, Black and Afro-Caribbean students (6–7 p.m.), on RLCP, Explore High Skills and Skilled Trades." },
      { when: "Oct 21 – Nov 5, 2026", b: "Peel RLCP program information nights", p: "one per program: IB Oct 21; AP, SciTech and Strings Oct 22; Arts Oct 27; IBT Oct 28; Skilled Trades Oct 29; Transportation Nov 5." },
      { when: "Nov 3–24, 2026", b: "Peel RLCP applications", p: "for the 2027-28 school year. First offers: February 2, 2027." },
      { when: "Dec 5, 2026 – Jan 28, 2027", b: "Peel assessments and auditions", p: "AP and Strings Dec 5; IB Dec 12; Arts and Skilled Trades Jan 27–28 (time set by each school)." },
      { when: "Jan 8, 2027", b: "Bakery School (Goetz)", p: "first-round application deadline to start in September 2027." },
      { when: "To be confirmed", b: "DPCDSB regional program applications", p: "(AP, IB, Arts, Sports, STEM, Bakery). Confirmed at each talk; St. Joan of Arc STEAM opens in October, per the board." },
    ],

    preguntasH: "Questions to bring to the info sessions",
    preguntasP: "To listen critically and not just to each school's presentation.",
    questions: [
      "What does this school have that the one next door doesn't?",
      "Which programs require an application, and by when?",
      "What can be taken from Grade 9 and what only in Grades 11–12?",
      "What grades or requirements are needed, and is there an audition or portfolio?",
      "Is there transportation, or does the family cover it? What extra costs are there?",
      "What certifications can be earned and what Co-op exists?",
      "Which universities, colleges or industries do they work with?",
      "Can programs be combined, for example IB with Co-op?",
    ],

    pendingH: "What is still to be confirmed",
    pendingP: "Data that could not be verified and that is worth checking at each info session or school website.",
    pending: [
      "Exact addresses of several schools and the distance from home",
      "Each school's complete SHSM list (DPCDSB publishes a 2026-27 matrix of 57 programs)",
      "Costs, transportation and application dates for DPCDSB regional programs",
      "Academic requirements and auditions for Arts, Sports and STEM",
      "Peel schools without an RLCP also offer Co-op, SHSM and Explore High Skills; verify on each website",
      "Fraser scores are updated every autumn: check the latest report",
    ],
    sourcesH: "Sources consulted",
    disclaimer: "Independent informational site, not affiliated with DPCDSB, Peel or the Fraser Institute. Information may change: always verify with official sources.",
    backTop: "Back to top",
  },

  fr: {
    htmlLang: "fr-CA",
    ogLocale: "fr_CA",
    title: "Guide des écoles secondaires de Mississauga | Highschool Navigator",
    metaDesc: "Répertoire complet des écoles secondaires catholiques, publiques et de langue française de Mississauga (DPCDSB et Peel) : BI, AP, arts, STIM, français, métiers, dates d'inscription et cote Fraser, avec filtres et comparateur.",
    skip: "Passer au contenu",
    eyebrow: "Mississauga · Entrée en 9e année, septembre 2027",
    h1: "Guide des écoles secondaires de Mississauga",
    h1a: "Guide des écoles secondaires",
    h1b: "de Mississauga",
    vibesLabel: "Explore selon tes intérêts :",
    statSchools: "écoles", statBoards: "conseils", statPrograms: "programmes",
    tone: { label: "Ton", teen: "Ado", family: "Famille" },
    bnav: { escuelas: "Écoles", regionales: "Programmes", quiz: "Trouve ta place", fechas: "Dates" },
    privacy: "Confidentialité",
    sticker: "6-7 😏",
    lead: "Toutes les écoles secondaires publiques, catholiques et de langue française de Mississauga, avec leurs programmes spéciaux (BI, AP, arts, STIM, français et plus), la façon d'y entrer et le moment de présenter une demande. Un guide pour en discuter en famille avec la même information.",
    factBoards: "Conseils scolaires :",
    factBoardsV: "DPCDSB (catholique), Peel (public) et une école de langue française",
    factSchools: "Écoles :",
    factSchoolsN: (n) => `${n} écoles secondaires à Mississauga`,
    notice: "<b>Ce guide décrit l'offre; il ne recommande aucune école.</b> Il inclut la cote publique de l'Institut Fraser comme repère de la perception de chaque école sur les résultats scolaires. Elle ne mesure ni les programmes, ni le climat, ni l'adéquation à chaque élève.",
    scope: "Portée : écoles secondaires publiques et catholiques de Mississauga, plus une école de langue française. Les écoles privées et indépendantes sont exclues (par exemple Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). Les programmes indiqués pour chaque école sont les programmes régionaux confirmés dans les sources officielles; les MHS (SHSM), l'éducation coopérative et autres peuvent varier : confirmez-les auprès de l'école.",
    crs: {
      extraH: "Aussi à cette école", shsmL: "MHS (SHSM)", otherL: "Autres programmes", siteL: "Site de l'école", calL: "Calendrier des cours officiel",
      h: "Cours offerts",
      intro: (y) => `Cours du calendrier officiel de l'école (${y}). La présence d'un cours ne garantit pas qu'il soit offert chaque année : confirme auprès de l'école. Les noms sont affichés tels que l'école les publie (en anglais).`,
      show: "Voir les cours", hide: "Masquer les cours", loading: "Chargement…", course: "Cours",
      peelNote: "Les écoles de Peel publient leurs cours dans leur propre guide de sélection; ils ne sont pas encore inclus ici.",
      finderH: "Recherche de cours",
      finderP: "Saisis une matière ou un code (par exemple Computer Science, Photography, ICS4U) pour voir quelles écoles du DPCDSB l'offrent et en quelles années.",
      finderPh: "Ex. : Computer Science, Photography, MHF4U…", finderNone: "Aucun cours ne correspond.", finderMin: "Saisis au moins 3 lettres.",
      finderCount: (n) => `${n} cours`,
      finderSrc: (y) => `Source : calendriers de cours officiels de 15 écoles du DPCDSB (${y}). Peel n'est pas encore inclus.`,
      offeredIn: "Offert à",
    },
    map: {
      nav: "Carte", h: "Carte des écoles",
      legendH: "Couleurs", legendToggle: "Touche pour afficher ou masquer", tilesFail: "Ton navigateur a bloqué la carte routière (bloqueur de pub ou bouclier de confidentialité?). Les repères et la liste fonctionnent toujours; essaie de mettre le bloqueur en pause pour ce site.", legendNum: "Le numéro de chaque point correspond à la liste", legendHome: "Ma maison",
      p: "Trouve les écoles près de chez toi. Touche une école dans la liste ou un point sur la carte pour voir sa fiche et ouvrir son profil. Tu peux marquer ta maison sur la carte pour voir la distance en ligne droite.",
      aria: "Carte interactive des écoles secondaires de Mississauga",
      search: "Chercher une école…", listAria: "Liste des écoles",
      count: (n) => `${n} école${n === 1 ? "" : "s"}`,
      gateH: "Carte routière interactive",
      gateP: "Pour l'afficher, ton navigateur demandera les images de la carte aux serveurs d'OpenStreetMap, qui verront ton adresse IP. Rien d'autre n'est envoyé. La liste des écoles fonctionne aussi sans la carte.",
      load: "Charger la carte", remember: "Se souvenir de mon choix sur cet appareil",
      home: "Marquer ma maison", homePick: "Touche la carte pour marquer ta maison", homeClear: "Retirer ma maison", locate: "Utiliser ma position",
      homeNote: "Ta position reste sur ton appareil et n'est pas enregistrée.", geoErr: "Impossible d'obtenir ta position.",
      dist: (km) => `≈ ${km} km en ligne droite`, sortedByDist: "Triées par distance depuis ta maison",
      directions: "Itinéraire", view: "Voir le profil", fit: "Tout voir", mine: "Dans ma liste",
      attrib: "© contributeurs d'OpenStreetMap", none: "Aucune école avec ces filtres.", myHome: "Ma maison",
    },
    list: {
      btn: "Ma liste", h: "Ma liste", local: "Conservée seulement sur cet appareil, sans compte.",
      add: "Ajouter à ma liste", saved: "Dans ma liste",
      empty: "Touche ☆ sur les écoles et les programmes pour créer ta liste. Tu verras ici ton plan avec ses dates.",
      schools: "Écoles", programs: "Programmes", planH: "Ton plan",
      noSessions: "Aucune séance datée pour l'instant pour ce que tu as enregistré.",
      icsAll: "Ajouter toutes les dates au calendrier", pdf: "Télécharger ma liste (PDF)", copy: "Copier en texte", copied: "Copié", clear: "Vider la liste",
      applyPeel: "Peel (RLCP) : demandes du 3 au 24 novembre 2026; premières offres le 2 février 2027.",
      applyDp: "DPCDSB : les dates d'inscription aux programmes régionaux sont confirmées à la séance de chaque école.",
    },
    game: {
      h: "Pause 🎮", p: "Tu as vu beaucoup d'écoles? Prends une pause et aide le 67 à sauter par-dessus les devoirs.",
      aria: "Jeu : le 67 saute des obstacles scolaires et ramasse des icônes de programmes",
      start: "Commencer", restart: "Recommencer", again: "Rejouer", ready: "Touche ou appuie sur espace pour commencer", over: "Partie terminée",
      score: "Points", best: "Record",
      hint: "Saute avec la barre d'espace, la flèche ↑ ou en touchant l'écran. Ramasse les icônes de programmes pour gagner des points.",
      reduced: "« Réduire les animations » détecté : le jeu va plus lentement.", sixtySeven: "67! 😏", paused: "Jeu en pause",
    },
    sess: {
      nav: "Séances",
      h: "Calendrier des séances d'information",
      p: "Dates et heures des séances d'information de l'automne 2026, école par école et programme par programme. Ajoute-les à ton calendrier et confirme toujours sur le site de l'école.",
      area: "Secteur", board: "Conseil", all: "Tous", allBoards: "Tous",
      miss: "Mississauga", bramp: "Brampton", caledon: "Caledon et Bolton", virtual: "Virtuel",
      tbc: "Date à confirmer", tba: "Heure à confirmer",
      kindSchool: "Séance de l'école", kindProgram: "Séance du programme", kindGeneral: "Séance générale",
      presented: "Aussi présentés :",
      register: "S'inscrire", join: "Se joindre à la séance",
      linkTbc: "Le lien de connexion est publié par le conseil ou l'école; consulte la source officielle ou la page du programme.", info: "Plus d'infos", flyer: "Dépliant", website: "Site de l'école",
      cal: "Ajouter au calendrier", calNote: "Heure de l'Est (Toronto). La durée est approximative.",
      none: "Aucune séance avec ces filtres.",
      count: (n) => `${n} séance${n === 1 ? "" : "s"}`,
      source: "Sources : PDF officiel des séances 2026 du DPCDSB et page des RLCP de Peel. Les horaires peuvent changer.",
      forSchool: "Séance d'information", forProgram: "Séances de ce programme",
      pd: { who: "À qui il s'adresse", reqs: "Exigences", how: "Comment faire la demande", keyDates: "Dates clés", sessions: "Séances d'information", hosts: "Où il est offert", links: "Information officielle", viewSchool: "Voir le profil de l'école", details: "Voir les détails", tapHint: "Touche la carte pour en savoir plus. Tu peux sélectionner et copier n'importe quel texte." },
    },
    detail: { close: "Fermer", profile: "Voir le profil", fraserH: "Cote Fraser", fraserAcademic: "Une mesure uniquement scolaire.", reportLink: "Bulletin Fraser", programsH: "Programmes et spécialisations", hostedH: "Programmes offerts ici", detailsH: "À propos de cette école", officialLink: "Site officiel du conseil", copy: "Copier le lien", copied: "Lien copié", addCompare: "Ajouter au comparateur", inCompare: "Dans le comparateur ✓", frenchNote: "École de langue française : l'admission exige l'admissibilité comme ayant droit (article 23)." },
    quiz: { h: "Tu ne sais pas par où commencer?", p: "Réponds à un questionnaire anonyme de 3 minutes et reçois des idées d'écoles et de programmes à explorer, avec un résultat en PDF. C'est une orientation, pas des services-conseils.", btn: "Faire le questionnaire" },
    nav: { capas: "Comment lire la carte", explorar: "Explorer et filtrer", escuelas: "Répertoire", comparar: "Comparer", regionales: "Programmes DPCDSB", peel: "Programmes Peel", grados: "À partir de quelle année", siglas: "Sigles", fechas: "Dates", preguntas: "Questions" },
    navLabel: "Sections",
    langLabel: "Langue",
    themeLabel: "Changer de thème",

    capasH: "Comment lire la carte",
    capasP: "Les options ne sont pas équivalentes. Il y a quatre niveaux distincts et certains peuvent se combiner.",
    layers: [
      { tag: "Niveau 1", h: "École", p: "L'établissement où vous étudiez. Toute école offre le programme secondaire régulier complet, plus quelques atouts qui lui sont propres." },
      { tag: "Niveau 2", h: "Programme régional", p: "Un programme spécial hébergé dans certaines écoles, qui accueille des élèves de toute la région. Il faut presque toujours présenter une demande, et le transport peut être à la charge de la famille." },
      { tag: "Niveau 3", h: "Spécialisation", p: "Un parcours au sein d'une école, comme une MHS (SHSM) ou l'éducation coopérative. Il se suit surtout en 11e et 12e année." },
      { tag: "Niveau 4", h: "Parcours", p: "Là où tout mène : université, collège, apprentissage ou travail. Cela dépend des combinaisons choisies." },
    ],

    exploreH: "Explorer et filtrer",
    exploreP: "Les filtres de conseil scolaire, de type de programme et la recherche touchent le répertoire et les programmes. « Commence en » et « Comment y entrer » ne touchent que les listes de programmes.",
    searchLabel: "Rechercher",
    searchPh: "Ex. BI, boulangerie, arts, Port Credit…",
    fSystem: "Conseil scolaire", fTag: "Type de programme", fStart: "Commence en (programmes)", fEntry: "Comment y entrer (programmes)", fSort: "Trier les écoles",
    all: "Tous",
    optSystem: { dpcdsb: "DPCDSB (catholique)", peel: "Peel (public)", fr: "Catholique de langue française" },
    optStart: { "9": "9e année", "10": "10e année", "11": "11e année" },
    optEntry: { auto: "Automatique (secteur)", apply: "Demande ou transfert requis" },
    optSort: { name: "Nom (A–Z)", fraser: "Cote Fraser (de la plus élevée à la plus basse)" },
    reset: "Réinitialiser les filtres",
    resultCount: (s, p) => `${s} école${s === 1 ? "" : "s"} · ${p} programme${p === 1 ? "" : "s"}`,
    noResults: "Aucun résultat avec ces filtres. Essayez de les réinitialiser.",

    escuelasH: "Répertoire des écoles secondaires de Mississauga",
    escuelasP: "Toutes les écoles, avec leurs programmes régionaux et leur cote Fraser. La cote est uniquement scolaire et ne classe pas la liste, sauf si vous choisissez de trier par cote.",
    lblFocus: "Orientation :",
    fraserLabel: "Cote Fraser",
    fraserOf: "/ 10",
    fraserRank: (r) => `${r}e rang en Ontario`,
    fraserPrev: (p) => `Année précédente : ${p}`,
    fraserNone: "Aucune cote Fraser dans le bulletin 2025",
    noPrograms: "Aucun programme régional propre. Offre le secondaire régulier; confirmez les MHS et l'éducation coopérative auprès de l'école.",
    moreInfo: "Plus de détails",
    fraserFoot: "Source : ",
    fraserWhatH: "Ce que mesure (et ne mesure pas) la cote Fraser",
    fraserWhat: "Elle est calculée à partir des résultats aux tests provinciaux : mathématiques de 9e année (théorique et appliqué), Test provincial de compétences linguistiques (TPCL, OSSLT), proportion de tests sous la norme et de tests non passés, et écarts entre les sexes. Elle ne mesure ni les arts, ni les sports, ni les programmes techniques, ni le climat, ni le soutien, ni les langues. Le contexte socioéconomique et la taille de l'échantillon comptent, et les cotes changent d'une année à l'autre. Utilisez-la comme un repère parmi d'autres, non comme un verdict.",
    compare: "Comparer",
    compareMax: "Maximum 4 écoles",

    compararH: "Comparateur d'écoles",
    compararP: "Choisissez jusqu'à 4 écoles de n'importe quel conseil pour les voir côte à côte.",
    compAdd: "Ajouter une école…",
    compRemove: "Retirer",
    compRows: { board: "Conseil scolaire", fraser: "Cote Fraser (2024-2025)", rank: "Rang en Ontario", prev: "Cote de l'année précédente", addr: "Emplacement", programs: "Programmes régionaux", focus: "Orientation", distinct: "Particularité", shsm: "Spécialisations (MHS)", langs: "Langues et autres", entry: "Comment y entrer" },
    compEmpty: "Sélectionnez au moins deux écoles pour les comparer.",
    compCol: "École",
    none: "—",

    regionalesH: "Programmes régionaux du DPCDSB",
    regionalesP: "Programmes qui accueillent des élèves de toute la région. L'école hôte est celle où l'on suit le programme; les sites de Mississauga sont indiqués.",
    peelH: "Programmes régionaux de Peel (RLCP)",
    peelP: "Les Regional Learning Choices Programs (RLCP) de Peel sont ouverts aux élèves qui habitent à Peel, y compris ceux qui fréquentent actuellement le système catholique. On présente sa demande selon son secteur (adresse du domicile); il vaut la peine de les connaître avant d'écarter quoi que ce soit.",
    host: "Sites : ",
    inMiss: "Mississauga",
    secondEntry: "Deuxième point d'entrée : ",
    peelHowH: "Comment ça fonctionne",
    peelHow: "Entrée en 9e année par demande en ligne. Des frais de demande et des frais annuels par programme s'appliquent. On examine les notes de 7e année et, pour certains programmes, une audition, une évaluation ou une réponse écrite. Un tirage au sort a ensuite lieu parmi les candidats qui répondent aux critères.",
    peelRuleH: "Règles importantes",
    peelRule: "Vous devez demander le programme qui correspond à votre secteur selon votre adresse. Les élèves titulaires d'un visa d'étudiant international ne sont pas admissibles (les titulaires d'un permis de travail ou d'études peuvent postuler).",
    startsAt: { "9": "Dès la 9e", "10": "Dès la 10e", "11": "Dès la 11e" },
    applyChip: "Demande",

    gradosH: "À partir de quelle année chaque option commence-t-elle?",
    gradosP: "Plusieurs options n'apparaissent qu'en 10e ou en 11e année. Il vaut donc la peine de voir tout le parcours avant de décider pour la 9e année.",
    tlOption: "Option",
    tlConfirmed: "Confirmé",
    tlSoft: "Préparation ou plage habituelle, à confirmer auprès de chaque école",
    timeline: [
      { label: "Secondaire régulier", sub: "N'importe quelle école", from: 1, to: 5, txt: "Cours réguliers", soft: false },
      { label: "AP", sub: "Par matière", segs: [[1, 3, "Préparation", true], [3, 5, "Cours et examens AP", false]] },
      { label: "BI", sub: "Diplôme de deux ans", segs: [[1, 3, "Séquence préalable (PEI ou pré-BI)", true], [3, 5, "Diplôme du BI", false]] },
      { label: "STEAM, arts, sports", sub: "Programmes régionaux", from: 1, to: 5, txt: "Dès la 9e année", soft: false },
      { label: "École de boulangerie", sub: "Goetz", from: 2, to: 5, txt: "10e à 12e année", soft: false },
      { label: "MHS (SHSM)", sub: "Spécialisation", from: 3, to: 5, txt: "11e–12e année", soft: false },
      { label: "Éducation coopérative", sub: "Expérience de travail avec crédit", from: 3, to: 5, txt: "Années supérieures", soft: false },
      { label: "PAJO et double reconnaissance", sub: "Métiers et collège", from: 3, to: 5, txt: "Habituellement 11e–12e", soft: true },
    ],

    siglasH: "Les sigles en une ligne",
    glossary: [
      ["AP", "Cours de niveau universitaire, matière par matière.", "Modulaire et flexible."],
      ["BI", "Diplôme complet et structuré de deux ans (Baccalauréat international).", "Tout l'ensemble, pas des matières isolées."],
      ["PEI / pré-BI", "Séquences menant au diplôme du BI à Peel : PEI (Glenforest) et pré-BI (Erindale).", ""],
      ["MHS (SHSM)", "Majeure haute spécialisation : une spécialisation sectorielle (TIC, affaires, tourisme et accueil, transport, arts et autres) avec cours, certifications et éducation coopérative.", "Suivie en 11e–12e année."],
      ["Éducation coopérative", "Étudier et travailler dans une vraie entreprise, et obtenir des crédits.", ""],
      ["PAJO (OYAP)", "Programme d'apprentissage pour les jeunes de l'Ontario : commencer un apprentissage de métier tout en terminant le secondaire.", ""],
      ["Double reconnaissance", "Cours collégiaux qui comptent aussi pour le diplôme d'études secondaires.", ""],
      ["RLCP", "Regional Learning Choices Programs : les programmes régionaux de Peel.", ""],
      ["École d'accueil (feeder)", "L'école secondaire attribuée par défaut à une école élémentaire.", ""],
      ["Secteur (boundary)", "La zone de résidence qui détermine l'école fréquentée sans avoir à présenter de demande.", ""],
      ["TPCL (OSSLT)", "Test provincial de compétences linguistiques : sert en partie de base à la cote Fraser.", ""],
    ],

    fechasH: "Dates à mettre à l'agenda",
    fechasP: "Voici les dates déjà connues. Confirmez-les toujours sur le site de chaque conseil ou école.",
    dates: [
      { when: "8 oct. – 26 nov. 2026", b: "Séances d'information du DPCDSB", p: "école par école (voir le calendrier plus bas)." },
      { when: "6 oct. 2026", b: "Soirée d'information virtuelle de Peel", p: "pour les familles d'élèves noirs et afro-caribéens (18 h–19 h), sur les RLCP, Explore High Skills et les métiers spécialisés." },
      { when: "21 oct. – 5 nov. 2026", b: "Soirées d'information des programmes RLCP de Peel", p: "une par programme : BI 21 oct.; AP, SciTech et cordes 22 oct.; arts 27 oct.; IBT 28 oct.; métiers spécialisés 29 oct.; transport 5 nov." },
      { when: "3–24 nov. 2026", b: "Demandes RLCP de Peel", p: "pour l'année scolaire 2027-2028. Premières offres : 2 février 2027." },
      { when: "5 déc. 2026 – 28 janv. 2027", b: "Évaluations et auditions de Peel", p: "AP et cordes 5 déc.; BI 12 déc.; arts et métiers spécialisés 27–28 janv. (l'heure est fixée par chaque école)." },
      { when: "8 janv. 2027", b: "École de boulangerie (Goetz)", p: "date limite de la première ronde de demandes pour commencer en septembre 2027." },
      { when: "À confirmer", b: "Demandes des programmes régionaux du DPCDSB", p: "(AP, BI, arts, sports, STIM, boulangerie). Confirmées à chaque présentation; le programme STEAM de St. Joan of Arc ouvre en octobre, selon le conseil." },
    ],

    preguntasH: "Questions à apporter aux séances d'information",
    preguntasP: "Pour écouter avec un esprit critique et pas seulement la présentation de chaque école.",
    questions: [
      "Qu'a cette école que l'école voisine n'a pas?",
      "Quels programmes exigent une demande, et jusqu'à quand?",
      "Que peut-on suivre dès la 9e année et que seulement en 11e–12e?",
      "Quelles notes ou exigences demande-t-on, et y a-t-il une audition ou un portfolio?",
      "Y a-t-il du transport, ou est-ce la famille qui l'assume? Quels frais supplémentaires y a-t-il?",
      "Quelles certifications peut-on obtenir et quelle éducation coopérative existe?",
      "Avec quelles universités, quels collèges ou quelles industries travaillent-ils?",
      "Peut-on combiner des programmes, par exemple le BI avec l'éducation coopérative?",
    ],

    pendingH: "Ce qu'il reste à confirmer",
    pendingP: "Données qui n'ont pas pu être vérifiées et qu'il vaut la peine de valider à chaque séance d'information ou sur le site de l'école.",
    pending: [
      "Adresses exactes de plusieurs écoles et distance depuis la maison",
      "Liste complète des MHS de chaque école (le DPCDSB publie une matrice 2026-2027 de 57 programmes)",
      "Coûts, transport et dates de demande des programmes régionaux du DPCDSB",
      "Exigences scolaires et auditions pour les arts, les sports et les STIM",
      "Les écoles de Peel sans RLCP offrent aussi l'éducation coopérative, des MHS et Explore High Skills; à vérifier sur chaque site",
      "La cote Fraser est mise à jour chaque automne : consultez le bulletin le plus récent",
    ],
    sourcesH: "Sources consultées",
    disclaimer: "Site d'information indépendant, sans lien avec le DPCDSB, Peel ni l'Institut Fraser. L'information peut changer : vérifiez toujours auprès des sources officielles.",
    backTop: "Retour en haut",
  },
};

export const SOURCES = [
  ["DPCDSB schools: official course calendars and SHSM pages (<school>.dpcdsb.org)", "https://www.dpcdsb.org/schools/school-directory"],
  ["Peel schools: program pages of each school (<school>.peelschools.org)", "https://www.peelschools.org/"],
  ["Regional Bakery School at Fr. Michael Goetz", "https://goetz.dpcdsb.org/programs/regional-programs"],
  ["DPCDSB, Secondary School Information Sessions 2026", "https://www.dpcdsb.org/dpcdsb/events/secondary-school-information-sessions"],
  ["DPCDSB, Regional Secondary Programs 2025-26", "https://www.dpcdsb.org/download/527393"],
  ["DPCDSB, Regional Advanced Placement", "https://www.dpcdsb.org/programs-services/secondary/advanced-placement"],
  ["DPCDSB, International Baccalaureate", "https://www.dpcdsb.org/programs-services/secondary/international-baccalaureate"],
  ["DPCDSB, Regional Arts Program", "https://www.dpcdsb.org/programs-services/secondary/regional-arts-program"],
  ["DPCDSB, Regional STEM Program", "https://www.dpcdsb.org/programs-services/secondary/regional-stem-program"],
  ["DPCDSB, Regional Sports Program", "https://www.dpcdsb.org/programs-services/secondary/regional-sports-program"],
  ["DPCDSB, Extended French and French Immersion", "https://www.dpcdsb.org/programs-services/secondary/french-immersion-program"],
  ["DPCDSB, Specialist High Skills Major", "https://www.dpcdsb.org/programs-services/secondary/specialist-high-skills-major"],
  ["DPCDSB, Canada Bakery School 2026-27", "https://www.dpcdsb.org/dpcdsb/news/post/dpcdsb-now-accepting-applications-for-canada-bakery-school-regional-program-2026-27"],
  ["Peel, Secondary Regional Learning Choices Programs", "https://www.peelschools.org/secondary-regional-learning-choice-programs"],
  ["Peel, IB", "https://www.peelschools.org/ib"],
  ["Peel, Arts", "https://www.peelschools.org/arts"],
  ["Peel, SciTech", "https://www.peelschools.org/scitech"],
  ["Peel, Strings", "https://www.peelschools.org/strings"],
  ["Peel, International Business and Technology", "https://www.peelschools.org/international-business-and-technology"],
  ["Peel, Regional Skilled Trades", "https://www.peelschools.org/regional-skilled-trades-program"],
  ["Fraser Institute, Report Card on Ontario's Secondary Schools 2025", FRASER.url],
];

/* ------------------------------------------------------------------ */
/* Schools. Fraser data: 2025 report, 2024-25 school year.             */
/* fraser: { score, rank, prev } ; prev = previous-year score or null. */
/* progs: verified regional programs (tag + optional note).            */
/* ------------------------------------------------------------------ */
const P = (k, n) => ({ k, n });
const F = (score, rank, prev) => ({ score, rank, prev });

export const SCHOOLS = [
  // ---------------- DPCDSB (Catholic) ----------------
  { id: "goetz", board: "dpcdsb", name: "Father Michael Goetz", addr: "330 Central Pkwy W", fraser: F(4.0, 654, 5.2),
    progs: [P("bakery", x("Regional Bakery School, Grade 10–12, primer año 2026-27", "Regional Bakery School, Grades 10–12, first year 2026-27", "École régionale de boulangerie, 10e–12e année, première année 2026-2027")), P("shsm", x("ICT y Arts & Culture", "ICT and Arts & Culture", "TIC et arts et culture"))],
    focus: x("una secundaria completa, con tecnología y un programa técnico de panadería. No es una escuela dedicada solo a la panadería.", "full high school with technology and a technical bakery program. It is not a “bakery school” overall.", "école secondaire complète avec technologie et un programme technique de boulangerie. Ce n'est pas une « école de boulangerie » en soi."),
    kv: {
      distinct: x("Regional Bakery School: cuatro cursos de panadería de Grade 10 a 12, con Co-op u OYAP.", "Regional Bakery School: four bakery courses in Grades 10 to 12, with Co-op or OYAP.", "École régionale de boulangerie : quatre cours de boulangerie de la 10e à la 12e année, avec éducation coopérative ou PAJO."),
      shsm: x("SHSM en Information & Communications Technology (ICT) y en Arts & Culture", "SHSM in Information & Communications Technology (ICT) and in Arts & Culture", "MHS en technologies de l'information et des communications (TIC) et en arts et culture"),
      langs: x("También Computer Science y Co-op", "Also Computer Science and Co-op", "Aussi informatique et éducation coopérative"),
      entry: x("Regular: automática si vives dentro de su boundary. Bakery: hay que aplicar.", "Regular: automatic if you live in its boundary. Bakery: application required.", "Régulier : automatique si vous habitez dans son secteur. Boulangerie : demande requise."),
    } },
  { id: "pocock", board: "dpcdsb", name: "Philip Pocock", addr: "4555 Tomken Rd", fraser: F(5.9, 401, 7.0),
    progs: [P("fi"), P("ef"), P("shsm", x("Arts & Culture, Hospitality & Tourism y Transportation", "Arts & Culture, Hospitality & Tourism and Transportation", "Arts et culture, tourisme et accueil et transport"))],
    focus: x("una mezcla de idiomas, artes, hospitalidad (hospitality) y áreas técnicas.", "a visible mix of languages, arts, hospitality and technical areas.", "combinaison visible de langues, d'arts, d'accueil et de domaines techniques."),
    kv: {
      distinct: x("SHSM en Transportation, conectado con áreas técnicas", "Transportation SHSM, tied to technical fields", "MHS en transport, lié aux domaines techniques"),
      shsm: x("SHSM en Arts & Culture, Hospitality & Tourism y Transportation", "SHSM in Arts & Culture, Hospitality & Tourism and Transportation", "MHS en arts et culture, tourisme et accueil, et transport"),
      langs: x("French Immersion y Extended French", "French Immersion and Extended French", "Immersion française et français prolongé"),
      entry: x("Regular: traslado si vives fuera de su boundary. Los programas de francés tienen su propio proceso.", "Regular: transfer if you live outside its boundary. French programs have their own process.", "Régulier : transfert si vous habitez hors de son secteur. Les programmes de français ont leur propre processus."),
    } },
  { id: "cabot", board: "dpcdsb", name: "John Cabot", addr: "Mississauga East", fraser: F(4.4, 620, 5.8),
    progs: [P("shsm", x("ICT", "ICT", "TIC"))],
    focus: x("negocios, tecnología y medios digitales, con un camino claro hacia el emprendimiento.", "business, technology and digital media, with a clear path to entrepreneurship.", "affaires, technologie et médias numériques, avec une voie claire vers l'entrepreneuriat."),
    kv: {
      distinct: x("Combina tecnología, creatividad y negocios. Incluye animación, cine y fotografía, no solo programación.", "Mixes technology with creativity and business. Includes animation, film and photography, not just programming.", "Allie technologie, créativité et affaires. Comprend l'animation, le cinéma et la photographie, pas seulement la programmation."),
      shsm: x("SHSM en ICT", "SHSM in ICT", "MHS en TIC"),
      langs: x("Business, ICT, Media, producción digital y Co-op", "Business, ICT, Media, digital production and Co-op", "Affaires, TIC, médias, production numérique et éducation coopérative"),
      entry: x("Traslado si vives fuera de su boundary", "Transfer if you live outside its boundary", "Transfert si vous habitez hors de son secteur"),
    } },
  { id: "sfx", board: "dpcdsb", name: "St. Francis Xavier", addr: "Mississauga East", fraser: F(8.0, 86, 8.0),
    progs: [P("ib", x("IB Diploma (sede regional)", "IB Diploma (regional host)", "Diplôme du BI (site régional)")), P("shsm", x("Varios SHSM", "Several SHSMs", "Plusieurs MHS"))],
    focus: x("una ruta académica distinta, con el International Baccalaureate (IB) y una oferta amplia.", "an alternative academic pathway with the International Baccalaureate and a broad offering.", "parcours scolaire alternatif avec le Baccalauréat international et une offre étendue."),
    kv: {
      distinct: x("IB Diploma Programme: un programa integrado y estructurado, distinto de la secundaria regular", "IB Diploma Programme: an integrated, structured program, different from regular high school", "Programme du diplôme du BI : programme intégré et structuré, distinct du secondaire régulier"),
      shsm: x("Varios SHSM", "Several SHSMs", "Plusieurs MHS"),
      langs: x("—", "—", "—"),
      entry: x("Regular: traslado. IB: hay que aplicar, según el boundary regional del IB.", "Regular: transfer. IB: application, according to the regional IB boundary.", "Régulier : transfert. BI : demande, selon le secteur régional du BI."),
    } },
  { id: "loyola", board: "dpcdsb", name: "Loyola", addr: "4010 Sladeview Cres", fraser: F(7.0, 220, 7.2), progs: [P("fi"), P("ef")] },
  { id: "aloysius", board: "dpcdsb", name: "St. Aloysius Gonzaga", addr: "2800 Erin Centre Blvd", fraser: F(7.7, 119, 7.6), progs: [P("ef")] },
  { id: "joseph", board: "dpcdsb", name: "St. Joseph", addr: "Mississauga", fraser: F(8.2, 65, 7.6), progs: [P("ap", x("Sede AP para Mississauga", "AP host for Mississauga", "Site AP pour Mississauga"))] },
  { id: "paul", board: "dpcdsb", name: "St. Paul", addr: "Mississauga", fraser: F(7.7, 119, 7.6), progs: [P("ib", x("IB Diploma (sede regional)", "IB Diploma (regional host)", "Diplôme du BI (site régional)"))] },
  { id: "iona", board: "dpcdsb", name: "Iona", addr: "Mississauga", fraser: F(6.2, 349, null), progs: [P("arts", x("Regional Arts: danza, teatro, música, medios y artes visuales", "Regional Arts: dance, drama, music, media and visual arts", "Arts régionaux : danse, théâtre, musique, médias et arts visuels")), P("shsm", x("Arts & Culture", "Arts & Culture", "Arts et culture"))] },
  { id: "joan", board: "dpcdsb", name: "St. Joan of Arc", addr: "Mississauga", fraser: F(5.9, 401, 6.7), progs: [P("stem", x("Regional STEAM, Grades 9–12", "Regional STEAM, Grades 9–12", "STEAM régional, 9e–12e année"))] },
  { id: "martin", board: "dpcdsb", name: "St. Martin", addr: "Mississauga", fraser: F(4.9, 559, 5.9), progs: [P("sports", x("Regional Sports", "Regional Sports", "Sports régional"))] },
  { id: "marcellinus", board: "dpcdsb", name: "St. Marcellinus", addr: "Mississauga", fraser: F(7.9, 95, 8.1), progs: [P("shsm", x("Arts & Culture", "Arts & Culture", "Arts et culture"))] },
  { id: "ascension", board: "dpcdsb", name: "Ascension of Our Lord", addr: "Mississauga", fraser: F(4.9, 559, 5.4), progs: [P("shsm", x("Business", "Business", "Affaires"))] },
  { id: "carmel", board: "dpcdsb", name: "Our Lady of Mount Carmel", addr: "Mississauga", fraser: F(6.9, 238, 7.0), progs: [] },
  { id: "romero", board: "dpcdsb", name: "St. Oscar Romero", addr: "2495 Credit Valley Rd", fraser: null, progs: [P("alt", x("Programa alternativo del DPCDSB", "DPCDSB alternative program", "Programme alternatif du DPCDSB"))] },

  // ---------------- Peel (public) ----------------
  { id: "johnfraser", board: "peel", name: "John Fraser SS", addr: "Mississauga", fraser: F(8.8, 29, null), progs: [P("ap", x("RLCP: Advanced Placement", "RLCP: Advanced Placement", "RLCP : Advanced Placement"))] },
  { id: "streetsville", board: "peel", name: "Streetsville SS", addr: "Mississauga", fraser: F(7.9, 95, null), progs: [] },
  { id: "lornepark", board: "peel", name: "Lorne Park SS", addr: "Mississauga", fraser: F(7.6, 130, null), progs: [] },
  { id: "portcredit", board: "peel", name: "Port Credit SS", addr: "Mississauga", fraser: F(7.2, 178, null), progs: [P("stem", x("RLCP: SciTech", "RLCP: SciTech", "RLCP : SciTech")), P("strings", x("RLCP: Strings", "RLCP: Strings", "RLCP : Cordes"))] },
  { id: "cawthra", board: "peel", name: "Cawthra Park SS", addr: "Mississauga", fraser: F(7.1, 201, null), progs: [P("arts", x("RLCP: Arts (al sur de la 401)", "RLCP: Arts (south of the 401)", "RLCP : Arts (au sud de la 401)"))] },
  { id: "glenforest", board: "peel", name: "Glenforest SS", addr: "Mississauga", fraser: F(6.8, 254, null), progs: [P("ib", x("RLCP: MYP IB (camino al Diploma)", "RLCP: MYP IB (path to the Diploma)", "RLCP : PEI du BI (voie vers le diplôme)"))] },
  { id: "mississ", board: "peel", name: "Mississauga SS", addr: "Mississauga", fraser: F(6.7, 275, null), progs: [] },
  { id: "erindale", board: "peel", name: "Erindale SS", addr: "Mississauga", fraser: F(6.2, 349, null), progs: [P("ib", x("RLCP: Pre-IB (camino al Diploma)", "RLCP: Pre-IB (path to the Diploma)", "RLCP : pré-BI (voie vers le diplôme)"))] },
  { id: "meadowvale", board: "peel", name: "Meadowvale SS", addr: "Mississauga", fraser: F(6.1, 367, null), progs: [P("ibt", x("RLCP: IBT", "RLCP: IBT", "RLCP : IBT"))] },
  { id: "stephenlewis", board: "peel", name: "Stephen Lewis SS", addr: "Mississauga", fraser: F(6.0, 390, null), progs: [] },
  { id: "rickhansen", board: "peel", name: "Rick Hansen SS", addr: "Mississauga", fraser: F(5.5, 478, null), progs: [] },
  { id: "applewood", board: "peel", name: "Applewood Heights SS", addr: "Mississauga", fraser: F(5.4, 497, null), progs: [] },
  { id: "lma", board: "peel", name: "Lincoln M. Alexander SS", addr: "Mississauga", fraser: F(4.8, 573, null), progs: [] },
  { id: "clarkson", board: "peel", name: "Clarkson SS", addr: "Mississauga", fraser: F(4.6, 591, null), progs: [] },
  { id: "tlkennedy", board: "peel", name: "Thomas L. Kennedy SS", addr: "Mississauga", fraser: F(3.3, 694, null),
    progs: [P("shsm", x("Business e ICT", "Business and ICT", "Affaires et TIC"))] },
  { id: "westcredit", board: "peel", name: "West Credit SS", addr: "Mississauga", fraser: F(0.9, 737, null),
    progs: [P("trades", x("RLCP: Regional Skilled Trades", "RLCP: Regional Skilled Trades", "RLCP : métiers spécialisés régionaux"))],
    fnote: x("Valor inusualmente bajo: revisa el informe original antes de sacar conclusiones.", "Unusually low value: check the original report before drawing conclusions.", "Valeur inhabituellement basse : consultez le bulletin original avant de tirer des conclusions.") },
  { id: "gordon", board: "peel", name: "Gordon Graydon", addr: "Mississauga", fraser: null, progs: [] },

  // ---------------- French-language Catholic ----------------
  { id: "famille", board: "fr", name: "Sainte-Famille", addr: "Mississauga", fraser: F(7.3, 158, 7.4), progs: [],
    fnote: x("Escuela de lengua francesa: para entrar hay que cumplir los requisitos de titular de derechos (sección 23).", "French-language school: entry requires rights-holder eligibility (section 23).", "École de langue française : l'admission exige l'admissibilité comme ayant droit (article 23).") },
];

/* ------------------------------------------------------------------ */
/* Regional programs. hosts: [name, inMississauga]                     */
/* ------------------------------------------------------------------ */
const H = (n, m = false) => ({ n, m });

export const PROGRAMS = [
  // DPCDSB
  { id: "ap", board: "dpcdsb", tag: "ap", start: "9", entry: "apply", name: x("Advanced Placement (AP)", "Advanced Placement (AP)", "Advanced Placement (AP)"),
    hosts: [H("St. Joseph CSS", true), H("St. Edmund Campion CSS (Brampton)")],
    p: x("Cursos de nivel universitario dentro de la secundaria. No es «una escuela más difícil»: eliges materia por materia, y los exámenes AP pueden darte créditos universitarios. St. Joseph atiende a Mississauga.", "University-level courses inside high school. It is not “a harder school”. You choose subject by subject and AP exams can earn university credit. St. Joseph serves Mississauga.", "Cours de niveau universitaire au secondaire. Ce n'est pas « une école plus difficile ». On choisit matière par matière et les examens AP peuvent donner des crédits universitaires. St. Joseph dessert Mississauga.") },
  { id: "ib", board: "dpcdsb", tag: "ib", start: "11", entry: "apply", name: x("International Baccalaureate (IB)", "International Baccalaureate (IB)", "Baccalauréat international (BI)"),
    hosts: [H("St. Francis Xavier CSS", true), H("St. Paul CSS", true), H("Notre Dame CSS (Brampton)")],
    p: x("Diploma preuniversitario de dos años. Eliges una materia de cada uno de seis grupos. Es un paquete integrado, no modular como el AP.", "Two-year pre-university diploma. The student chooses one subject from each of six groups. It is an integrated package, not modular like AP.", "Diplôme préuniversitaire de deux ans. L'élève choisit une matière dans chacun des six groupes. C'est un ensemble intégré, non modulaire comme l'AP.") },
  { id: "steam", board: "dpcdsb", tag: "stem", start: "9", entry: "apply", name: x("Regional STEM / STEAM", "Regional STEM / STEAM", "STIM / STEAM régional"),
    hosts: [H("St. Joan of Arc CSS", true), H("St. Marguerite d'Youville CSS (Brampton)"), H("St. Augustine CSS (Brampton)")],
    p: x("Grade 9 a 12. En St. Joan of Arc: proyectos prácticos, investigación, design thinking y resolución creativa de problemas. Las sedes de Brampton suman opciones de SHSM (Healthcare, ICT, Hospitality) e iSTEAM.", "Grades 9–12. At St. Joan of Arc: hands-on projects, inquiry, design thinking and creative problem solving. The Brampton sites add SHSM options (Healthcare, ICT, Hospitality) and iSTEAM.", "9e–12e année. À St. Joan of Arc : projets pratiques, enquête, design thinking et résolution créative de problèmes. Les sites de Brampton ajoutent des options de MHS (santé, TIC, accueil) et l'iSTEAM.") },
  { id: "arts", board: "dpcdsb", tag: "arts", start: "9", entry: "apply", name: x("Regional Arts", "Regional Arts", "Arts régionaux"),
    hosts: [H("Iona CSS", true), H("St. Thomas Aquinas CSS (Brampton)"), H("St. Roch CSS (Brampton)")],
    p: x("Danza, teatro, música instrumental y vocal, medios y artes visuales. Puede pedir audición o portafolio.", "Dance, drama, instrumental and vocal music, media and visual arts. May require an audition or portfolio.", "Danse, théâtre, musique instrumentale et vocale, médias et arts visuels. Peut exiger une audition ou un portfolio.") },
  { id: "sports", board: "dpcdsb", tag: "sports", start: "9", entry: "apply", name: x("Regional Sports", "Regional Sports", "Sports régional"),
    hosts: [H("St. Martin CSS", true)],
    p: x("Deporte, condición física, liderazgo y educación física. No es solo para atletas de élite. Puede conectar con un SHSM de Sports.", "Sport, fitness, leadership and physical education. Not only for elite athletes. Can connect to a Sports SHSM.", "Sport, conditionnement physique, leadership et éducation physique. Pas seulement pour les athlètes d'élite. Peut se relier à une MHS en sports.") },
  { id: "bakery", board: "dpcdsb", tag: "bakery", start: "10", entry: "apply", name: x("Bakery School", "Bakery School", "École de boulangerie"),
    hosts: [H("Father Michael Goetz CSS", true)],
    p: x("Un camino técnico dentro de una secundaria general. Cuatro cursos de panadería y experiencia real con Co-op u OYAP. Grade 10 a 12.", "A technical pathway inside a general high school. Four bakery courses and real experience through Co-op or OYAP. Grades 10–12.", "Voie technique au sein d'une école secondaire générale. Quatre cours de boulangerie et une expérience réelle par l'éducation coopérative ou le PAJO. 10e–12e année.") },
  { id: "fi", board: "dpcdsb", tag: "fi", start: "9", entry: "apply", name: x("French Immersion (secundaria)", "French Immersion (secondary)", "Immersion française (secondaire)"),
    hosts: [H("Philip Pocock CSS", true), H("Loyola CSS", true), H("Cardinal Leger CSS (Brampton)")],
    p: x("Continuación de French Immersion para quienes la cursaron en primaria (desde Grade 1). Tiene su propio proceso de inscripción.", "Continuation of French Immersion for students who took it in elementary (from Grade 1). It has its own registration process.", "Suite de l'immersion française pour les élèves qui l'ont suivie à l'élémentaire (dès la 1re année). Processus d'inscription distinct.") },
  { id: "ef", board: "dpcdsb", tag: "ef", start: "9", entry: "apply", name: x("Extended French (secundaria)", "Extended French (secondary)", "Français prolongé (secondaire)"),
    hosts: [H("Philip Pocock CSS", true), H("St. Aloysius Gonzaga CSS", true), H("Loyola CSS", true), H("Robert F. Hall CSS (Caledon)"), H("Cardinal Leger CSS (Brampton)"), H("St. Roch CSS (Brampton)")],
    p: x("Seis secundarias del DPCDSB ofrecen el programa; tres están en Mississauga. Cada centro recibe estudiantes de primarias asignadas.", "Six secondary schools in DPCDSB; three are in Mississauga. Each centre takes students from designated elementary schools.", "Six écoles secondaires au DPCDSB; trois sont à Mississauga. Chaque centre accueille des élèves d'écoles élémentaires désignées.") },
  { id: "alt", board: "dpcdsb", tag: "alt", start: "9", entry: "apply", name: x("Programa alternativo", "Alternative program", "Programme alternatif"),
    hosts: [H("St. Oscar Romero CSS", true)],
    p: x("Una alternativa a la secundaria tradicional. Confirma los requisitos y el proceso en el sitio de la escuela.", "An alternative to traditional high school. Confirm requirements and process on the school's website.", "Solution de rechange au secondaire traditionnel. Confirmez les exigences et le processus sur le site de l'école.") },

  // Peel RLCP
  { id: "p-ib", board: "peel", tag: "ib", start: "9", entry: "apply", name: x("IB", "IB", "BI"),
    hosts: [H("Glenforest SS (MYP)", true), H("Erindale SS (Pre-IB)", true), H("Turner Fenton SS (MYP, Brampton)"), H("Harold M. Brathwaite SS (Pre-IB, Brampton)")],
    p: x("Al Diploma IB se llega por MYP (Glenforest, Turner Fenton) o por Pre-IB (Erindale, Harold M. Brathwaite).", "The IB Diploma is reached through MYP (Glenforest, Turner Fenton) or Pre-IB (Erindale, Harold M. Brathwaite).", "On accède au diplôme du BI par le PEI (Glenforest, Turner Fenton) ou le pré-BI (Erindale, Harold M. Brathwaite)."),
    second: x("Grade 11: se necesitan las matemáticas de Grade 10 y MCR3U, y francés académico de Grade 10.", "Grade 11: requires Grade 10 math and MCR3U, and Grade 10 Academic French.", "11e année : exige les mathématiques de 10e année et MCR3U, et le français théorique de 10e année.") },
  { id: "p-arts", board: "peel", tag: "arts", start: "9", entry: "apply", name: x("Arts", "Arts", "Arts"),
    hosts: [H("Cawthra Park SS (al sur de la 401)", true), H("Mayfield SS (al norte de la 401, Caledon)")],
    p: x("Danza, teatro, música (instrumental o vocal) o artes visuales. Se necesita audición o portafolio.", "Dance, drama, music (instrumental or vocal) or visual arts. Requires an audition or portfolio.", "Danse, théâtre, musique (instrumentale ou vocale) ou arts visuels. Audition ou portfolio requis."),
    second: x("Grade 10 (para estudiantes actuales de Grade 9).", "Grade 10 (for current Grade 9 students).", "10e année (pour les élèves actuels de 9e année).") },
  { id: "p-ap", board: "peel", tag: "ap", start: "9", entry: "apply", name: x("Advanced Placement (AP)", "Advanced Placement (AP)", "Advanced Placement (AP)"),
    hosts: [H("John Fraser SS", true), H("Central Peel SS (Brampton)")],
    p: x("Preparación universitaria para estudiantes muy motivados. Incluye una evaluación presencial de matemáticas y lectoescritura.", "University readiness for highly motivated students. Includes an in-person numeracy and literacy assessment.", "Préparation à l'université pour des élèves très motivés. Comprend une évaluation en personne en numératie et en littératie.") },
  { id: "p-scitech", board: "peel", tag: "stem", start: "9", entry: "apply", name: x("SciTech", "SciTech", "SciTech"),
    hosts: [H("Port Credit SS", true), H("Chinguacousy SS (Brampton)")],
    p: x("STEM con alianzas con instituciones postsecundarias y con la industria, tecnología de nivel profesional, excursiones y competencias.", "STEM with post-secondary and industry partners, industry-standard technology, excursions and competitions.", "STIM avec partenaires postsecondaires et industriels, technologie aux normes de l'industrie, sorties et compétitions.") },
  { id: "p-ibt", board: "peel", tag: "ibt", start: "9", entry: "apply", name: x("International Business & Technology (IBT)", "International Business & Technology (IBT)", "International Business & Technology (IBT)"),
    hosts: [H("Meadowvale SS", true), H("North Park SS (Brampton)")],
    p: x("Negocios y tecnología con visión global, aprendizaje por proyectos, emprendimiento, robótica y STEM. Se pide un video de 1 min 30 s.", "Business and technology with a global outlook, project-based learning, entrepreneurship, robotics and STEM. Requires a 1:30 video.", "Affaires et technologie avec un regard mondial, apprentissage par projets, entrepreneuriat, robotique et STIM. Vidéo de 1 min 30 requise.") },
  { id: "p-tet", board: "peel", tag: "trades", start: "9", entry: "apply", name: x("Transportation, Engineering & Technology", "Transportation, Engineering & Technology", "Transport, ingénierie et technologie"),
    hosts: [H("Bramalea SS (Brampton)")],
    p: x("Industrias de transporte terrestre, marítimo y aeroespacial, con apoyo de socios de la industria. La sede está fuera de Mississauga.", "Land, marine and aerospace transportation industries, with industry partner support. The host is outside Mississauga.", "Industries du transport terrestre, maritime et aérospatial, avec l'appui de partenaires. Le site est hors de Mississauga.") },
  { id: "p-strings", board: "peel", tag: "strings", start: "9", entry: "apply", name: x("Strings", "Strings", "Cordes"),
    hosts: [H("Port Credit SS", true), H("Central Peel SS (Brampton)")],
    p: x("Estudio de un instrumento de cuerda, de principiante a avanzado, con experiencia orquestal. Se necesita audición.", "Study of a string instrument, from beginner to advanced, with an orchestral experience. Requires an audition.", "Étude d'un instrument à cordes, du débutant à l'avancé, avec expérience orchestrale. Audition requise.") },
  { id: "p-trades", board: "peel", tag: "trades", start: "9", entry: "apply", name: x("Regional Skilled Trades", "Regional Skilled Trades", "Métiers spécialisés régionaux"),
    hosts: [H("West Credit SS", true), H("Judith Nyman SS (Brampton)")],
    p: x("Aprendizaje práctico en oficios como la construcción. Según la sede, se pide un artefacto, una encuesta de intereses y una audición.", "Experiential learning in trades such as construction. Depending on the host, an artifact, a survey of interest and an audition are required.", "Apprentissage expérientiel dans des métiers comme la construction. Selon le site, un artefact, un sondage d'intérêts et une audition sont exigés."),
    second: x("Grade 11.", "Grade 11.", "11e année.") },
];

/* Schools whose own website names their SHSM sectors get an SHSM chip listing them (see school-extras.js). */
for (const sc of SCHOOLS) {
  const e = EXTRAS[sc.id];
  if (!e || !e.shsm || !e.shsm.length) continue;
  const note = { es: e.shsm.join(", "), en: e.shsm.join(", "), fr: e.shsm.join(", ") };
  const i = sc.progs.findIndex((p) => p.k === "shsm");
  if (i >= 0) sc.progs[i] = { k: "shsm", n: note }; else sc.progs.push({ k: "shsm", n: note });
}

/* Icons for program types (emoji, no external assets). */
export const TAG_ICON = {
  ib: "🌐", ap: "🎓", arts: "🎨", stem: "🔬", sports: "⚽", fi: "🇨🇦", ef: "🥖", bakery: "🥐",
  trades: "🛠️", ibt: "💼", strings: "🎻", alt: "🧭", shsm: "⭐",
};

/* Program types shown as quick "vibe" chips on the home page. */
export const VIBES = ["ib", "ap", "arts", "stem", "sports", "fi", "trades", "ibt"];

/* Teen-tone overrides. The "Family" tone uses the base UI text above.
   Keys here fully replace the base ones (nested objects are replaced whole). */
export const TEEN = {
  es: {
    eyebrow: "Mississauga · Grade 9 · septiembre 2027",
    h1a: "Encuentra tu high school",
    h1b: "en Mississauga",
    lead: "33 escuelas y todos los programas, sin enredos. Filtra por lo que te gusta, compara y haz el vibe check para saber por dónde empezar.",
    notice: "<b>Aquí no hay favoritas.</b> Solo mostramos lo que ofrece cada escuela. La nota Fraser es solo académica: no mide el ambiente, los programas ni si la escuela va contigo.",
    quiz: { h: "Vibe check ✨", p: "12 toques, 3 minutos y sin registrarte. Al final recibes un PDF con escuelas y programas para explorar. Es una guía, no una sentencia.", btn: "Hacer el vibe check" },
    exploreH: "Filtra a tu manera",
    compararH: "Cara a cara",
    vibesLabel: "Empieza por lo que te llama:",
    preguntasH: "Qué preguntar en las charlas",
    fechasH: "Fechas que no puedes olvidar",
  },
  en: {
    eyebrow: "Mississauga · Grade 9 · September 2027",
    h1a: "Find your high school",
    h1b: "in Mississauga",
    lead: "33 schools, every program, zero fluff. Filter by what you like, compare, and take the vibe check to see where to start.",
    notice: "<b>No favourites here.</b> We only show what each school offers. The Fraser score is academic only: it does not measure atmosphere, programs or whether a school is right for you.",
    quiz: { h: "Vibe check ✨", p: "12 taps, 3 minutes, no sign-up. You get a PDF with schools and programs to explore. It is a guide, not a verdict.", btn: "Take the vibe check" },
    exploreH: "Filter your way",
    compararH: "Head to head",
    vibesLabel: "Start with what you are into:",
    preguntasH: "What to ask at the info sessions",
    fechasH: "Dates you cannot miss",
  },
  fr: {
    eyebrow: "Mississauga · 9e année · septembre 2027",
    h1a: "Trouve ton école secondaire",
    h1b: "à Mississauga",
    lead: "33 écoles, tous les programmes, zéro blabla. Filtre selon ce que tu aimes, compare et fais le vibe check pour savoir par où commencer.",
    notice: "<b>Ici, pas de favoris.</b> On montre seulement ce que chaque école offre. La cote Fraser est uniquement scolaire : elle ne mesure ni le climat, ni les programmes, ni si l'école est faite pour toi.",
    quiz: { h: "Vibe check ✨", p: "12 clics, 3 minutes, sans inscription. Tu obtiens un PDF avec des écoles et des programmes à explorer. C'est un guide, pas un verdict.", btn: "Faire le vibe check" },
    exploreH: "Filtre à ta façon",
    compararH: "Face à face",
    vibesLabel: "Commence par ce qui te branche :",
    preguntasH: "Quoi demander aux séances d'info",
    fechasH: "Les dates à ne pas manquer",
  },
};
