// All site content lives here, in Spanish (es), English (en) and Canadian French (fr).
// To update data (Fraser scores, dates, programs, schools) edit only this file.

const x = (es, en, fr) => ({ es, en, fr });

export const LANGS = ["es", "en", "fr"];

export const FRASER = {
  report: x(
    "Informe Fraser 2025 (año escolar 2024-25)",
    "Fraser Institute 2025 Report Card (2024-25 school year)",
    "Bulletin 2025 de l'Institut Fraser (année scolaire 2024-2025)"
  ),
  url: "https://www.fraserinstitute.org/sites/default/files/2025-11/ontario-secondary-school-rankings-2025_0.pdf",
};

/* ------------------------------------------------------------------ */
/* Program types used as filter tags and chips                         */
/* ------------------------------------------------------------------ */
export const TAGS = {
  ib: x("IB", "IB", "BI"),
  ap: x("AP", "AP", "AP"),
  arts: x("Artes", "Arts", "Arts"),
  stem: x("STEM / SciTech", "STEM / SciTech", "STIM / SciTech"),
  sports: x("Deportes", "Sports", "Sports"),
  fi: x("French Immersion", "French Immersion", "Immersion française"),
  ef: x("Extended French", "Extended French", "Français prolongé"),
  bakery: x("Panadería", "Bakery", "Boulangerie"),
  trades: x("Oficios (Skilled Trades)", "Skilled Trades", "Métiers spécialisés"),
  ibt: x("IBT (negocios y tecnología)", "IBT (business & tech)", "IBT (affaires et technologie)"),
  strings: x("Cuerdas", "Strings", "Cordes"),
  alt: x("Programa alternativo", "Alternative program", "Programme alternatif"),
  shsm: x("SHSM", "SHSM", "MHS (SHSM)"),
};

export const BOARDS = {
  dpcdsb: x("DPCDSB (católico)", "DPCDSB (Catholic)", "DPCDSB (catholique)"),
  peel: x("Peel (público)", "Peel (public)", "Peel (public)"),
  fr: x("Escuela francófona católica", "French-language Catholic", "Catholique de langue française"),
};

/* ------------------------------------------------------------------ */
/* UI strings                                                          */
/* ------------------------------------------------------------------ */
export const UI = {
  es: {
    htmlLang: "es",
    ogLocale: "es_CO",
    title: "Guía de Secundarias en Mississauga | Highschool Navigator",
    metaDesc: "Directorio completo de secundarias católicas, públicas y francófonas en Mississauga (DPCDSB y Peel): IB, AP, Arts, STEM, francés, oficios, fechas de solicitud y nota Fraser, con filtros y comparador.",
    skip: "Saltar al contenido",
    eyebrow: "Mississauga · Ingreso a Grade 9, septiembre 2027",
    h1: "Guía de Secundarias en Mississauga",
    lead: "Todas las secundarias públicas, católicas y francófonas de Mississauga, con sus programas especiales (IB, AP, Arts, STEM, francés y más), cómo se entra y cuándo aplicar. Una guía para conversar en familia con la misma información.",
    factBoards: "Sistemas:",
    factBoardsV: "DPCDSB (católico), Peel (público) y escuela francófona",
    factSchools: "Escuelas:",
    factSchoolsN: (n) => `${n} secundarias de Mississauga`,
    notice: "<b>Esta guía describe la oferta; no recomienda ninguna escuela.</b> Incluye la nota pública del Fraser Institute como referencia de cómo se percibe cada escuela en resultados académicos. No mide programas, ambiente ni ajuste a cada estudiante.",
    scope: "Alcance: secundarias públicas y católicas de Mississauga, más una francófona. Se excluyen las escuelas privadas e independientes (por ejemplo Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). Los programas listados por escuela son los regionales confirmados en las fuentes oficiales; SHSM, Co-op y otros pueden variar, así que confírmalos en la escuela.",
    nav: { capas: "Cómo leer el mapa", explorar: "Explorar y filtrar", escuelas: "Directorio", comparar: "Comparar", regionales: "Programas DPCDSB", peel: "Programas Peel", grados: "Desde qué grado", siglas: "Siglas", fechas: "Fechas", preguntas: "Preguntas" },
    navLabel: "Secciones",
    langLabel: "Idioma",
    themeLabel: "Cambiar tema",

    capasH: "Cómo leer el mapa",
    capasP: "Las opciones no son equivalentes. Hay cuatro niveles distintos y algunos se pueden combinar.",
    layers: [
      { tag: "Nivel 1", h: "Escuela", p: "El edificio donde estudias. Toda escuela ofrece la secundaria regular completa, más algunos extras propios." },
      { tag: "Nivel 2", h: "Programa regional", p: "Un programa especial que vive en ciertas escuelas y recibe estudiantes de toda la zona. Casi siempre se solicita, y el transporte puede ser por cuenta de la familia." },
      { tag: "Nivel 3", h: "Especialización", p: "Una ruta dentro de una escuela, como SHSM o Co-op. Se cursa sobre todo en Grades 11 y 12." },
      { tag: "Nivel 4", h: "Pathway", p: "Hacia dónde conduce todo: universidad, college, apprenticeship o trabajo. Depende de las combinaciones que se elijan." },
    ],

    exploreH: "Explorar y filtrar",
    exploreP: "Los filtros de sistema, tipo de programa y búsqueda afectan al directorio y a los programas. «Empieza en» y «Cómo se entra» afectan solo a las listas de programas.",
    searchLabel: "Buscar",
    searchPh: "Ej. IB, panadería, arte, Port Credit…",
    fSystem: "Sistema", fTag: "Tipo de programa", fStart: "Empieza en (programas)", fEntry: "Cómo se entra (programas)", fSort: "Ordenar escuelas",
    all: "Todos",
    optSystem: { dpcdsb: "DPCDSB (católico)", peel: "Peel (público)", fr: "Francófona católica" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automática (boundary)", apply: "Requiere solicitud o transferencia" },
    optSort: { name: "Nombre (A–Z)", fraser: "Nota Fraser (mayor a menor)" },
    reset: "Limpiar filtros",
    resultCount: (s, p) => `${s} escuela${s === 1 ? "" : "s"} · ${p} programa${p === 1 ? "" : "s"}`,
    noResults: "No hay resultados con esos filtros. Prueba a limpiarlos.",

    escuelasH: "Directorio de secundarias de Mississauga",
    escuelasP: "Todas las escuelas, con sus programas regionales y la nota Fraser. La nota es solo académica y no ordena la lista salvo que elijas ordenarla.",
    lblFocus: "Enfoque:",
    fraserLabel: "Nota Fraser",
    fraserOf: "/ 10",
    fraserRank: (r) => `Puesto ${r} en Ontario`,
    fraserPrev: (p) => `Año anterior: ${p}`,
    fraserNone: "Sin nota Fraser en el informe 2025",
    noPrograms: "Sin programa regional propio. Ofrece la secundaria regular; confirma SHSM y Co-op en la escuela.",
    moreInfo: "Más detalles",
    fraserFoot: "Fuente: ",
    fraserWhatH: "Qué mide (y qué no) la nota Fraser",
    fraserWhat: "Se calcula con resultados de exámenes provinciales: matemáticas de Grade 9 (Academic y Applied), Ontario Secondary School Literacy Test (OSSLT), porcentaje de pruebas por debajo del estándar y de pruebas no rendidas, y brechas entre géneros. No mide artes, deportes, programas técnicos, ambiente, apoyo ni idiomas. El contexto socioeconómico y el tamaño de la muestra influyen, y las notas cambian de un año a otro. Úsala como una referencia más, no como veredicto.",
    compare: "Comparar",
    compareMax: "Máximo 4 escuelas",

    compararH: "Comparador de escuelas",
    compararP: "Elige hasta 4 escuelas de cualquiera de los sistemas para verlas lado a lado.",
    compAdd: "Añadir escuela…",
    compRemove: "Quitar",
    compRows: { board: "Sistema", fraser: "Nota Fraser (2024-25)", rank: "Puesto en Ontario", prev: "Nota año anterior", addr: "Ubicación", programs: "Programas regionales", focus: "Enfoque", distinct: "Distintivo", shsm: "Especializaciones (SHSM)", langs: "Idiomas y otros", entry: "Cómo se entra" },
    compEmpty: "Selecciona al menos dos escuelas para compararlas.",
    compCol: "Escuela",
    none: "—",

    regionalesH: "Programas regionales del DPCDSB",
    regionalesP: "Programas que reciben estudiantes de toda la zona. La escuela sede es donde se cursa; las sedes de Mississauga van marcadas.",
    peelH: "Programas regionales de Peel (RLCP)",
    peelP: "Los Regional Learning Choices Programs (RLCP) de Peel están abiertos a estudiantes que viven en Peel, incluidos los que hoy estudian en el sistema católico. Se solicita por dirección de casa (boundary) y conviene conocerlos antes de descartar nada.",
    host: "Sedes: ",
    inMiss: "Mississauga",
    secondEntry: "Segunda entrada: ",
    peelHowH: "Cómo funciona",
    peelHow: "Entrada en Grade 9 por solicitud en línea. Hay una tarifa de solicitud y una tarifa anual por programa. Se revisan las notas de Grade 7 y, en algunos programas, una audición, evaluación o respuesta escrita. Luego hay un sorteo aleatorio entre quienes cumplen los criterios.",
    peelRuleH: "Reglas importantes",
    peelRule: "Debes aplicar al programa que corresponde a tu boundary según tu dirección. Los estudiantes con visa de estudiante internacional no pueden aplicar (quienes tienen permiso de trabajo o estudio, sí).",
    startsAt: { "9": "Desde Gr 9", "10": "Desde Gr 10", "11": "Desde Gr 11" },
    applyChip: "Solicitud",

    gradosH: "¿Desde qué grado empieza cada cosa?",
    gradosP: "Varias opciones no aparecen hasta Grade 10 u 11. Por eso conviene ver el recorrido completo antes de decidir por Grade 9.",
    tlOption: "Opción",
    tlConfirmed: "Confirmado",
    tlSoft: "Preparación o rango típico, por confirmar con cada escuela",
    timeline: [
      { label: "Secundaria regular", sub: "Cualquier escuela", from: 1, to: 5, txt: "Cursos regulares", soft: false },
      { label: "AP", sub: "Por materia", segs: [[1, 3, "Preparación", true], [3, 5, "Cursos y exámenes AP", false]] },
      { label: "IB", sub: "Diploma de dos años", segs: [[1, 3, "Secuencia previa (MYP o Pre-IB)", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Programas regionales", from: 1, to: 5, txt: "Desde Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grades 10 a 12", soft: false },
      { label: "SHSM", sub: "Especialización", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Experiencia laboral con crédito", from: 3, to: 5, txt: "Senior grades", soft: false },
      { label: "OYAP y Dual Credit", sub: "Oficios y college", from: 3, to: 5, txt: "Normalmente 11–12", soft: true },
    ],

    siglasH: "Siglas en una línea",
    glossary: [
      ["AP", "Cursos de nivel universitario, materia por materia.", "Modular y flexible."],
      ["IB", "Diploma completo y estructurado de dos años.", "Todo el paquete, no materias sueltas."],
      ["MYP / Pre-IB", "Secuencias previas al IB Diploma en Peel: MYP (Glenforest) y Pre-IB (Erindale).", ""],
      ["SHSM", "Specialist High Skills Major: una especialización de sector (ICT, Business, Hospitality, Transportation, Arts y otros) con cursos, certificaciones y Co-op.", "Se cursa en Gr 11–12."],
      ["Co-op", "Estudiar y trabajar en una empresa real, y recibir créditos por ello.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: empezar un aprendizaje de oficio mientras se termina la secundaria.", ""],
      ["Dual Credit", "Cursos de college que cuentan también para el diploma de secundaria.", ""],
      ["RLCP", "Regional Learning Choices Programs: los programas regionales de Peel.", ""],
      ["Feeder", "La secundaria que corresponde por defecto a una escuela primaria.", ""],
      ["Boundary", "El área de residencia que decide a qué escuela se asiste sin solicitar nada.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: prueba provincial de lectoescritura, base de parte de la nota Fraser.", ""],
    ],

    fechasH: "Fechas para el calendario",
    fechasP: "Estas son las fechas que ya se conocen. Confírmalas siempre en el sitio de cada board o escuela.",
    dates: [
      { when: "Oct–nov 2026", b: "Charlas y open houses del DPCDSB", p: "para Grade 8. Cada escuela publica su propia fecha en su sitio." },
      { when: "6 oct 2026", b: "Noche informativa virtual de Peel", p: "para familias de estudiantes afrodescendientes (18:00–19:00), sobre RLCP, Explore High Skills y Skilled Trades." },
      { when: "3–24 nov 2026", b: "Solicitudes RLCP de Peel", p: "para el año escolar 2027-28 (confirmado en el sitio de Peel)." },
      { when: "Por confirmar", b: "Solicitudes de programas regionales DPCDSB", p: "(AP, IB, Arts, Sports, STEM, Bakery). Se confirma en cada charla; STEAM de St. Joan of Arc abre en octubre, según el board." },
    ],

    preguntasH: "Preguntas para llevar a las charlas",
    preguntasP: "Para escuchar con criterio y no solo la presentación de cada escuela.",
    questions: [
      "¿Qué tiene esta escuela que no tenga la de al lado?",
      "¿Qué programas requieren solicitud y hasta cuándo?",
      "¿Qué se puede tomar desde Grade 9 y qué solo en Grades 11–12?",
      "¿Qué notas o requisitos piden, y hay audición o portafolio?",
      "¿Hay transporte, o lo cubre la familia? ¿Qué costos extra hay?",
      "¿Qué certificaciones se obtienen y qué Co-op existe?",
      "¿Con qué universidades, colleges o industria trabajan?",
      "¿Se pueden combinar programas, por ejemplo IB con Co-op?",
    ],

    pendingH: "Lo que falta por confirmar",
    pendingP: "Datos que no se pudieron verificar y que conviene revisar en cada charla o sitio de la escuela.",
    pending: [
      "Direcciones exactas de varias escuelas y la distancia desde casa",
      "Lista completa de SHSM por escuela (el DPCDSB publica una matriz 2026-27 con 57 programas)",
      "Costos, transporte y fechas de solicitud de los programas regionales del DPCDSB",
      "Requisitos académicos y audiciones de Arts, Sports y STEM",
      "Las escuelas de Peel sin RLCP también ofrecen Co-op, SHSM y Explore High Skills; verifícalo en cada sitio",
      "La nota Fraser se actualiza cada otoño: revisa el informe más reciente",
    ],
    sourcesH: "Fuentes consultadas",
    disclaimer: "Sitio informativo independiente, sin afiliación con el DPCDSB, Peel ni el Fraser Institute. La información puede cambiar: verifica siempre en las fuentes oficiales.",
    backTop: "Volver arriba",
  },

  en: {
    htmlLang: "en",
    ogLocale: "en_CA",
    title: "Mississauga High School Guide | Highschool Navigator",
    metaDesc: "Complete directory of Catholic, public and French-language high schools in Mississauga (DPCDSB and Peel): IB, AP, Arts, STEM, French, trades, application dates and Fraser scores, with filters and a comparison tool.",
    skip: "Skip to content",
    eyebrow: "Mississauga · Grade 9 entry, September 2027",
    h1: "Mississauga High School Guide",
    lead: "Every public, Catholic and French-language high school in Mississauga, with its special programs (IB, AP, Arts, STEM, French and more), how to get in and when to apply. A guide so the family can talk with the same information.",
    factBoards: "Boards:",
    factBoardsV: "DPCDSB (Catholic), Peel (public) and a French-language school",
    factSchools: "Schools:",
    factSchoolsN: (n) => `${n} high schools in Mississauga`,
    notice: "<b>This guide describes what is offered; it does not recommend any school.</b> It includes the Fraser Institute's public score as a reference for how each school is perceived on academic results. It does not measure programs, atmosphere or fit for each student.",
    scope: "Scope: public and Catholic high schools in Mississauga, plus one French-language school. Private and independent schools are excluded (for example Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). The programs listed per school are the regional programs confirmed in official sources; SHSM, Co-op and others may vary, so confirm them with the school.",
    nav: { capas: "How to read the map", explorar: "Explore & filter", escuelas: "Directory", comparar: "Compare", regionales: "DPCDSB programs", peel: "Peel programs", grados: "Which grade", siglas: "Glossary", fechas: "Dates", preguntas: "Questions" },
    navLabel: "Sections",
    langLabel: "Language",
    themeLabel: "Toggle theme",

    capasH: "How to read the map",
    capasP: "The options are not equivalent. There are four different levels and some can be combined.",
    layers: [
      { tag: "Level 1", h: "School", p: "The building where you study. Every school offers the full regular high school program, plus some extras of its own." },
      { tag: "Level 2", h: "Regional program", p: "A special program housed in certain schools that takes students from the whole area. It almost always requires an application, and transportation may be the family's responsibility." },
      { tag: "Level 3", h: "Specialization", p: "A pathway inside a school, such as SHSM or Co-op. Mostly taken in Grades 11 and 12." },
      { tag: "Level 4", h: "Pathway", p: "Where it all leads: university, college, apprenticeship or work. It depends on the combinations chosen." },
    ],

    exploreH: "Explore & filter",
    exploreP: "The board, program type and search filters affect the directory and the programs. “Starts in” and “How to get in” only affect the program lists.",
    searchLabel: "Search",
    searchPh: "E.g. IB, bakery, arts, Port Credit…",
    fSystem: "Board", fTag: "Program type", fStart: "Starts in (programs)", fEntry: "How to get in (programs)", fSort: "Sort schools",
    all: "All",
    optSystem: { dpcdsb: "DPCDSB (Catholic)", peel: "Peel (public)", fr: "French-language Catholic" },
    optStart: { "9": "Grade 9", "10": "Grade 10", "11": "Grade 11" },
    optEntry: { auto: "Automatic (boundary)", apply: "Application or transfer required" },
    optSort: { name: "Name (A–Z)", fraser: "Fraser score (high to low)" },
    reset: "Clear filters",
    resultCount: (s, p) => `${s} school${s === 1 ? "" : "s"} · ${p} program${p === 1 ? "" : "s"}`,
    noResults: "No results for those filters. Try clearing them.",

    escuelasH: "Directory of Mississauga high schools",
    escuelasP: "Every school, with its regional programs and Fraser score. The score is academic only and does not order the list unless you choose to sort by it.",
    lblFocus: "Focus:",
    fraserLabel: "Fraser score",
    fraserOf: "/ 10",
    fraserRank: (r) => `Rank ${r} in Ontario`,
    fraserPrev: (p) => `Previous year: ${p}`,
    fraserNone: "No Fraser score in the 2025 report",
    noPrograms: "No regional program of its own. Offers the regular high school; confirm SHSM and Co-op with the school.",
    moreInfo: "More details",
    fraserFoot: "Source: ",
    fraserWhatH: "What the Fraser score measures (and what it does not)",
    fraserWhat: "It is calculated from provincial test results: Grade 9 math (Academic and Applied), the Ontario Secondary School Literacy Test (OSSLT), the share of tests below standard and of tests not written, and gender gaps. It does not measure arts, sports, technical programs, atmosphere, support or languages. Socioeconomic context and sample size matter, and scores change from year to year. Use it as one reference, not a verdict.",
    compare: "Compare",
    compareMax: "Maximum 4 schools",

    compararH: "School comparison",
    compararP: "Pick up to 4 schools from any board to see them side by side.",
    compAdd: "Add a school…",
    compRemove: "Remove",
    compRows: { board: "Board", fraser: "Fraser score (2024-25)", rank: "Rank in Ontario", prev: "Previous year score", addr: "Location", programs: "Regional programs", focus: "Focus", distinct: "What stands out", shsm: "Specializations (SHSM)", langs: "Languages and other", entry: "How to get in" },
    compEmpty: "Select at least two schools to compare them.",
    compCol: "School",
    none: "—",

    regionalesH: "DPCDSB regional programs",
    regionalesP: "Programs that take students from the whole area. The host school is where the program is taken; Mississauga hosts are marked.",
    peelH: "Peel regional programs (RLCP)",
    peelP: "Peel's Regional Learning Choices Programs (RLCP) are open to students who live in Peel, including those currently in the Catholic system. You apply according to your home boundary, and it is worth knowing them before ruling anything out.",
    host: "Hosts: ",
    inMiss: "Mississauga",
    secondEntry: "Second entry: ",
    peelHowH: "How it works",
    peelHow: "Grade 9 entry by online application. There is an application fee and an annual per-program fee. Grade 7 marks are reviewed and, for some programs, an audition, assessment or written response. Then a random selection is held among applicants who meet the criteria.",
    peelRuleH: "Important rules",
    peelRule: "You must apply to the program that matches your boundary by home address. Students on an international student visa are not eligible (those with work or study permits may apply).",
    startsAt: { "9": "From Gr 9", "10": "From Gr 10", "11": "From Gr 11" },
    applyChip: "Application",

    gradosH: "From which grade does each thing start?",
    gradosP: "Several options do not appear until Grade 10 or 11. That is why it helps to see the whole path before deciding on Grade 9.",
    tlOption: "Option",
    tlConfirmed: "Confirmed",
    tlSoft: "Preparation or typical range, to be confirmed with each school",
    timeline: [
      { label: "Regular high school", sub: "Any school", from: 1, to: 5, txt: "Regular courses", soft: false },
      { label: "AP", sub: "Subject by subject", segs: [[1, 3, "Preparation", true], [3, 5, "AP courses and exams", false]] },
      { label: "IB", sub: "Two-year diploma", segs: [[1, 3, "Prior sequence (MYP or Pre-IB)", true], [3, 5, "IB Diploma", false]] },
      { label: "STEAM, Arts, Sports", sub: "Regional programs", from: 1, to: 5, txt: "From Grade 9", soft: false },
      { label: "Bakery School", sub: "Goetz", from: 2, to: 5, txt: "Grades 10 to 12", soft: false },
      { label: "SHSM", sub: "Specialization", from: 3, to: 5, txt: "Grades 11–12", soft: false },
      { label: "Co-op", sub: "Work experience for credit", from: 3, to: 5, txt: "Senior grades", soft: false },
      { label: "OYAP & Dual Credit", sub: "Trades and college", from: 3, to: 5, txt: "Usually 11–12", soft: true },
    ],

    siglasH: "Acronyms in one line",
    glossary: [
      ["AP", "University-level courses, subject by subject.", "Modular and flexible."],
      ["IB", "A complete, structured two-year diploma.", "The whole package, not single subjects."],
      ["MYP / Pre-IB", "Sequences leading to the IB Diploma in Peel: MYP (Glenforest) and Pre-IB (Erindale).", ""],
      ["SHSM", "Specialist High Skills Major: a sector specialization (ICT, Business, Hospitality, Transportation, Arts and others) with courses, certifications and Co-op.", "Taken in Gr 11–12."],
      ["Co-op", "Study and work at a real company, and earn credits for it.", ""],
      ["OYAP", "Ontario Youth Apprenticeship Program: start a trade apprenticeship while finishing high school.", ""],
      ["Dual Credit", "College courses that also count toward the high school diploma.", ""],
      ["RLCP", "Regional Learning Choices Programs: Peel's regional programs.", ""],
      ["Feeder", "The high school that is the default for a given elementary school.", ""],
      ["Boundary", "The residence area that decides which school you attend without applying.", ""],
      ["OSSLT", "Ontario Secondary School Literacy Test: the provincial literacy test, part of the basis of the Fraser score.", ""],
    ],

    fechasH: "Dates for your calendar",
    fechasP: "These are the dates already known. Always confirm them on each board's or school's website.",
    dates: [
      { when: "Oct–Nov 2026", b: "DPCDSB talks and open houses", p: "for Grade 8. Each school publishes its own date on its website." },
      { when: "Oct 6, 2026", b: "Peel virtual information night", p: "for families of African, Black and Afro-Caribbean students (6–7 p.m.), on RLCP, Explore High Skills and Skilled Trades." },
      { when: "Nov 3–24, 2026", b: "Peel RLCP applications", p: "for the 2027-28 school year (confirmed on Peel's website)." },
      { when: "To be confirmed", b: "DPCDSB regional program applications", p: "(AP, IB, Arts, Sports, STEM, Bakery). Confirmed at each talk; St. Joan of Arc STEAM opens in October, per the board." },
    ],

    preguntasH: "Questions to bring to the info sessions",
    preguntasP: "To listen critically and not just to each school's presentation.",
    questions: [
      "What does this school have that the one next door doesn't?",
      "Which programs require an application, and by when?",
      "What can be taken from Grade 9 and what only in Grades 11–12?",
      "What grades or requirements are needed, and is there an audition or portfolio?",
      "Is there transportation, or does the family cover it? What extra costs are there?",
      "What certifications can be earned and what Co-op exists?",
      "Which universities, colleges or industries do they work with?",
      "Can programs be combined, for example IB with Co-op?",
    ],

    pendingH: "What is still to be confirmed",
    pendingP: "Data that could not be verified and that is worth checking at each info session or school website.",
    pending: [
      "Exact addresses of several schools and the distance from home",
      "Each school's complete SHSM list (DPCDSB publishes a 2026-27 matrix of 57 programs)",
      "Costs, transportation and application dates for DPCDSB regional programs",
      "Academic requirements and auditions for Arts, Sports and STEM",
      "Peel schools without an RLCP also offer Co-op, SHSM and Explore High Skills; verify on each website",
      "Fraser scores are updated every autumn: check the latest report",
    ],
    sourcesH: "Sources consulted",
    disclaimer: "Independent informational site, not affiliated with DPCDSB, Peel or the Fraser Institute. Information may change: always verify with official sources.",
    backTop: "Back to top",
  },

  fr: {
    htmlLang: "fr-CA",
    ogLocale: "fr_CA",
    title: "Guide des écoles secondaires de Mississauga | Highschool Navigator",
    metaDesc: "Répertoire complet des écoles secondaires catholiques, publiques et de langue française de Mississauga (DPCDSB et Peel) : BI, AP, arts, STIM, français, métiers, dates d'inscription et cote Fraser, avec filtres et comparateur.",
    skip: "Passer au contenu",
    eyebrow: "Mississauga · Entrée en 9e année, septembre 2027",
    h1: "Guide des écoles secondaires de Mississauga",
    lead: "Toutes les écoles secondaires publiques, catholiques et de langue française de Mississauga, avec leurs programmes spéciaux (BI, AP, arts, STIM, français et plus), la façon d'y entrer et le moment de présenter une demande. Un guide pour en discuter en famille avec la même information.",
    factBoards: "Conseils scolaires :",
    factBoardsV: "DPCDSB (catholique), Peel (public) et une école de langue française",
    factSchools: "Écoles :",
    factSchoolsN: (n) => `${n} écoles secondaires à Mississauga`,
    notice: "<b>Ce guide décrit l'offre; il ne recommande aucune école.</b> Il inclut la cote publique de l'Institut Fraser comme repère de la perception de chaque école sur les résultats scolaires. Elle ne mesure ni les programmes, ni le climat, ni l'adéquation à chaque élève.",
    scope: "Portée : écoles secondaires publiques et catholiques de Mississauga, plus une école de langue française. Les écoles privées et indépendantes sont exclues (par exemple Olive Grove, ISNA, The Woodlands, Al-Manarat, Safa & Marwa). Les programmes indiqués pour chaque école sont les programmes régionaux confirmés dans les sources officielles; les MHS (SHSM), l'éducation coopérative et autres peuvent varier : confirmez-les auprès de l'école.",
    nav: { capas: "Comment lire la carte", explorar: "Explorer et filtrer", escuelas: "Répertoire", comparar: "Comparer", regionales: "Programmes DPCDSB", peel: "Programmes Peel", grados: "À partir de quelle année", siglas: "Sigles", fechas: "Dates", preguntas: "Questions" },
    navLabel: "Sections",
    langLabel: "Langue",
    themeLabel: "Changer de thème",

    capasH: "Comment lire la carte",
    capasP: "Les options ne sont pas équivalentes. Il y a quatre niveaux distincts et certains peuvent se combiner.",
    layers: [
      { tag: "Niveau 1", h: "École", p: "L'établissement où vous étudiez. Toute école offre le programme secondaire régulier complet, plus quelques atouts qui lui sont propres." },
      { tag: "Niveau 2", h: "Programme régional", p: "Un programme spécial hébergé dans certaines écoles, qui accueille des élèves de toute la région. Il faut presque toujours présenter une demande, et le transport peut être à la charge de la famille." },
      { tag: "Niveau 3", h: "Spécialisation", p: "Un parcours au sein d'une école, comme une MHS (SHSM) ou l'éducation coopérative. Il se suit surtout en 11e et 12e année." },
      { tag: "Niveau 4", h: "Parcours", p: "Là où tout mène : université, collège, apprentissage ou travail. Cela dépend des combinaisons choisies." },
    ],

    exploreH: "Explorer et filtrer",
    exploreP: "Les filtres de conseil scolaire, de type de programme et la recherche touchent le répertoire et les programmes. « Commence en » et « Comment y entrer » ne touchent que les listes de programmes.",
    searchLabel: "Rechercher",
    searchPh: "Ex. BI, boulangerie, arts, Port Credit…",
    fSystem: "Conseil scolaire", fTag: "Type de programme", fStart: "Commence en (programmes)", fEntry: "Comment y entrer (programmes)", fSort: "Trier les écoles",
    all: "Tous",
    optSystem: { dpcdsb: "DPCDSB (catholique)", peel: "Peel (public)", fr: "Catholique de langue française" },
    optStart: { "9": "9e année", "10": "10e année", "11": "11e année" },
    optEntry: { auto: "Automatique (secteur)", apply: "Demande ou transfert requis" },
    optSort: { name: "Nom (A–Z)", fraser: "Cote Fraser (de la plus élevée à la plus basse)" },
    reset: "Réinitialiser les filtres",
    resultCount: (s, p) => `${s} école${s === 1 ? "" : "s"} · ${p} programme${p === 1 ? "" : "s"}`,
    noResults: "Aucun résultat avec ces filtres. Essayez de les réinitialiser.",

    escuelasH: "Répertoire des écoles secondaires de Mississauga",
    escuelasP: "Toutes les écoles, avec leurs programmes régionaux et leur cote Fraser. La cote est uniquement scolaire et ne classe pas la liste, sauf si vous choisissez de trier par cote.",
    lblFocus: "Orientation :",
    fraserLabel: "Cote Fraser",
    fraserOf: "/ 10",
    fraserRank: (r) => `${r}e rang en Ontario`,
    fraserPrev: (p) => `Année précédente : ${p}`,
    fraserNone: "Aucune cote Fraser dans le bulletin 2025",
    noPrograms: "Aucun programme régional propre. Offre le secondaire régulier; confirmez les MHS et l'éducation coopérative auprès de l'école.",
    moreInfo: "Plus de détails",
    fraserFoot: "Source : ",
    fraserWhatH: "Ce que mesure (et ne mesure pas) la cote Fraser",
    fraserWhat: "Elle est calculée à partir des résultats aux tests provinciaux : mathématiques de 9e année (théorique et appliqué), Test provincial de compétences linguistiques (TPCL, OSSLT), proportion de tests sous la norme et de tests non passés, et écarts entre les sexes. Elle ne mesure ni les arts, ni les sports, ni les programmes techniques, ni le climat, ni le soutien, ni les langues. Le contexte socioéconomique et la taille de l'échantillon comptent, et les cotes changent d'une année à l'autre. Utilisez-la comme un repère parmi d'autres, non comme un verdict.",
    compare: "Comparer",
    compareMax: "Maximum 4 écoles",

    compararH: "Comparateur d'écoles",
    compararP: "Choisissez jusqu'à 4 écoles de n'importe quel conseil pour les voir côte à côte.",
    compAdd: "Ajouter une école…",
    compRemove: "Retirer",
    compRows: { board: "Conseil scolaire", fraser: "Cote Fraser (2024-2025)", rank: "Rang en Ontario", prev: "Cote de l'année précédente", addr: "Emplacement", programs: "Programmes régionaux", focus: "Orientation", distinct: "Particularité", shsm: "Spécialisations (MHS)", langs: "Langues et autres", entry: "Comment y entrer" },
    compEmpty: "Sélectionnez au moins deux écoles pour les comparer.",
    compCol: "École",
    none: "—",

    regionalesH: "Programmes régionaux du DPCDSB",
    regionalesP: "Programmes qui accueillent des élèves de toute la région. L'école hôte est celle où l'on suit le programme; les sites de Mississauga sont indiqués.",
    peelH: "Programmes régionaux de Peel (RLCP)",
    peelP: "Les Regional Learning Choices Programs (RLCP) de Peel sont ouverts aux élèves qui habitent à Peel, y compris ceux qui fréquentent actuellement le système catholique. On présente sa demande selon son secteur (adresse du domicile); il vaut la peine de les connaître avant d'écarter quoi que ce soit.",
    host: "Sites : ",
    inMiss: "Mississauga",
    secondEntry: "Deuxième point d'entrée : ",
    peelHowH: "Comment ça fonctionne",
    peelHow: "Entrée en 9e année par demande en ligne. Des frais de demande et des frais annuels par programme s'appliquent. On examine les notes de 7e année et, pour certains programmes, une audition, une évaluation ou une réponse écrite. Un tirage au sort a ensuite lieu parmi les candidats qui répondent aux critères.",
    peelRuleH: "Règles importantes",
    peelRule: "Vous devez demander le programme qui correspond à votre secteur selon votre adresse. Les élèves titulaires d'un visa d'étudiant international ne sont pas admissibles (les titulaires d'un permis de travail ou d'études peuvent postuler).",
    startsAt: { "9": "Dès la 9e", "10": "Dès la 10e", "11": "Dès la 11e" },
    applyChip: "Demande",

    gradosH: "À partir de quelle année chaque option commence-t-elle?",
    gradosP: "Plusieurs options n'apparaissent qu'en 10e ou en 11e année. Il vaut donc la peine de voir tout le parcours avant de décider pour la 9e année.",
    tlOption: "Option",
    tlConfirmed: "Confirmé",
    tlSoft: "Préparation ou plage habituelle, à confirmer auprès de chaque école",
    timeline: [
      { label: "Secondaire régulier", sub: "N'importe quelle école", from: 1, to: 5, txt: "Cours réguliers", soft: false },
      { label: "AP", sub: "Par matière", segs: [[1, 3, "Préparation", true], [3, 5, "Cours et examens AP", false]] },
      { label: "BI", sub: "Diplôme de deux ans", segs: [[1, 3, "Séquence préalable (PEI ou pré-BI)", true], [3, 5, "Diplôme du BI", false]] },
      { label: "STEAM, arts, sports", sub: "Programmes régionaux", from: 1, to: 5, txt: "Dès la 9e année", soft: false },
      { label: "École de boulangerie", sub: "Goetz", from: 2, to: 5, txt: "10e à 12e année", soft: false },
      { label: "MHS (SHSM)", sub: "Spécialisation", from: 3, to: 5, txt: "11e–12e année", soft: false },
      { label: "Éducation coopérative", sub: "Expérience de travail avec crédit", from: 3, to: 5, txt: "Années supérieures", soft: false },
      { label: "PAJO et double reconnaissance", sub: "Métiers et collège", from: 3, to: 5, txt: "Habituellement 11e–12e", soft: true },
    ],

    siglasH: "Les sigles en une ligne",
    glossary: [
      ["AP", "Cours de niveau universitaire, matière par matière.", "Modulaire et flexible."],
      ["BI", "Diplôme complet et structuré de deux ans (Baccalauréat international).", "Tout l'ensemble, pas des matières isolées."],
      ["PEI / pré-BI", "Séquences menant au diplôme du BI à Peel : PEI (Glenforest) et pré-BI (Erindale).", ""],
      ["MHS (SHSM)", "Majeure haute spécialisation : une spécialisation sectorielle (TIC, affaires, tourisme et accueil, transport, arts et autres) avec cours, certifications et éducation coopérative.", "Suivie en 11e–12e année."],
      ["Éducation coopérative", "Étudier et travailler dans une vraie entreprise, et obtenir des crédits.", ""],
      ["PAJO (OYAP)", "Programme d'apprentissage pour les jeunes de l'Ontario : commencer un apprentissage de métier tout en terminant le secondaire.", ""],
      ["Double reconnaissance", "Cours collégiaux qui comptent aussi pour le diplôme d'études secondaires.", ""],
      ["RLCP", "Regional Learning Choices Programs : les programmes régionaux de Peel.", ""],
      ["École d'accueil (feeder)", "L'école secondaire attribuée par défaut à une école élémentaire.", ""],
      ["Secteur (boundary)", "La zone de résidence qui détermine l'école fréquentée sans avoir à présenter de demande.", ""],
      ["TPCL (OSSLT)", "Test provincial de compétences linguistiques : sert en partie de base à la cote Fraser.", ""],
    ],

    fechasH: "Dates à mettre à l'agenda",
    fechasP: "Voici les dates déjà connues. Confirmez-les toujours sur le site de chaque conseil ou école.",
    dates: [
      { when: "Oct.–nov. 2026", b: "Présentations et portes ouvertes du DPCDSB", p: "pour la 8e année. Chaque école publie sa propre date sur son site." },
      { when: "6 oct. 2026", b: "Soirée d'information virtuelle de Peel", p: "pour les familles d'élèves noirs et afro-caribéens (18 h–19 h), sur les RLCP, Explore High Skills et les métiers spécialisés." },
      { when: "3–24 nov. 2026", b: "Demandes RLCP de Peel", p: "pour l'année scolaire 2027-2028 (confirmé sur le site de Peel)." },
      { when: "À confirmer", b: "Demandes des programmes régionaux du DPCDSB", p: "(AP, BI, arts, sports, STIM, boulangerie). Confirmées à chaque présentation; le programme STEAM de St. Joan of Arc ouvre en octobre, selon le conseil." },
    ],

    preguntasH: "Questions à apporter aux séances d'information",
    preguntasP: "Pour écouter avec un esprit critique et pas seulement la présentation de chaque école.",
    questions: [
      "Qu'a cette école que l'école voisine n'a pas?",
      "Quels programmes exigent une demande, et jusqu'à quand?",
      "Que peut-on suivre dès la 9e année et que seulement en 11e–12e?",
      "Quelles notes ou exigences demande-t-on, et y a-t-il une audition ou un portfolio?",
      "Y a-t-il du transport, ou est-ce la famille qui l'assume? Quels frais supplémentaires y a-t-il?",
      "Quelles certifications peut-on obtenir et quelle éducation coopérative existe?",
      "Avec quelles universités, quels collèges ou quelles industries travaillent-ils?",
      "Peut-on combiner des programmes, par exemple le BI avec l'éducation coopérative?",
    ],

    pendingH: "Ce qu'il reste à confirmer",
    pendingP: "Données qui n'ont pas pu être vérifiées et qu'il vaut la peine de valider à chaque séance d'information ou sur le site de l'école.",
    pending: [
      "Adresses exactes de plusieurs écoles et distance depuis la maison",
      "Liste complète des MHS de chaque école (le DPCDSB publie une matrice 2026-2027 de 57 programmes)",
      "Coûts, transport et dates de demande des programmes régionaux du DPCDSB",
      "Exigences scolaires et auditions pour les arts, les sports et les STIM",
      "Les écoles de Peel sans RLCP offrent aussi l'éducation coopérative, des MHS et Explore High Skills; à vérifier sur chaque site",
      "La cote Fraser est mise à jour chaque automne : consultez le bulletin le plus récent",
    ],
    sourcesH: "Sources consultées",
    disclaimer: "Site d'information indépendant, sans lien avec le DPCDSB, Peel ni l'Institut Fraser. L'information peut changer : vérifiez toujours auprès des sources officielles.",
    backTop: "Retour en haut",
  },
};

export const SOURCES = [
  ["DPCDSB, Regional Secondary Programs 2025-26", "https://www.dpcdsb.org/download/527393"],
  ["DPCDSB, Regional Advanced Placement", "https://www.dpcdsb.org/programs-services/secondary/advanced-placement"],
  ["DPCDSB, International Baccalaureate", "https://www.dpcdsb.org/programs-services/secondary/international-baccalaureate"],
  ["DPCDSB, Regional Arts Program", "https://www.dpcdsb.org/programs-services/secondary/regional-arts-program"],
  ["DPCDSB, Regional STEM Program", "https://www.dpcdsb.org/programs-services/secondary/regional-stem-program"],
  ["DPCDSB, Regional Sports Program", "https://www.dpcdsb.org/programs-services/secondary/regional-sports-program"],
  ["DPCDSB, Extended French and French Immersion", "https://www.dpcdsb.org/programs-services/secondary/french-immersion-program"],
  ["DPCDSB, Specialist High Skills Major", "https://www.dpcdsb.org/programs-services/secondary/specialist-high-skills-major"],
  ["DPCDSB, Canada Bakery School 2026-27", "https://www.dpcdsb.org/dpcdsb/news/post/dpcdsb-now-accepting-applications-for-canada-bakery-school-regional-program-2026-27"],
  ["Peel, Secondary Regional Learning Choices Programs", "https://www.peelschools.org/secondary-regional-learning-choice-programs"],
  ["Peel, IB", "https://www.peelschools.org/ib"],
  ["Peel, Arts", "https://www.peelschools.org/arts"],
  ["Peel, SciTech", "https://www.peelschools.org/scitech"],
  ["Peel, Strings", "https://www.peelschools.org/strings"],
  ["Peel, International Business and Technology", "https://www.peelschools.org/international-business-and-technology"],
  ["Peel, Regional Skilled Trades", "https://www.peelschools.org/regional-skilled-trades-program"],
  ["Fraser Institute, Report Card on Ontario's Secondary Schools 2025", FRASER.url],
];

/* ------------------------------------------------------------------ */
/* Schools. Fraser data: 2025 report, 2024-25 school year.             */
/* fraser: { score, rank, prev } ; prev = previous-year score or null. */
/* progs: verified regional programs (tag + optional note).            */
/* ------------------------------------------------------------------ */
const P = (k, n) => ({ k, n });
const F = (score, rank, prev) => ({ score, rank, prev });

export const SCHOOLS = [
  // ---------------- DPCDSB (Catholic) ----------------
  { id: "goetz", board: "dpcdsb", name: "Father Michael Goetz", addr: "330 Central Pkwy W", fraser: F(4.0, 654, 5.2),
    progs: [P("bakery", x("Regional Bakery School, Grades 10–12, primer año 2026-27", "Regional Bakery School, Grades 10–12, first year 2026-27", "École régionale de boulangerie, 10e–12e année, première année 2026-2027")), P("shsm", x("ICT y Arts & Culture", "ICT and Arts & Culture", "TIC et arts et culture"))],
    focus: x("secundaria completa con tecnología y un programa técnico de panadería. No es una escuela «de bakery».", "full high school with technology and a technical bakery program. It is not a “bakery school” overall.", "école secondaire complète avec technologie et un programme technique de boulangerie. Ce n'est pas une « école de boulangerie » en soi."),
    kv: {
      distinct: x("Regional Bakery School: cuatro cursos de panadería en Grades 10 a 12, con Co-op u OYAP.", "Regional Bakery School: four bakery courses in Grades 10 to 12, with Co-op or OYAP.", "École régionale de boulangerie : quatre cours de boulangerie de la 10e à la 12e année, avec éducation coopérative ou PAJO."),
      shsm: x("SHSM en Information & Communications Technology (ICT) y en Arts & Culture", "SHSM in Information & Communications Technology (ICT) and in Arts & Culture", "MHS en technologies de l'information et des communications (TIC) et en arts et culture"),
      langs: x("También Computer Science y Co-op", "Also Computer Science and Co-op", "Aussi informatique et éducation coopérative"),
      entry: x("Regular: automática si vives en su boundary. Bakery: requiere solicitud.", "Regular: automatic if you live in its boundary. Bakery: application required.", "Régulier : automatique si vous habitez dans son secteur. Boulangerie : demande requise."),
    } },
  { id: "pocock", board: "dpcdsb", name: "Philip Pocock", addr: "4555 Tomken Rd", fraser: F(5.9, 401, 7.0),
    progs: [P("fi"), P("ef"), P("shsm", x("Arts & Culture, Hospitality & Tourism y Transportation", "Arts & Culture, Hospitality & Tourism and Transportation", "Arts et culture, tourisme et accueil et transport"))],
    focus: x("combinación visible de idiomas, artes, hospitality y áreas técnicas.", "a visible mix of languages, arts, hospitality and technical areas.", "combinaison visible de langues, d'arts, d'accueil et de domaines techniques."),
    kv: {
      distinct: x("SHSM de Transportation, ligado a áreas técnicas", "Transportation SHSM, tied to technical fields", "MHS en transport, lié aux domaines techniques"),
      shsm: x("SHSM en Arts & Culture, Hospitality & Tourism y Transportation", "SHSM in Arts & Culture, Hospitality & Tourism and Transportation", "MHS en arts et culture, tourisme et accueil, et transport"),
      langs: x("French Immersion y Extended French", "French Immersion and Extended French", "Immersion française et français prolongé"),
      entry: x("Regular: transferencia si vives fuera de su boundary. Los programas de francés tienen su propio proceso.", "Regular: transfer if you live outside its boundary. French programs have their own process.", "Régulier : transfert si vous habitez hors de son secteur. Les programmes de français ont leur propre processus."),
    } },
  { id: "cabot", board: "dpcdsb", name: "John Cabot", addr: "Mississauga East", fraser: F(4.4, 620, 5.8),
    progs: [P("shsm", x("ICT", "ICT", "TIC"))],
    focus: x("negocios, tecnología y medios digitales, con ruta clara al emprendimiento.", "business, technology and digital media, with a clear path to entrepreneurship.", "affaires, technologie et médias numériques, avec une voie claire vers l'entrepreneuriat."),
    kv: {
      distinct: x("Mezcla tecnología con creatividad y negocios. Incluye animación, cine y fotografía, no solo programación.", "Mixes technology with creativity and business. Includes animation, film and photography, not just programming.", "Allie technologie, créativité et affaires. Comprend l'animation, le cinéma et la photographie, pas seulement la programmation."),
      shsm: x("SHSM en ICT", "SHSM in ICT", "MHS en TIC"),
      langs: x("Business, ICT, Media, producción digital y Co-op", "Business, ICT, Media, digital production and Co-op", "Affaires, TIC, médias, production numérique et éducation coopérative"),
      entry: x("Transferencia si vives fuera de su boundary", "Transfer if you live outside its boundary", "Transfert si vous habitez hors de son secteur"),
    } },
  { id: "sfx", board: "dpcdsb", name: "St. Francis Xavier", addr: "Mississauga East", fraser: F(8.0, 86, 8.0),
    progs: [P("ib", x("IB Diploma (sede regional)", "IB Diploma (regional host)", "Diplôme du BI (site régional)")), P("shsm", x("Varios SHSM", "Several SHSMs", "Plusieurs MHS"))],
    focus: x("ruta académica alternativa con International Baccalaureate y una oferta amplia.", "an alternative academic pathway with the International Baccalaureate and a broad offering.", "parcours scolaire alternatif avec le Baccalauréat international et une offre étendue."),
    kv: {
      distinct: x("IB Diploma Programme: programa integrado y estructurado, distinto de la secundaria regular", "IB Diploma Programme: an integrated, structured program, different from regular high school", "Programme du diplôme du BI : programme intégré et structuré, distinct du secondaire régulier"),
      shsm: x("Varios SHSM", "Several SHSMs", "Plusieurs MHS"),
      langs: x("—", "—", "—"),
      entry: x("Regular: transferencia. IB: solicitud, según el boundary regional de IB.", "Regular: transfer. IB: application, according to the regional IB boundary.", "Régulier : transfert. BI : demande, selon le secteur régional du BI."),
    } },
  { id: "loyola", board: "dpcdsb", name: "Loyola", addr: "4010 Sladeview Cres", fraser: F(7.0, 220, 7.2), progs: [P("fi"), P("ef")] },
  { id: "aloysius", board: "dpcdsb", name: "St. Aloysius Gonzaga", addr: "2800 Erin Centre Blvd", fraser: F(7.7, 119, 7.6), progs: [P("ef")] },
  { id: "joseph", board: "dpcdsb", name: "St. Joseph", addr: "Mississauga", fraser: F(8.2, 65, 7.6), progs: [P("ap", x("Sede AP para Mississauga", "AP host for Mississauga", "Site AP pour Mississauga"))] },
  { id: "paul", board: "dpcdsb", name: "St. Paul", addr: "Mississauga", fraser: F(7.7, 119, 7.6), progs: [P("ib", x("IB Diploma (sede regional)", "IB Diploma (regional host)", "Diplôme du BI (site régional)"))] },
  { id: "iona", board: "dpcdsb", name: "Iona", addr: "Mississauga", fraser: F(6.2, 349, null), progs: [P("arts", x("Regional Arts: danza, teatro, música, medios y artes visuales", "Regional Arts: dance, drama, music, media and visual arts", "Arts régionaux : danse, théâtre, musique, médias et arts visuels")), P("shsm", x("Arts & Culture", "Arts & Culture", "Arts et culture"))] },
  { id: "joan", board: "dpcdsb", name: "St. Joan of Arc", addr: "Mississauga", fraser: F(5.9, 401, 6.7), progs: [P("stem", x("Regional STEAM, Grades 9–12", "Regional STEAM, Grades 9–12", "STEAM régional, 9e–12e année"))] },
  { id: "martin", board: "dpcdsb", name: "St. Martin", addr: "Mississauga", fraser: F(4.9, 559, 5.9), progs: [P("sports", x("Regional Sports", "Regional Sports", "Sports régional"))] },
  { id: "marcellinus", board: "dpcdsb", name: "St. Marcellinus", addr: "Mississauga", fraser: F(7.9, 95, 8.1), progs: [P("shsm", x("Arts & Culture", "Arts & Culture", "Arts et culture"))] },
  { id: "ascension", board: "dpcdsb", name: "Ascension of Our Lord", addr: "Mississauga", fraser: F(4.9, 559, 5.4), progs: [P("shsm", x("Business", "Business", "Affaires"))] },
  { id: "carmel", board: "dpcdsb", name: "Our Lady of Mount Carmel", addr: "Mississauga", fraser: F(6.9, 238, 7.0), progs: [] },
  { id: "romero", board: "dpcdsb", name: "St. Oscar Romero", addr: "2495 Credit Valley Rd", fraser: null, progs: [P("alt", x("Programa alternativo del DPCDSB", "DPCDSB alternative program", "Programme alternatif du DPCDSB"))] },

  // ---------------- Peel (public) ----------------
  { id: "johnfraser", board: "peel", name: "John Fraser SS", addr: "Mississauga", fraser: F(8.8, 29, null), progs: [P("ap", x("RLCP: Advanced Placement", "RLCP: Advanced Placement", "RLCP : Advanced Placement"))] },
  { id: "streetsville", board: "peel", name: "Streetsville SS", addr: "Mississauga", fraser: F(7.9, 95, null), progs: [] },
  { id: "lornepark", board: "peel", name: "Lorne Park SS", addr: "Mississauga", fraser: F(7.6, 130, null), progs: [] },
  { id: "portcredit", board: "peel", name: "Port Credit SS", addr: "Mississauga", fraser: F(7.2, 178, null), progs: [P("stem", x("RLCP: SciTech", "RLCP: SciTech", "RLCP : SciTech")), P("strings", x("RLCP: Strings", "RLCP: Strings", "RLCP : Cordes"))] },
  { id: "cawthra", board: "peel", name: "Cawthra Park SS", addr: "Mississauga", fraser: F(7.1, 201, null), progs: [P("arts", x("RLCP: Arts (al sur de la 401)", "RLCP: Arts (south of the 401)", "RLCP : Arts (au sud de la 401)"))] },
  { id: "glenforest", board: "peel", name: "Glenforest SS", addr: "Mississauga", fraser: F(6.8, 254, null), progs: [P("ib", x("RLCP: MYP IB (vía al Diploma)", "RLCP: MYP IB (path to the Diploma)", "RLCP : PEI du BI (voie vers le diplôme)"))] },
  { id: "mississ", board: "peel", name: "Mississauga SS", addr: "Mississauga", fraser: F(6.7, 275, null), progs: [] },
  { id: "erindale", board: "peel", name: "Erindale SS", addr: "Mississauga", fraser: F(6.2, 349, null), progs: [P("ib", x("RLCP: Pre-IB (vía al Diploma)", "RLCP: Pre-IB (path to the Diploma)", "RLCP : pré-BI (voie vers le diplôme)"))] },
  { id: "meadowvale", board: "peel", name: "Meadowvale SS", addr: "Mississauga", fraser: F(6.1, 367, null), progs: [P("ibt", x("RLCP: IBT", "RLCP: IBT", "RLCP : IBT"))] },
  { id: "stephenlewis", board: "peel", name: "Stephen Lewis SS", addr: "Mississauga", fraser: F(6.0, 390, null), progs: [] },
  { id: "rickhansen", board: "peel", name: "Rick Hansen SS", addr: "Mississauga", fraser: F(5.5, 478, null), progs: [] },
  { id: "applewood", board: "peel", name: "Applewood Heights SS", addr: "Mississauga", fraser: F(5.4, 497, null), progs: [] },
  { id: "lma", board: "peel", name: "Lincoln M. Alexander SS", addr: "Mississauga", fraser: F(4.8, 573, null), progs: [] },
  { id: "clarkson", board: "peel", name: "Clarkson SS", addr: "Mississauga", fraser: F(4.6, 591, null), progs: [] },
  { id: "tlkennedy", board: "peel", name: "Thomas L. Kennedy SS", addr: "Mississauga", fraser: F(3.3, 694, null),
    progs: [P("ibt", x("RLCP: IBT", "RLCP: IBT", "RLCP : IBT")), P("shsm", x("Business e ICT", "Business and ICT", "Affaires et TIC"))] },
  { id: "westcredit", board: "peel", name: "West Credit SS", addr: "Mississauga", fraser: F(0.9, 737, null),
    progs: [P("trades", x("RLCP: Regional Skilled Trades", "RLCP: Regional Skilled Trades", "RLCP : métiers spécialisés régionaux"))],
    fnote: x("Valor inusualmente bajo: revisa el informe original antes de sacar conclusiones.", "Unusually low value: check the original report before drawing conclusions.", "Valeur inhabituellement basse : consultez le bulletin original avant de tirer des conclusions.") },
  { id: "gordon", board: "peel", name: "Gordon Graydon", addr: "Mississauga", fraser: null, progs: [] },

  // ---------------- French-language Catholic ----------------
  { id: "famille", board: "fr", name: "Sainte-Famille", addr: "Mississauga", fraser: F(7.3, 158, 7.4), progs: [],
    fnote: x("Escuela de lengua francesa: el ingreso exige elegibilidad como titular de derechos (sección 23).", "French-language school: entry requires rights-holder eligibility (section 23).", "École de langue française : l'admission exige l'admissibilité comme ayant droit (article 23).") },
];

/* ------------------------------------------------------------------ */
/* Regional programs. hosts: [name, inMississauga]                     */
/* ------------------------------------------------------------------ */
const H = (n, m = false) => ({ n, m });

export const PROGRAMS = [
  // DPCDSB
  { id: "ap", board: "dpcdsb", tag: "ap", start: "9", entry: "apply", name: x("Advanced Placement (AP)", "Advanced Placement (AP)", "Advanced Placement (AP)"),
    hosts: [H("St. Joseph CSS", true), H("St. Edmund Campion CSS (Brampton)")],
    p: x("Cursos de nivel universitario dentro de la secundaria. No es «una escuela más difícil». Se elige materia por materia y los exámenes AP pueden dar crédito universitario. St. Joseph atiende a Mississauga.", "University-level courses inside high school. It is not “a harder school”. You choose subject by subject and AP exams can earn university credit. St. Joseph serves Mississauga.", "Cours de niveau universitaire au secondaire. Ce n'est pas « une école plus difficile ». On choisit matière par matière et les examens AP peuvent donner des crédits universitaires. St. Joseph dessert Mississauga.") },
  { id: "ib", board: "dpcdsb", tag: "ib", start: "11", entry: "apply", name: x("International Baccalaureate (IB)", "International Baccalaureate (IB)", "Baccalauréat international (BI)"),
    hosts: [H("St. Francis Xavier CSS", true), H("St. Paul CSS", true), H("Notre Dame CSS (Brampton)")],
    p: x("Diploma preuniversitario de dos años. El estudiante elige una materia de cada uno de seis grupos. Es un paquete integrado, no modular como AP.", "Two-year pre-university diploma. The student chooses one subject from each of six groups. It is an integrated package, not modular like AP.", "Diplôme préuniversitaire de deux ans. L'élève choisit une matière dans chacun des six groupes. C'est un ensemble intégré, non modulaire comme l'AP.") },
  { id: "steam", board: "dpcdsb", tag: "stem", start: "9", entry: "apply", name: x("Regional STEM / STEAM", "Regional STEM / STEAM", "STIM / STEAM régional"),
    hosts: [H("St. Joan of Arc CSS", true), H("St. Marguerite d'Youville CSS (Brampton)"), H("St. Augustine CSS (Brampton)")],
    p: x("Grades 9–12. En St. Joan of Arc: proyectos prácticos, indagación, design thinking y resolución creativa de problemas. Las sedes de Brampton añaden opciones de SHSM (Healthcare, ICT, Hospitality) e iSTEAM.", "Grades 9–12. At St. Joan of Arc: hands-on projects, inquiry, design thinking and creative problem solving. The Brampton sites add SHSM options (Healthcare, ICT, Hospitality) and iSTEAM.", "9e–12e année. À St. Joan of Arc : projets pratiques, enquête, design thinking et résolution créative de problèmes. Les sites de Brampton ajoutent des options de MHS (santé, TIC, accueil) et l'iSTEAM.") },
  { id: "arts", board: "dpcdsb", tag: "arts", start: "9", entry: "apply", name: x("Regional Arts", "Regional Arts", "Arts régionaux"),
    hosts: [H("Iona CSS", true), H("St. Thomas Aquinas CSS (Brampton)"), H("St. Roch CSS (Brampton)")],
    p: x("Danza, teatro, música instrumental y vocal, medios y artes visuales. Puede pedir audición o portafolio.", "Dance, drama, instrumental and vocal music, media and visual arts. May require an audition or portfolio.", "Danse, théâtre, musique instrumentale et vocale, médias et arts visuels. Peut exiger une audition ou un portfolio.") },
  { id: "sports", board: "dpcdsb", tag: "sports", start: "9", entry: "apply", name: x("Regional Sports", "Regional Sports", "Sports régional"),
    hosts: [H("St. Martin CSS", true)],
    p: x("Deporte, condición física, liderazgo y educación física. No es solo para atletas de élite. Puede conectar con un SHSM de Sports.", "Sport, fitness, leadership and physical education. Not only for elite athletes. Can connect to a Sports SHSM.", "Sport, conditionnement physique, leadership et éducation physique. Pas seulement pour les athlètes d'élite. Peut se relier à une MHS en sports.") },
  { id: "bakery", board: "dpcdsb", tag: "bakery", start: "10", entry: "apply", name: x("Bakery School", "Bakery School", "École de boulangerie"),
    hosts: [H("Father Michael Goetz CSS", true)],
    p: x("Ruta técnica dentro de una secundaria general. Cuatro cursos de panadería y experiencia real con Co-op u OYAP. Grades 10–12.", "A technical pathway inside a general high school. Four bakery courses and real experience through Co-op or OYAP. Grades 10–12.", "Voie technique au sein d'une école secondaire générale. Quatre cours de boulangerie et une expérience réelle par l'éducation coopérative ou le PAJO. 10e–12e année.") },
  { id: "fi", board: "dpcdsb", tag: "fi", start: "9", entry: "apply", name: x("French Immersion (secundaria)", "French Immersion (secondary)", "Immersion française (secondaire)"),
    hosts: [H("Philip Pocock CSS", true), H("Loyola CSS", true), H("Cardinal Leger CSS (Brampton)")],
    p: x("Continuación de French Immersion para quienes la cursaron en primaria (desde Grade 1). Tiene su propio proceso de registro.", "Continuation of French Immersion for students who took it in elementary (from Grade 1). It has its own registration process.", "Suite de l'immersion française pour les élèves qui l'ont suivie à l'élémentaire (dès la 1re année). Processus d'inscription distinct.") },
  { id: "ef", board: "dpcdsb", tag: "ef", start: "9", entry: "apply", name: x("Extended French (secundaria)", "Extended French (secondary)", "Français prolongé (secondaire)"),
    hosts: [H("Philip Pocock CSS", true), H("St. Aloysius Gonzaga CSS", true), H("Loyola CSS", true), H("Robert F. Hall CSS (Caledon)"), H("Cardinal Leger CSS (Brampton)"), H("St. Thomas Aquinas CSS (Brampton)")],
    p: x("Seis escuelas secundarias en el DPCDSB; tres están en Mississauga. Cada centro recibe estudiantes de escuelas primarias designadas.", "Six secondary schools in DPCDSB; three are in Mississauga. Each centre takes students from designated elementary schools.", "Six écoles secondaires au DPCDSB; trois sont à Mississauga. Chaque centre accueille des élèves d'écoles élémentaires désignées.") },
  { id: "alt", board: "dpcdsb", tag: "alt", start: "9", entry: "apply", name: x("Programa alternativo", "Alternative program", "Programme alternatif"),
    hosts: [H("St. Oscar Romero CSS", true)],
    p: x("Alternativa a la secundaria tradicional. Confirma requisitos y proceso en el sitio de la escuela.", "An alternative to traditional high school. Confirm requirements and process on the school's website.", "Solution de rechange au secondaire traditionnel. Confirmez les exigences et le processus sur le site de l'école.") },

  // Peel RLCP
  { id: "p-ib", board: "peel", tag: "ib", start: "9", entry: "apply", name: x("IB", "IB", "BI"),
    hosts: [H("Glenforest SS (MYP)", true), H("Erindale SS (Pre-IB)", true), H("Turner Fenton SS (MYP, Brampton)"), H("Harold M. Brathwaite SS (Pre-IB, Brampton)")],
    p: x("El Diploma IB se accede vía MYP (Glenforest, Turner Fenton) o Pre-IB (Erindale, Harold M. Brathwaite).", "The IB Diploma is reached through MYP (Glenforest, Turner Fenton) or Pre-IB (Erindale, Harold M. Brathwaite).", "On accède au diplôme du BI par le PEI (Glenforest, Turner Fenton) ou le pré-BI (Erindale, Harold M. Brathwaite)."),
    second: x("Grade 11: requiere matemáticas de Grade 10 y MCR3U, y francés académico de Grade 10.", "Grade 11: requires Grade 10 math and MCR3U, and Grade 10 Academic French.", "11e année : exige les mathématiques de 10e année et MCR3U, et le français théorique de 10e année.") },
  { id: "p-arts", board: "peel", tag: "arts", start: "9", entry: "apply", name: x("Arts", "Arts", "Arts"),
    hosts: [H("Cawthra Park SS (al sur de la 401)", true), H("Mayfield SS (al norte de la 401, Caledon)")],
    p: x("Danza, teatro, música (instrumental o vocal) o artes visuales. Requiere audición o portafolio.", "Dance, drama, music (instrumental or vocal) or visual arts. Requires an audition or portfolio.", "Danse, théâtre, musique (instrumentale ou vocale) ou arts visuels. Audition ou portfolio requis."),
    second: x("Grade 10 (para estudiantes actuales de Grade 9).", "Grade 10 (for current Grade 9 students).", "10e année (pour les élèves actuels de 9e année).") },
  { id: "p-ap", board: "peel", tag: "ap", start: "9", entry: "apply", name: x("Advanced Placement (AP)", "Advanced Placement (AP)", "Advanced Placement (AP)"),
    hosts: [H("John Fraser SS", true), H("Central Peel SS (Brampton)")],
    p: x("Preparación universitaria para estudiantes muy motivados. Incluye evaluación presencial de numeracia y literacidad.", "University readiness for highly motivated students. Includes an in-person numeracy and literacy assessment.", "Préparation à l'université pour des élèves très motivés. Comprend une évaluation en personne en numératie et en littératie.") },
  { id: "p-scitech", board: "peel", tag: "stem", start: "9", entry: "apply", name: x("SciTech", "SciTech", "SciTech"),
    hosts: [H("Port Credit SS", true), H("Chinguacousy SS (Brampton)")],
    p: x("STEM con alianzas con instituciones postsecundarias e industria, tecnología de estándar industrial, excursiones y competencias.", "STEM with post-secondary and industry partners, industry-standard technology, excursions and competitions.", "STIM avec partenaires postsecondaires et industriels, technologie aux normes de l'industrie, sorties et compétitions.") },
  { id: "p-ibt", board: "peel", tag: "ibt", start: "9", entry: "apply", name: x("International Business & Technology (IBT)", "International Business & Technology (IBT)", "International Business & Technology (IBT)"),
    hosts: [H("Meadowvale SS", true), H("T.L. Kennedy SS", true), H("North Park SS (Brampton)")],
    p: x("Negocios y tecnología con mirada global, aprendizaje por proyectos, emprendimiento, robótica y STEM. Pide un video de 1:30.", "Business and technology with a global outlook, project-based learning, entrepreneurship, robotics and STEM. Requires a 1:30 video.", "Affaires et technologie avec un regard mondial, apprentissage par projets, entrepreneuriat, robotique et STIM. Vidéo de 1 min 30 requise.") },
  { id: "p-tet", board: "peel", tag: "trades", start: "9", entry: "apply", name: x("Transportation, Engineering & Technology", "Transportation, Engineering & Technology", "Transport, ingénierie et technologie"),
    hosts: [H("Bramalea SS (Brampton)")],
    p: x("Industrias de transporte terrestre, marítimo y aeroespacial, con apoyo de socios de la industria. La sede está fuera de Mississauga.", "Land, marine and aerospace transportation industries, with industry partner support. The host is outside Mississauga.", "Industries du transport terrestre, maritime et aérospatial, avec l'appui de partenaires. Le site est hors de Mississauga.") },
  { id: "p-strings", board: "peel", tag: "strings", start: "9", entry: "apply", name: x("Strings", "Strings", "Cordes"),
    hosts: [H("Port Credit SS", true), H("Central Peel SS (Brampton)")],
    p: x("Estudio de un instrumento de cuerda, de principiante a avanzado, con experiencia orquestal. Requiere audición.", "Study of a string instrument, from beginner to advanced, with an orchestral experience. Requires an audition.", "Étude d'un instrument à cordes, du débutant à l'avancé, avec expérience orchestrale. Audition requise.") },
  { id: "p-trades", board: "peel", tag: "trades", start: "9", entry: "apply", name: x("Regional Skilled Trades", "Regional Skilled Trades", "Métiers spécialisés régionaux"),
    hosts: [H("West Credit SS", true), H("Judith Nyman SS (Brampton)")],
    p: x("Aprendizaje experiencial en oficios como construcción. Incluye entrevista, audición y evaluación definida por la escuela.", "Experiential learning in trades such as construction. Includes a written response, interview and school-defined assessment.", "Apprentissage expérientiel dans des métiers comme la construction. Comprend une réponse écrite, une entrevue et une évaluation définie par l'école."),
    second: x("Grade 11.", "Grade 11.", "11e année.") },
];
