// Questionnaire content (es / en / fr-CA) and scoring weights.
// Each option adds weights to program tags (see TAGS in content.js).
// Special keys: _prog / _regular (program vs regular school), _board, _transport.

const x = (es, en, fr) => ({ es, en, fr });

export const QUIZ_UI = {
  es: {
    title: "¿Qué secundaria encaja contigo? | Highschool Navigator",
    metaDesc: "Cuestionario anónimo de 3 minutos para explorar posibles secundarias y programas en Mississauga según tus intereses. Incluye resultado en PDF.",
    back: "Volver a la guía",
    backShort: "Guía",
    langLabel: "Idioma",
    themeLabel: "Cambiar tema",
    eyebrow: "Cuestionario · 3 minutos",
    h1: "¿Qué secundaria podría encajar contigo?",
    lead: "Responde con lo primero que sientas. No hay respuestas correctas ni incorrectas. Al final verás ideas de escuelas y programas de Mississauga para explorar y podrás descargar un PDF.",
    bullets: ["Sin nombre, sin registro, sin cuenta", "Unos 12 toques, una pregunta a la vez", "Resultado en PDF, en el idioma que elijas"],
    notAdvice: "Es una orientación, no una asesoría vocacional ni académica. Una persona experta (orientador de tu escuela) puede ayudarte a decidir.",
    start: "Empezar",
    partAbout: "Sobre ti",
    partFamily: "Para la familia (opcional)",
    q: (i, n) => `Pregunta ${i} de ${n}`,
    next: "Siguiente",
    prev: "Atrás",
    skip: "Saltar",
    pickUpTo: (n) => `Elige hasta ${n}`,
    pickOne: "Elige una",
    finish: "Ver mis ideas",
    resultsH: "Tus ideas para explorar",
    resultsLead: "Según tus respuestas, estas escuelas y programas podrían gustarte. Son ideas para investigar, no una decisión.",
    profileH: "Tu perfil en una línea",
    schoolsH: "Escuelas para mirar de cerca",
    programsH: "Programas que podrían gustarte",
    nextH: "Siguientes pasos",
    below: "Tus sugerencias están justo abajo ↓",
    viewProfile: "Ver perfil completo",
    tapHint: "Toca la tarjeta para ver más. Puedes seleccionar y copiar cualquier texto.",
    nextSteps: [
      "Revisa los programas en la guía y anota cuáles piden solicitud, audición o portafolio.",
      "Asiste a las charlas y open houses (oct–nov 2026). Peel recibe solicitudes del 3 al 24 de noviembre de 2026.",
      "Confirma cuál es tu escuela por boundary (según tu dirección) en el buscador de escuelas de tu board.",
      "Habla con el orientador de tu escuela actual antes de decidir.",
    ],
    bands: { strong: "Encaje alto", good: "Buen encaje", possible: "Posible" },
    hosts: "Sedes: ",
    inMiss: "Mississauga",
    whyLabel: "Por qué aparece",
    noSignal: "Tus respuestas quedaron abiertas y no señalan un programa concreto. Es normal: explora el directorio completo y vuelve a intentarlo.",
    regularNote: "Ofrece la secundaria regular completa; confirma en la escuela sus opciones de SHSM y Co-op.",
    transportNote: "Este encaje depende de un programa regional. Si el transporte es difícil, revisa primero la escuela de tu boundary.",
    frenchNote: "Escuela de lengua francesa: exige elegibilidad como titular de derechos (sección 23).",
    pdf: "Descargar PDF",
    pdfBusy: "Generando…",
    retake: "Repetir el cuestionario",
    seeGuide: "Ver el directorio completo",
    shareH: "Ayuda a mejorar esta guía (opcional)",
    shareP: "Puedes compartir tus respuestas de forma anónima: sin nombre, sin correo, sin IP guardada y sin cookies. Solo se guardan las respuestas, el idioma, la fecha (sin hora) y las escuelas y programas sugeridos. Sirven para ver qué opciones interesan a las familias y se borran a los 24 meses. Si tienes menos de 13 años, hazlo con tu familia.",
    ageNote: "Si tienes menos de 13 años, haz el cuestionario con un adulto de tu familia.",
    privacy: "Política de privacidad",
    shareCheck: "Acepto compartir mis respuestas de forma anónima",
    shareBtn: "Enviar",
    shareOk: "¡Gracias! Tus respuestas anónimas se enviaron.",
    shareErr: "No se pudo enviar ahora. Tu resultado y el PDF siguen disponibles.",
    shareOff: "El envío anónimo aún no está activado en este sitio.",
    fsaLabel: "Primeras 3 letras de tu código postal (opcional)",
    fsaHint: "Ej. L4Z. Sirve solo para ver zonas de interés, nunca se pide la dirección.",
    fsaInvalid: "Formato: letra, número, letra (ej. L4Z).",
    pdfTitle: "Ideas de secundarias en Mississauga",
    pdfSub: "Resultado del cuestionario · Highschool Navigator",
    pdfDate: "Fecha",
    pdfDisclaimerH: "Importante",
    pdfDisclaimer: "Este documento es una orientación general basada en respuestas rápidas. No es asesoría vocacional ni académica, y no garantiza admisión ni ajuste. Confirma programas, requisitos, costos y fechas con cada escuela y board, y consulta al orientador de tu escuela.",
    pdfFooter: "Highschool Navigator Mississauga · Sitio informativo independiente, sin afiliación con DPCDSB, Peel ni Fraser Institute.",
    pdfAnswersH: "Tus respuestas",
  },
  en: {
    title: "Which high school might fit you? | Highschool Navigator",
    metaDesc: "An anonymous 3-minute questionnaire to explore possible high schools and programs in Mississauga based on your interests. Includes a PDF result.",
    back: "Back to the guide",
    backShort: "Guide",
    langLabel: "Language",
    themeLabel: "Toggle theme",
    eyebrow: "Questionnaire · 3 minutes",
    h1: "Which high school might fit you?",
    lead: "Answer with your first instinct. There are no right or wrong answers. At the end you will see ideas for Mississauga schools and programs to explore, and you can download a PDF.",
    bullets: ["No name, no sign-up, no account", "About 12 taps, one question at a time", "PDF result in the language you choose"],
    notAdvice: "This is guidance, not academic or career counselling. A qualified person (your school's guidance counsellor) can help you decide.",
    start: "Start",
    partAbout: "About you",
    partFamily: "For the family (optional)",
    q: (i, n) => `Question ${i} of ${n}`,
    next: "Next",
    prev: "Back",
    skip: "Skip",
    pickUpTo: (n) => `Pick up to ${n}`,
    pickOne: "Pick one",
    finish: "See my ideas",
    resultsH: "Your ideas to explore",
    resultsLead: "Based on your answers, these schools and programs might appeal to you. They are ideas to research, not a decision.",
    profileH: "Your profile in one line",
    schoolsH: "Schools to look at closely",
    programsH: "Programs you might like",
    nextH: "Next steps",
    below: "Your suggestions are right below ↓",
    viewProfile: "View full profile",
    tapHint: "Tap the card for more. You can select and copy any text.",
    nextSteps: [
      "Review the programs in the guide and note which ones require an application, audition or portfolio.",
      "Attend the info sessions and open houses (Oct–Nov 2026). Peel accepts applications Nov 3–24, 2026.",
      "Confirm which school is yours by boundary (based on your address) using your board's school locator.",
      "Talk to the guidance counsellor at your current school before deciding.",
    ],
    bands: { strong: "Strong fit", good: "Good fit", possible: "Possible" },
    hosts: "Hosts: ",
    inMiss: "Mississauga",
    whyLabel: "Why it shows up",
    noSignal: "Your answers were open and do not point to a specific program. That is normal: explore the full directory and try again.",
    regularNote: "Offers the full regular high school; confirm its SHSM and Co-op options with the school.",
    transportNote: "This match depends on a regional program. If transportation is difficult, check your boundary school first.",
    frenchNote: "French-language school: entry requires rights-holder eligibility (section 23).",
    pdf: "Download PDF",
    pdfBusy: "Generating…",
    retake: "Retake the questionnaire",
    seeGuide: "See the full directory",
    shareH: "Help improve this guide (optional)",
    shareP: "You can share your answers anonymously: no name, no email, no IP stored and no cookies. Only the answers, language, date (no time) and the suggested schools and programs are saved. They are used to see which options families are interested in and are deleted after 24 months. If you are under 13, do it with your family.",
    ageNote: "If you are under 13, take the questionnaire with an adult from your family.",
    privacy: "Privacy policy",
    shareCheck: "I agree to share my answers anonymously",
    shareBtn: "Send",
    shareOk: "Thank you! Your anonymous answers were sent.",
    shareErr: "Could not send right now. Your result and PDF are still available.",
    shareOff: "Anonymous sharing is not enabled on this site yet.",
    fsaLabel: "First 3 characters of your postal code (optional)",
    fsaHint: "E.g. L4Z. Used only to see areas of interest; your address is never requested.",
    fsaInvalid: "Format: letter, number, letter (e.g. L4Z).",
    pdfTitle: "High school ideas for Mississauga",
    pdfSub: "Questionnaire result · Highschool Navigator",
    pdfDate: "Date",
    pdfDisclaimerH: "Important",
    pdfDisclaimer: "This document is general guidance based on quick answers. It is not academic or career counselling and does not guarantee admission or fit. Confirm programs, requirements, costs and dates with each school and board, and talk to your school's guidance counsellor.",
    pdfFooter: "Highschool Navigator Mississauga · Independent informational site, not affiliated with DPCDSB, Peel or the Fraser Institute.",
    pdfAnswersH: "Your answers",
  },
  fr: {
    title: "Quelle école secondaire te convient? | Highschool Navigator",
    metaDesc: "Questionnaire anonyme de 3 minutes pour explorer des écoles secondaires et programmes possibles à Mississauga selon tes intérêts. Résultat en PDF.",
    back: "Retour au guide",
    backShort: "Guide",
    langLabel: "Langue",
    themeLabel: "Changer de thème",
    eyebrow: "Questionnaire · 3 minutes",
    h1: "Quelle école secondaire pourrait te convenir?",
    lead: "Réponds avec ta première impression. Il n'y a pas de bonne ou de mauvaise réponse. À la fin, tu verras des idées d'écoles et de programmes de Mississauga à explorer, et tu pourras télécharger un PDF.",
    bullets: ["Sans nom, sans inscription, sans compte", "Environ 12 clics, une question à la fois", "Résultat en PDF, dans la langue de ton choix"],
    notAdvice: "Il s'agit d'une orientation, pas de services-conseils scolaires ou professionnels. Une personne qualifiée (le personnel d'orientation de ton école) peut t'aider à décider.",
    start: "Commencer",
    partAbout: "À propos de toi",
    partFamily: "Pour la famille (facultatif)",
    q: (i, n) => `Question ${i} sur ${n}`,
    next: "Suivant",
    prev: "Retour",
    skip: "Passer",
    pickUpTo: (n) => `Choisis jusqu'à ${n}`,
    pickOne: "Choisis-en une",
    finish: "Voir mes idées",
    resultsH: "Tes idées à explorer",
    resultsLead: "Selon tes réponses, ces écoles et ces programmes pourraient te plaire. Ce sont des pistes à explorer, pas une décision.",
    profileH: "Ton profil en une ligne",
    schoolsH: "Écoles à regarder de près",
    programsH: "Programmes qui pourraient te plaire",
    nextH: "Prochaines étapes",
    below: "Tes suggestions sont juste en dessous ↓",
    viewProfile: "Voir le profil complet",
    tapHint: "Touche la carte pour en savoir plus. Tu peux sélectionner et copier n'importe quel texte.",
    nextSteps: [
      "Passe en revue les programmes du guide et note ceux qui exigent une demande, une audition ou un portfolio.",
      "Assiste aux séances d'information et aux portes ouvertes (oct.–nov. 2026). Peel reçoit les demandes du 3 au 24 novembre 2026.",
      "Confirme ton école de secteur (selon ton adresse) avec l'outil de recherche d'écoles de ton conseil.",
      "Parle au personnel d'orientation de ton école actuelle avant de décider.",
    ],
    bands: { strong: "Très bonne adéquation", good: "Bonne adéquation", possible: "Possible" },
    hosts: "Sites : ",
    inMiss: "Mississauga",
    whyLabel: "Pourquoi elle apparaît",
    noSignal: "Tes réponses sont restées ouvertes et ne pointent pas vers un programme précis. C'est normal : explore le répertoire complet et réessaie.",
    regularNote: "Offre le secondaire régulier complet; confirme auprès de l'école ses options de MHS et d'éducation coopérative.",
    transportNote: "Cette adéquation repose sur un programme régional. Si le transport est difficile, vérifie d'abord ton école de secteur.",
    frenchNote: "École de langue française : l'admission exige l'admissibilité comme ayant droit (article 23).",
    pdf: "Télécharger le PDF",
    pdfBusy: "Génération…",
    retake: "Refaire le questionnaire",
    seeGuide: "Voir le répertoire complet",
    shareH: "Aide à améliorer ce guide (facultatif)",
    shareP: "Tu peux partager tes réponses de façon anonyme : sans nom, sans courriel, sans adresse IP conservée et sans témoins (cookies). Seuls les réponses, la langue, la date (sans l'heure) et les écoles et programmes suggérés sont enregistrés. Ils servent à voir quelles options intéressent les familles et sont supprimés après 24 mois. Si tu as moins de 13 ans, fais-le avec ta famille.",
    ageNote: "Si tu as moins de 13 ans, fais le questionnaire avec un adulte de ta famille.",
    privacy: "Politique de confidentialité",
    shareCheck: "J'accepte de partager mes réponses de façon anonyme",
    shareBtn: "Envoyer",
    shareOk: "Merci! Tes réponses anonymes ont été envoyées.",
    shareErr: "Envoi impossible pour le moment. Ton résultat et le PDF restent disponibles.",
    shareOff: "Le partage anonyme n'est pas encore activé sur ce site.",
    fsaLabel: "3 premiers caractères de ton code postal (facultatif)",
    fsaHint: "Ex. L4Z. Sert seulement à voir les secteurs d'intérêt; ton adresse n'est jamais demandée.",
    fsaInvalid: "Format : lettre, chiffre, lettre (ex. L4Z).",
    pdfTitle: "Idées d'écoles secondaires à Mississauga",
    pdfSub: "Résultat du questionnaire · Highschool Navigator",
    pdfDate: "Date",
    pdfDisclaimerH: "Important",
    pdfDisclaimer: "Ce document est une orientation générale fondée sur des réponses rapides. Il ne constitue pas des services-conseils scolaires ou professionnels et ne garantit ni l'admission ni l'adéquation. Confirme les programmes, exigences, coûts et dates auprès de chaque école et conseil scolaire, et consulte le personnel d'orientation de ton école.",
    pdfFooter: "Highschool Navigator Mississauga · Site d'information indépendant, sans lien avec le DPCDSB, Peel ni l'Institut Fraser.",
    pdfAnswersH: "Tes réponses",
  },
};

/* One line per program tag: why it may appeal. */
export const TAG_WHY = {
  ib: x("Diploma estructurado y exigente, pensado para la universidad", "A structured, demanding diploma built for university", "Diplôme structuré et exigeant, conçu pour l'université"),
  ap: x("Cursos de nivel universitario, materia por materia", "University-level courses, subject by subject", "Cours de niveau universitaire, matière par matière"),
  arts: x("Programa de artes con audición o portafolio", "An arts program with audition or portfolio", "Programme d'arts avec audition ou portfolio"),
  stem: x("Aprendizaje por proyectos en ciencia y tecnología", "Project-based learning in science and technology", "Apprentissage par projets en sciences et technologie"),
  sports: x("Deporte, condición física y liderazgo", "Sport, fitness and leadership", "Sport, conditionnement physique et leadership"),
  fi: x("Continúa o profundiza el francés", "Continue or deepen your French", "Poursuivre ou approfondir le français"),
  ef: x("Más francés que el programa básico", "More French than the core program", "Plus de français que le programme de base"),
  bakery: x("Ruta técnica de panadería con Co-op u OYAP", "A technical bakery pathway with Co-op or OYAP", "Voie technique en boulangerie avec éducation coopérative ou PAJO"),
  trades: x("Aprendizaje práctico de oficios", "Hands-on learning in the trades", "Apprentissage pratique des métiers"),
  ibt: x("Negocios y tecnología con proyectos", "Business and technology through projects", "Affaires et technologie par projets"),
  strings: x("Música de cuerdas y experiencia orquestal", "String music and orchestral experience", "Musique à cordes et expérience orchestrale"),
  alt: x("Alternativa a la secundaria tradicional", "An alternative to traditional high school", "Solution de rechange au secondaire traditionnel"),
  shsm: x("Especialización con certificaciones y Co-op", "A specialization with certifications and Co-op", "Spécialisation avec certifications et éducation coopérative"),
};

/* ------------------------------------------------------------------ */
/* Questions                                                           */
/* part: "about" | "family". type: "multi" (max) | "single" | "fsa".   */
/* ------------------------------------------------------------------ */
const O = (v, e, es, en, fr, w = {}) => ({ v, e, l: x(es, en, fr), w });

export const QUESTIONS = [
  { id: "q1", part: "about", type: "multi", max: 3,
    t: x("¿Qué te gusta hacer más?", "What do you enjoy doing most?", "Qu'est-ce que tu aimes le plus faire?"),
    o: [
      O("tech", "💻", "Tecnología y programar", "Technology and coding", "La technologie et la programmation", { ibt: 2, stem: 2, shsm: 1, ap: 0.5 }),
      O("science", "🔬", "Ciencia y experimentos", "Science and experiments", "Les sciences et les expériences", { stem: 2.5, ap: 1.5, ib: 1 }),
      O("arts", "🎨", "Arte, diseño o teatro", "Art, design or drama", "L'art, le design ou le théâtre", { arts: 3, shsm: 0.5 }),
      O("music", "🎻", "Música y baile", "Music and dance", "La musique et la danse", { arts: 2, strings: 3 }),
      O("sports", "⚽", "Deporte y liderazgo", "Sports and leadership", "Le sport et le leadership", { sports: 3.5 }),
      O("business", "📈", "Negocios y emprender", "Business and entrepreneurship", "Les affaires et l'entrepreneuriat", { ibt: 3, shsm: 1.5, ap: 0.5 }),
      O("health", "🩺", "Ayudar a otros y salud", "Helping others and health", "Aider les autres et la santé", { shsm: 1.5, stem: 0.5, ap: 0.5 }),
      O("hands", "🛠️", "Construir, cocinar, hacer con las manos", "Building, cooking, making things", "Construire, cuisiner, fabriquer", { trades: 3, bakery: 3, shsm: 1, alt: 0.5 }),
      O("languages", "🌍", "Idiomas y culturas", "Languages and cultures", "Les langues et les cultures", { fi: 2.5, ef: 2.5, ib: 1.5 }),
      O("words", "📚", "Leer, escribir y debatir", "Reading, writing and debating", "Lire, écrire et débattre", { ib: 2, ap: 1.5, arts: 0.5 }),
    ] },
  { id: "q2", part: "about", type: "single",
    t: x("¿Cómo aprendes mejor?", "How do you learn best?", "Comment apprends-tu le mieux?"),
    o: [
      O("projects", "🧩", "Con proyectos y retos", "With projects and challenges", "Avec des projets et des défis", { stem: 1, ibt: 1.5, arts: 0.5, ib: 0.5 }),
      O("exams", "📝", "Estudiando a fondo y con exámenes", "Studying in depth and with exams", "En étudiant en profondeur, avec des examens", { ap: 2, ib: 1.5 }),
      O("hands", "🔧", "Practicando con las manos", "Practicing hands-on", "En pratiquant de mes mains", { trades: 2, bakery: 1.5, stem: 0.5, shsm: 0.5 }),
      O("talk", "💬", "Conversando y en grupo", "Discussing in groups", "En discutant en groupe", { ib: 1, arts: 0.5, fi: 0.5 }),
    ] },
  { id: "q3", part: "about", type: "single",
    t: x("¿Cuánto reto académico quieres?", "How much academic challenge do you want?", "Quel niveau de défi scolaire souhaites-tu?"),
    o: [
      O("high", "🚀", "Mucho: me gusta ir más rápido", "A lot: I like to go faster", "Beaucoup : j'aime aller plus vite", { ap: 2, ib: 2.5 }),
      O("medium", "⚖️", "Equilibrado", "Balanced", "Équilibré", {}),
      O("steady", "🌱", "A mi ritmo, con buen apoyo", "At my own pace, with good support", "À mon rythme, avec un bon soutien", { alt: 1, ap: -1, ib: -1 }),
    ] },
  { id: "q4", part: "about", type: "single",
    t: x("¿Y las matemáticas y la ciencia?", "And math and science?", "Et les mathématiques et les sciences?"),
    o: [
      O("love", "➕", "Me encantan", "I love them", "Je les adore", { stem: 1.5, ibt: 0.5, ap: 0.5 }),
      O("ok", "🙂", "Están bien", "They are fine", "Ça va", {}),
      O("other", "🎭", "Prefiero otras materias", "I prefer other subjects", "Je préfère d'autres matières", { stem: -1, ibt: -0.5 }),
    ] },
  { id: "q5", part: "about", type: "single",
    t: x("Después de la secundaria, ¿qué te imaginas?", "After high school, what do you picture?", "Après le secondaire, qu'est-ce que tu imagines?"),
    o: [
      O("uni", "🎓", "Universidad", "University", "L'université", { ap: 1.5, ib: 2 }),
      O("college", "🏫", "College", "College", "Le collège", { shsm: 1.5, ibt: 0.5, stem: 0.5 }),
      O("trade", "🧰", "Un oficio o aprendizaje", "A trade or apprenticeship", "Un métier ou un apprentissage", { trades: 2.5, bakery: 2, shsm: 1 }),
      O("work", "💼", "Trabajar pronto", "Working soon", "Travailler bientôt", { shsm: 1, trades: 1, bakery: 0.5 }),
      O("unsure", "🤷", "Aún no lo sé", "I do not know yet", "Je ne sais pas encore", {}),
    ] },
  { id: "q6", part: "about", type: "single",
    t: x("¿Te gustaría probar un trabajo real mientras estudias?", "Would you like to try a real job while you study?", "Aimerais-tu essayer un vrai emploi pendant tes études?"),
    o: [
      O("yes", "✅", "Sí, mucho", "Yes, a lot", "Oui, beaucoup", { shsm: 1.5, trades: 1, bakery: 1 }),
      O("maybe", "🤔", "Tal vez", "Maybe", "Peut-être", { shsm: 0.5 }),
      O("no", "🙅", "Prefiero solo estudiar", "I would rather just study", "Je préfère seulement étudier", {}),
    ] },
  { id: "q7", part: "about", type: "single",
    t: x("¿Y el francés?", "And French?", "Et le français?"),
    o: [
      O("cont", "🇨🇦", "Ya lo estudio a fondo y quiero seguir", "I already study it in depth and want to continue", "Je l'étudie déjà à fond et je veux continuer", { fi: 4, ef: 3 }),
      O("improve", "📈", "Quiero mejorarlo", "I want to improve it", "Je veux l'améliorer", { ef: 2, fi: 1, ib: 0.5 }),
      O("no", "➖", "No es prioridad", "It is not a priority", "Ce n'est pas une priorité", {}),
    ] },
  { id: "q8", part: "about", type: "single",
    t: x("¿Te sientes cómodo con una audición o un portafolio?", "Are you comfortable with an audition or portfolio?", "Es-tu à l'aise avec une audition ou un portfolio?"),
    o: [
      O("yes", "🎤", "Sí, sin problema", "Yes, no problem", "Oui, sans problème", {}),
      O("no", "😅", "Prefiero evitarlo", "I would rather avoid it", "Je préfère l'éviter", { arts: -3, strings: -3 }),
    ] },
  { id: "q9", part: "about", type: "single",
    t: x("¿Qué prefieres?", "What do you prefer?", "Que préfères-tu?"),
    o: [
      O("focus", "🎯", "Un programa con enfoque especial", "A program with a special focus", "Un programme à orientation particulière", { _prog: 1 }),
      O("regular", "🏠", "Una escuela regular con variedad", "A regular school with variety", "Une école régulière avec de la variété", { _regular: 1 }),
      O("unsure", "🤷", "No estoy seguro", "Not sure", "Je ne suis pas sûr", {}),
    ] },
  { id: "q10", part: "family", type: "single",
    t: x("Familia: ¿qué sistema prefieren?", "Family: which system do you prefer?", "Famille : quel système préférez-vous?"),
    o: [
      O("catholic", "⛪", "Católico (DPCDSB)", "Catholic (DPCDSB)", "Catholique (DPCDSB)", { _board: "catholic" }),
      O("public", "🏛️", "Público (Peel)", "Public (Peel)", "Public (Peel)", { _board: "public" }),
      O("either", "🤝", "Cualquiera", "Either", "L'un ou l'autre", {}),
      O("french", "⚜️", "Escuela de lengua francesa", "A French-language school", "Une école de langue française", { _board: "french" }),
    ] },
  { id: "q11", part: "family", type: "single",
    t: x("Familia: ¿pueden cubrir el transporte a un programa más lejano?", "Family: can you cover transportation to a farther program?", "Famille : pouvez-vous assumer le transport vers un programme plus éloigné?"),
    o: [
      O("yes", "🚗", "Sí", "Yes", "Oui", {}),
      O("limited", "🚌", "Con limitaciones", "With limits", "Avec des limites", { _transport: 1 }),
      O("no", "📍", "Preferimos quedarnos cerca de casa", "We prefer to stay close to home", "Nous préférons rester près de la maison", { _transport: 2 }),
    ] },
  { id: "q12", part: "family", type: "single",
    t: x("Familia: ¿en qué zona de Mississauga viven? (opcional)", "Family: which part of Mississauga do you live in? (optional)", "Famille : dans quel secteur de Mississauga habitez-vous? (facultatif)"),
    o: [
      O("east", "🌅", "Este", "East", "Est", {}),
      O("central", "🏙️", "Centro", "Central", "Centre", {}),
      O("west", "🌇", "Oeste", "West", "Ouest", {}),
      O("other", "🗺️", "Otra ciudad o prefiero no decir", "Another city or prefer not to say", "Une autre ville ou je préfère ne pas le dire", {}),
    ] },
];

/* Teen-tone overrides for the questionnaire (the Family tone uses QUIZ_UI). */
export const QUIZ_TEEN = {
  es: {
    eyebrow: "Vibe check · 3 minutos",
    h1: "¿Qué high school va contigo?",
    lead: "Responde con lo primero que sientas. No hay respuestas malas. Al final te sale una lista de escuelas y programas de Mississauga para explorar, y un PDF para guardar.",
    start: "Vamos",
    finish: "Ver mi resultado",
    resultsH: "Tu resultado",
    resultsLead: "Según lo que contestaste, esto podría ir contigo. Son ideas para investigar, no una decisión final.",
    profileH: "Tu vibe",
    schoolsH: "Escuelas para stalkear (con cariño)",
    programsH: "Programas que te pueden gustar",
    retake: "Repetir el vibe check",
    tick6: "6…", tick7: "…7 😏",
  },
  en: {
    eyebrow: "Vibe check · 3 minutes",
    h1: "Which high school matches your vibe?",
    lead: "Answer with your first instinct. No bad answers. At the end you get a list of Mississauga schools and programs to explore, plus a PDF to keep.",
    start: "Let's go",
    finish: "See my result",
    resultsH: "Your result",
    resultsLead: "Based on what you picked, these might fit. They are ideas to research, not a final decision.",
    profileH: "Your vibe",
    schoolsH: "Schools to check out",
    programsH: "Programs you might like",
    retake: "Retake the vibe check",
    tick6: "6…", tick7: "…7 😏",
  },
  fr: {
    eyebrow: "Vibe check · 3 minutes",
    h1: "Quelle école secondaire est faite pour toi?",
    lead: "Réponds avec ta première impression. Pas de mauvaise réponse. À la fin, tu obtiens une liste d'écoles et de programmes de Mississauga à explorer, et un PDF à garder.",
    start: "C'est parti",
    finish: "Voir mon résultat",
    resultsH: "Ton résultat",
    resultsLead: "Selon tes choix, ceci pourrait te convenir. Ce sont des pistes à explorer, pas une décision finale.",
    profileH: "Ton vibe",
    schoolsH: "Écoles à explorer",
    programsH: "Programmes qui pourraient te plaire",
    retake: "Refaire le vibe check",
    tick6: "6…", tick7: "…7 😏",
  },
};
