// Builds js/map-data.js: the decorative GTA outline shown before the street map is loaded (offline-safe).
// Data: OpenStreetMap contributors (ODbL): regional boundaries (Nominatim), Lake Ontario shore and the
// freeways (Overpass). Run: node scripts/pipeline/build-map.mjs
import fs from "node:fs/promises";
import path from "node:path";
import { get, ROOT } from "./lib.mjs";

const BBOX = { s: 43.28, n: 44.4, w: -80.15, e: -78.5 };
const W = 1000;
const kx = Math.cos((((BBOX.s + BBOX.n) / 2) * Math.PI) / 180);
const H = Math.round((W * (BBOX.n - BBOX.s)) / ((BBOX.e - BBOX.w) * kx));
const px = ([lon, lat]) => [((lon - BBOX.w) / (BBOX.e - BBOX.w)) * W, ((BBOX.n - lat) / (BBOX.n - BBOX.s)) * H];

function dp(pts, eps) { // Douglas-Peucker
  if (pts.length < 3) return pts;
  const [a, b] = [pts[0], pts.at(-1)];
  let idx = 0, dmax = 0;
  for (let i = 1; i < pts.length - 1; i++) {
    const [x, y] = pts[i];
    const dx = b[0] - a[0], dy = b[1] - a[1];
    const d = dx || dy ? Math.abs(dy * x - dx * y + b[0] * a[1] - b[1] * a[0]) / Math.hypot(dx, dy) : Math.hypot(x - a[0], y - a[1]);
    if (d > dmax) { dmax = d; idx = i; }
  }
  return dmax > eps ? [...dp(pts.slice(0, idx + 1), eps).slice(0, -1), ...dp(pts.slice(idx), eps)] : [a, b];
}
const path1 = (pts, close) => "M" + pts.map(([x, y]) => `${Math.round(x)},${Math.round(y)}`).join("L") + (close ? "Z" : "");

// --- boundaries: Nominatim search finds the relation, details.php returns its full polygon
const UAH = { delay: 1500, ttlHours: 24 * 60 };
async function polygonOf(query, relId) {
  if (!relId) {
    const r = await get(`https://nominatim.openstreetmap.org/search?q=${encodeURIComponent(query)}&format=json&limit=1&countrycodes=ca`, UAH);
    relId = JSON.parse(r.text)[0]?.osm_id;
  }
  const d = await get(`https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=${relId}&polygon_geojson=1&format=json`, UAH);
  const g = JSON.parse(d.text).geometry;
  if (!g) throw new Error("no geometry for " + query);
  const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
  return polys.map((p) => dp(p[0].map(px), 0.7)).filter((p) => p.length > 3).map((p) => path1(p, true)).join("");
}
const REG = { toronto: "Toronto, Ontario, Canada", peel: "Regional Municipality of Peel, Ontario", york: "Regional Municipality of York, Ontario", durham: "Regional Municipality of Durham, Ontario", halton: "Regional Municipality of Halton, Ontario" };
const regions = {};
for (const [k, q] of Object.entries(REG)) { regions[k] = await polygonOf(q); console.log(k, regions[k].length, "chars"); }
const lake = await polygonOf("Lake Ontario", 1206310); // OSM relation: Lake Ontario
console.log("lake", lake.length, "chars");

// --- Overpass helper (public mirror; the main instance rejects some clients)
const OV = "https://overpass.kumi.systems/api/interpreter";
async function overpass(q) {
  const r = await get(`${OV}?data=${encodeURIComponent(q)}`, { delay: 2000, ttlHours: 24 * 60, timeoutMs: 170000 });
  if (!r.ok) throw new Error("overpass " + (r.status || r.error));
  return JSON.parse(r.text).elements;
}
const bb = `${BBOX.s},${BBOX.w},${BBOX.n},${BBOX.e}`;

// --- Freeways
const KEEP = /^(ON )?(400|401|403|404|407|409|410|412|427|QEW)$/;
const ways = await overpass(`[out:json][timeout:90];way["highway"="motorway"]["ref"](${bb});out geom;`);
const byRef = {};
for (const w of ways) {
  const ref = (w.tags.ref || "").split(";").map((r) => r.trim()).find((r) => KEEP.test(r));
  if (ref) (byRef[ref.replace(/^ON /, "")] ||= []).push(dp(w.geometry.map((p) => px([p.lon, p.lat])), 1));
}
const roads = Object.entries(byRef).map(([ref, ls]) => ({ ref, d: ls.map((l) => path1(l)).join("") }));
const DVP = await overpass(`[out:json][timeout:60];way["highway"="motorway"]["name"~"Don Valley Parkway|Gardiner Expressway|Allen Road"](${bb});out geom;`);
roads.push({ ref: "DVP / Gardiner", d: DVP.map((w) => path1(dp(w.geometry.map((p) => px([p.lon, p.lat])), 1))).join("") });
console.log(roads.map((r) => `${r.ref}:${r.d.length}`).join(" "));

const LABELS = { Toronto: [43.70, -79.40], Mississauga: [43.59, -79.64], Brampton: [43.73, -79.76], Markham: [43.86, -79.29], Vaughan: [43.84, -79.51], "Richmond Hill": [43.88, -79.44], Oakville: [43.45, -79.69], Burlington: [43.33, -79.80], Milton: [43.52, -79.88], Oshawa: [43.90, -78.86], Whitby: [43.88, -78.94], Ajax: [43.85, -79.03], Pickering: [43.84, -79.09], Newmarket: [44.06, -79.46], Caledon: [43.87, -79.95], Georgina: [44.30, -79.45], Clarington: [43.93, -78.69], "Halton Hills": [43.63, -79.95] };
const labels = Object.entries(LABELS).map(([name, [lat, lon]]) => ({ name, p: px([lon, lat]).map(Math.round) }));

const out = `// GENERATED by scripts/pipeline/build-map.mjs. Map data © OpenStreetMap contributors (ODbL).
// Decorative GTA outline for the offline preview: regional boundaries, Lake Ontario, freeways, labels.
export const MAP = ${JSON.stringify({ w: W, h: H, bbox: BBOX, regions, lake, roads, labels })};
`;
await fs.writeFile(path.join(ROOT, "js/map-data.js"), out);
console.log("wrote js/map-data.js", out.length, "bytes");
