#!/usr/bin/env node
// Turns validated raw data (data/raw/<board>/) into the site modules:
//   js/data/summary.js            eager: which schools have details + their program tags (for the cards)
//   js/data/details/<board>.js    lazy: profiles, programs, registration, sessions, admissions per board
//   js/data/courses/<board>.js    lazy: course lists per school
// Run after validate.mjs:  node scripts/pipeline/build-details.mjs
import fs from "node:fs/promises";
import path from "node:path";
import { ROOT } from "./lib.mjs";
import { CURATED_INFO } from "../../js/data/roster.js";
import { SCHOOLS } from "../../js/content.js";
import { checkSchool, checkBoard } from "./schema.mjs";
import { BOARDS } from "../../js/content.js";

const ctx = { ids: new Set(SCHOOLS.map((s) => s.id)), boards: new Set(Object.keys(BOARDS)) };
const rawDir = path.join(ROOT, "data/raw");
const boards = (await fs.readdir(rawDir).catch(() => [])).filter((b) => ctx.boards.has(b)).sort();
const summary = {}, detailBoards = [], courseBoards = [];
const strip = (o) => JSON.parse(JSON.stringify(o, (k, v) => (v === null || v === "" || (Array.isArray(v) && !v.length) ? undefined : v)));

await fs.mkdir(path.join(ROOT, "js/data/details"), { recursive: true });
await fs.mkdir(path.join(ROOT, "js/data/courses"), { recursive: true });
for (const b of boards) {
  const dir = path.join(rawDir, b);
  const files = (await fs.readdir(dir)).filter((f) => f.endsWith(".json"));
  const out = { board: b, schools: {}, programs: [], sessions: [] };
  const crs = { year: {}, courses: {} };
  let skipped = 0;
  for (const f of files) {
    const d = JSON.parse(await fs.readFile(path.join(dir, f), "utf8"));
    if (f.endsWith(".courses.json")) {
      const id = f.replace(/\.courses\.json$/, "");
      if (ctx.ids.has(id) && d.courses?.length) { crs.courses[id] = d.courses; crs.year[id] = d.year || null; }
      continue;
    }
    if (f === "_board.json") {
      if (checkBoard(d, ctx).length) { console.warn(`skip ${b}/${f}: fails validation (run validate.mjs)`); skipped++; continue; }
      out.registration = strip(d.registration);
      out.scrapedAt = d.scrapedAt;
      out.programs = (d.programs || []).map((p) => strip({ ...p, id: `${b}-${p.id.replace(new RegExp(`^${b}-`), "")}` }));
      out.sessions.push(...(d.sessions || []).map((s) => strip({ ...s, school: s.school || null })));
      continue;
    }
    if (checkSchool(d, ctx).length) { console.warn(`skip ${b}/${f}: fails validation`); skipped++; continue; }
    out.schools[d.id] = strip({
      curated: d.id in CURATED_INFO || SCHOOLS.find((s) => s.id === d.id && !s.pending) ? 1 : undefined,
      site: d.site, focus: d.focus, kv: d.kv, shsm: d.shsm, other: d.other, cal: d.calendarUrl, at: d.scrapedAt,
      progs: (d.programs || []).map((p) => ({ k: p.tag, n: p.note, name: p.name, url: p.url, grades: p.grades, entry: p.entry })),
      admissions: (d.admissions || []).map((a) => ({ ...a })),
      sessions: d.sessions || [], missing: d.missing, sources: d.sources,
    });
    const s = out.schools[d.id];
    if (!s.curated) summary[d.id] = [...new Set([...(d.programs || []).map((p) => p.tag), ...((d.shsm || []).length ? ["shsm"] : [])])];
  }
  for (const id of Object.keys(crs.courses)) if (out.schools[id]) out.schools[id].courses = 1;
  if (Object.keys(out.schools).length || out.programs.length || out.registration) {
    detailBoards.push(b);
    await fs.writeFile(path.join(ROOT, `js/data/details/${b}.js`), `// GENERATED by scripts/pipeline/build-details.mjs from data/raw/${b}. Do not edit by hand.\nexport default ${JSON.stringify(out)};\n`);
  }
  if (Object.keys(crs.courses).length) {
    courseBoards.push(b);
    await fs.writeFile(path.join(ROOT, `js/data/courses/${b}.js`), `// GENERATED by scripts/pipeline/build-details.mjs. Course lists as published by each school (course titles in English).\nexport default ${JSON.stringify(crs)};\n`);
  }
  console.log(b.padEnd(10), `${Object.keys(out.schools).length} schools, ${out.programs.length} programs, ${Object.keys(crs.courses).length} course lists${skipped ? `, ${skipped} skipped` : ""}`);
}
await fs.writeFile(path.join(ROOT, "js/data/summary.js"), `// GENERATED by scripts/pipeline/build-details.mjs. Which schools have collected details (program tags) and which boards have lazy data modules.\nexport const DETAIL_BOARDS = ${JSON.stringify(detailBoards)};\nexport const COURSE_BOARDS = ${JSON.stringify(courseBoards)};\nexport const SUMMARY = ${JSON.stringify(summary)};\n`);
console.log("summary:", Object.keys(summary).length, "schools with details");
