#!/usr/bin/env node
// Matches the Fraser rows (data/fraser-2025.json) to GTA roster schools -> data/fraser-match.json + data/fraser-review.md.
// A match needs the report's school name words to be contained in the roster name AND the report city to fit the school's
// city. Anything ambiguous or unmatched is listed for a human; the hand-curated scores always stay as they are.
import fs from "node:fs";
import path from "node:path";
import { ROOT } from "./lib.mjs";
import { SCHOOLS } from "../../js/content.js";
import { CURATED_INFO } from "../../js/data/roster.js";

const rows = JSON.parse(fs.readFileSync(path.join(ROOT, "data/fraser-2025.json"), "utf8")).rows;
const overrides = fs.existsSync(path.join(ROOT, "data/fraser-overrides.json")) ? JSON.parse(fs.readFileSync(path.join(ROOT, "data/fraser-overrides.json"), "utf8")) : {};

const POSTAL = { Thornhill: ["Vaughan", "Markham", "Richmond Hill"], Woodbridge: ["Vaughan"], Maple: ["Vaughan"], Concord: ["Vaughan"], Kleinburg: ["Vaughan"], Unionville: ["Markham"], Stouffville: ["Whitchurch-Stouffville"], Bolton: ["Caledon"], Keswick: ["Georgina"], Sutton: ["Georgina"], "King City": ["King"], Nobleton: ["King"], Georgetown: ["Halton Hills"], Acton: ["Halton Hills"], Bowmanville: ["Clarington"], Courtice: ["Clarington"], "Port Perry": ["Scugog"], Cannington: ["Brock"], Toronto: ["Toronto"], Scarborough: ["Toronto"], Etobicoke: ["Toronto"], "North York": ["Toronto"], "East York": ["Toronto"] };
const DIRECT = new Set(["Mississauga", "Brampton", "Markham", "Richmond Hill", "Aurora", "Newmarket", "Pickering", "Ajax", "Whitby", "Oshawa", "Oakville", "Burlington", "Milton", "Caledon", "Uxbridge", "Vaughan", "Clarington"]);
const citiesOf = (c0) => { const c = c0.replace(/\b\w+/g, (w) => w[0] + w.slice(1).toLowerCase()); return POSTAL[c] || (DIRECT.has(c) ? [c] : null); };

const STOP = new Set(["secondary", "school", "high", "collegiate", "institute", "ci", "ss", "hs", "css", "catholic", "the", "of", "de", "la", "le", "ecole", "esc", "academy", "program", "and", "for", "saint", "st", "ste", "college", "cvi", "district"]);
const tok = (s) => s.toLowerCase().replace(/\./g, "").normalize("NFD").replace(/[̀-ͯ]/g, "").replace(/[’']/g, "").replace(/&/g, " and ").split(/[^a-z0-9]+/).filter((w) => w && !STOP.has(w));

const match = {}, review = [];
const used = new Map();
for (const r of rows) {
  const cities = citiesOf(r.city);
  if (!cities) continue; // not in the GTA
  const rt = tok(r.name);
  if (!rt.length) { review.push(`${r.rank} ${r.name} (${r.city}): name too generic to match`); continue; }
  const cand = SCHOOLS.filter((s) => cities.includes(s.city) && rt.every((w) => tok(s.name).includes(w)));
  const key = `${r.name}|${r.city}|${r.score}`;
  const ov = overrides[key];
  const pick = ov !== undefined ? (ov ? [SCHOOLS.find((s) => s.id === ov)] : []) : cand;
  if (pick.length === 1 && pick[0]) {
    const s = pick[0];
    if (used.has(s.id)) review.push(`${s.id}: matched twice (${used.get(s.id)} and ${r.rank} ${r.name}, ${r.city}); add an override`);
    used.set(s.id, `${r.rank} ${r.name}`);
    match[s.id] = { score: r.score, rank: r.rank, prev: r.prev, name: r.name, city: r.city };
  } else if (pick.length > 1) review.push(`${r.rank} ${r.name} (${r.city}, ${r.score}): ambiguous: ${pick.map((s) => s.id).join(", ")}   key: ${key}`);
  else review.push(`${r.rank} ${r.name} (${r.city}, ${r.score}): no roster school   key: ${key}`);
}
// Site module: scores for schools that are NOT hand-curated (curated schools keep their own, identical, values).
const handCurated = new Set(Object.keys(CURATED_INFO));
const mod = Object.fromEntries(Object.entries(match).filter(([id]) => !handCurated.has(id)).map(([id, m]) => [id, [m.score, m.rank, m.prev]]));
fs.writeFileSync(path.join(ROOT, "js/data/fraser.js"), `// GENERATED by scripts/pipeline/match-fraser.mjs from the Fraser Institute Report Card on Ontario's Secondary Schools 2025 (2024-25 school year).\n// id -> [overall rating out of 10, rank in Ontario, previous rating or null]. Only academic test results: see the note on the site.\nexport const FRASER_SCORES = ${JSON.stringify(mod)};\n`);
fs.writeFileSync(path.join(ROOT, "data/fraser-match.json"), JSON.stringify(match, null, 0) + "\n");
fs.writeFileSync(path.join(ROOT, "data/fraser-review.md"), "# Fraser matching review\n\nRows in a GTA city that could not be matched to exactly one roster school. Add `\"<key>\": \"<school-id>\"` (or null to ignore) to data/fraser-overrides.json.\n\n" + review.map((l) => `- ${l}`).join("\n") + "\n");
const curated = SCHOOLS.filter((s) => s.fraser && !s.pending && !(s.id in match));
console.log("matched:", Object.keys(match).length, "| to review:", review.length, "| curated with a score but not matched:", curated.map((s) => s.id).join(","));
let diff = 0; for (const s of SCHOOLS) if (s.fraser && match[s.id] && (s.fraser.score !== match[s.id].score || s.fraser.rank !== match[s.id].rank)) { diff++; console.log("DIFF", s.id, s.fraser, match[s.id]); }
console.log("curated scores that differ from the report:", diff);
